import { describe, it, expect } from 'vitest';
import { existsSync, statSync } from 'node:fs';
import { execFileSync, spawnSync } from 'node:child_process';
import { resolve } from 'node:path';
import { MUSIC_TRACKS } from '../../src/audio/music-selector';

// Zimmer + Rahman pin: every music slot must be a REAL audio bed
// (raga drone + melody + tabla), not a silent placeholder.
// Deterministic procedural synthesis is generated by scripts/generate-music.mjs
// at `npm pretest` time.

const PUBLIC = resolve(__dirname, '..', '..', 'public');

describe('music quality contract (Zimmer + Rahman)', () => {
  it('every mood slot has a non-trivial audio file (>50KB)', () => {
    for (const track of Object.values(MUSIC_TRACKS)) {
      const p = resolve(PUBLIC, track.file);
      expect(existsSync(p), `${track.file} missing`).toBe(true);
      const size = statSync(p).size;
      expect(size, `${track.file} only ${size} bytes — silent placeholder?`).toBeGreaterThan(50_000);
    }
  });

  it('every mood slot has a 30s duration (loop bed)', () => {
    for (const track of Object.values(MUSIC_TRACKS)) {
      const p = resolve(PUBLIC, track.file);
      const dur = parseFloat(
        execFileSync('ffprobe', [
          '-v',
          'error',
          '-show_entries',
          'stream=duration',
          '-of',
          'default=nw=1:nk=1',
          p,
        ]).toString(),
      );
      expect(dur, `${track.file} duration ${dur}s`).toBeGreaterThan(25);
      expect(dur).toBeLessThanOrEqual(31);
    }
  });

  it('files are not pure silence (RMS energy > threshold)', () => {
    // Sample one mood — heroic_triumphant must have actual audio content.
    const p = resolve(PUBLIC, 'audio/music/heroic_triumphant.mp3');
    const proc = spawnSync(
      'ffmpeg',
      ['-hide_banner', '-i', p, '-af', 'volumedetect', '-vn', '-f', 'null', '/dev/null'],
      { encoding: 'utf8' },
    );
    const stderr = proc.stderr;
    const meanMatch = stderr.match(/mean_volume:\s*(-?[\d.]+)\s*dB/);
    expect(meanMatch, `volumedetect output:\n${stderr}`).not.toBeNull();
    const meanDb = parseFloat(meanMatch![1]);
    // Silence is around -91dB; real audio is louder than -40dB.
    expect(meanDb, `mean_volume ${meanDb}dB suggests silent placeholder`).toBeGreaterThan(-40);
  });
});
