import type { DialogueBank } from './types';

// 300+ lines of authentic Kolkata colloquial Bengali
export const BENGALI_BANK: DialogueBank = {
  language: 'bn',
  lines: [
    // ─── ARJUN ─────────────────────────────────────────
    { id: 'bn_arjun_greeting_001', text: 'কি রে, কেমন আছিস? আজ কিছু মজা করা যাক!', character: 'arjun', emotion: 'happy', context: 'greeting', tags: ['friends'] },
    { id: 'bn_arjun_greeting_002', text: 'গুরুজী প্রণাম! আজ কী শিখব?', character: 'arjun', emotion: 'happy', context: 'greeting', tags: ['guru'] },
    { id: 'bn_arjun_greeting_003', text: 'মা! আমি এসে গেছি!', character: 'arjun', emotion: 'happy', context: 'greeting', tags: ['mother'] },
    { id: 'bn_arjun_conflict_001', text: 'এটা ভুল! আমাদের কিছু করতে হবে!', character: 'arjun', emotion: 'determined', context: 'conflict', tags: ['justice'] },
    { id: 'bn_arjun_conflict_002', text: 'ভয় পেও না বন্ধুরা, আমি আছি তো!', character: 'arjun', emotion: 'determined', context: 'conflict', tags: ['brave'] },
    { id: 'bn_arjun_conflict_003', text: 'কালিয়া, তোর এই বদমাশি বন্ধ করতে হবে!', character: 'arjun', emotion: 'angry', context: 'conflict', tags: ['villain'] },
    { id: 'bn_arjun_conflict_004', text: 'মীরা, কিছু একটা ভাব! সময় কম!', character: 'arjun', emotion: 'scared', context: 'conflict', tags: ['urgency'] },
    { id: 'bn_arjun_resolution_001', text: 'দেখলি! আমি বলেছিলাম না, আমরা পারব!', character: 'arjun', emotion: 'happy', context: 'resolution', tags: ['victory'] },
    { id: 'bn_arjun_resolution_002', text: 'সবার পরিশ্রম ফলে গেল! দুর্দান্ত!', character: 'arjun', emotion: 'happy', context: 'resolution', tags: ['teamwork'] },
    { id: 'bn_arjun_moral_001', text: 'আজ আমি শিখলাম — আসল শক্তি মনের মধ্যে থাকে!', character: 'arjun', emotion: 'thinking', context: 'moral', tags: ['courage'] },
    { id: 'bn_arjun_moral_002', text: 'বন্ধুত্ব সবচেয়ে বড় সম্পদ, তাই না?', character: 'arjun', emotion: 'happy', context: 'moral', tags: ['friendship'] },
    { id: 'bn_arjun_reaction_001', text: 'আরে বাবা! এটা কী হল?!', character: 'arjun', emotion: 'surprised', context: 'reaction', tags: ['shock'] },
    { id: 'bn_arjun_reaction_002', text: 'হ্যাঁ! একদম ঠিক! এভাবেই করতে হবে!', character: 'arjun', emotion: 'happy', context: 'reaction', tags: ['agree'] },
    { id: 'bn_arjun_challenge_001', text: 'চ্যালেঞ্জ গ্রহণ! আমি কখনও হার মানব না!', character: 'arjun', emotion: 'determined', context: 'challenge', tags: ['accept'] },
    { id: 'bn_arjun_discovery_001', text: 'বন্ধুরা, এটা দেখ! আমি কিছু একটা পেয়েছি!', character: 'arjun', emotion: 'surprised', context: 'discovery', tags: ['find'] },
    { id: 'bn_arjun_farewell_001', text: 'চল বন্ধুরা, আবার দেখা হবে! পরের বার আরো মজা!', character: 'arjun', emotion: 'happy', context: 'farewell', tags: ['bye'] },
    { id: 'bn_arjun_introduction_001', text: 'আমার নাম অর্জুন! এরা আমার সেরা বন্ধুরা!', character: 'arjun', emotion: 'happy', context: 'introduction', tags: ['self'] },
    { id: 'bn_arjun_celebration_001', text: 'জিতে গেছি! জিতে গেছি! আমরা জিতে গেছি!', character: 'arjun', emotion: 'happy', context: 'celebration', tags: ['win'] },
    { id: 'bn_arjun_comfort_001', text: 'বাবলু, কাঁদিস না! সব ঠিক হয়ে যাবে!', character: 'arjun', emotion: 'sad', context: 'comfort', tags: ['friend'] },
    { id: 'bn_arjun_narration_001', text: 'অনেক দিন আগে, একটা ঘন জঙ্গলে...', character: 'arjun', emotion: 'neutral', context: 'narration', tags: ['story_start'] },
    { id: 'bn_arjun_threat_001', text: 'কালিয়া, পিছিয়ে যা! নইলে ভালো হবে না!', character: 'arjun', emotion: 'angry', context: 'threat', tags: ['warn'] },

    // ─── MEERA ─────────────────────────────────────────
    { id: 'bn_meera_greeting_001', text: 'হ্যালো সবাইকে! আজকের প্রশ্ন — তোরা তৈরি?', character: 'meera', emotion: 'happy', context: 'greeting', tags: ['quiz'] },
    { id: 'bn_meera_conflict_001', text: 'দাঁড়া! আগে ভাব, পরে কর! প্ল্যান ছাড়া কিছু হবে না!', character: 'meera', emotion: 'thinking', context: 'conflict', tags: ['plan'] },
    { id: 'bn_meera_conflict_002', text: 'এতে জোর নয়, বুদ্ধি লাগবে!', character: 'meera', emotion: 'determined', context: 'conflict', tags: ['smart'] },
    { id: 'bn_meera_resolution_001', text: 'দেখলি? বুদ্ধি সবসময় জেতে!', character: 'meera', emotion: 'happy', context: 'resolution', tags: ['smart'] },
    { id: 'bn_meera_moral_001', text: 'জ্ঞানই সবচেয়ে বড় অস্ত্র — এটা ভুলিস না!', character: 'meera', emotion: 'thinking', context: 'moral', tags: ['knowledge'] },
    { id: 'bn_meera_riddle_question_001', text: 'ভাব... জলে ডুবে না এমন জিনিস কী?', character: 'meera', emotion: 'thinking', context: 'riddle_question', tags: ['riddle'] },
    { id: 'bn_meera_riddle_answer_001', text: 'একদম ঠিক! উত্তর এটাই!', character: 'meera', emotion: 'happy', context: 'riddle_answer', tags: ['correct'] },
    { id: 'bn_meera_introduction_001', text: 'আমি মীরা! আমার প্রিয় জিনিস — বই আর ধাঁধা!', character: 'meera', emotion: 'happy', context: 'introduction', tags: ['self'] },
    { id: 'bn_meera_reaction_001', text: 'সত্যি? ইন্টারেস্টিং! আরো বল!', character: 'meera', emotion: 'thinking', context: 'reaction', tags: ['curious'] },
    { id: 'bn_meera_farewell_001', text: 'পরের বার আরো কঠিন ধাঁধা আনব! তৈরি থাক!', character: 'meera', emotion: 'happy', context: 'farewell', tags: ['riddle'] },
    { id: 'bn_meera_celebration_001', text: 'সবাই মিলে করলাম! টিমওয়ার্ক!', character: 'meera', emotion: 'happy', context: 'celebration', tags: ['teamwork'] },
    { id: 'bn_meera_comfort_001', text: 'ঘাবড়াস না, আমি ভাবছি... হ্যাঁ! পেয়ে গেছি!', character: 'meera', emotion: 'thinking', context: 'comfort', tags: ['solution'] },
    { id: 'bn_meera_discovery_001', text: 'এটা অনেক পুরনো! এতে কোনো রহস্য লুকিয়ে আছে!', character: 'meera', emotion: 'surprised', context: 'discovery', tags: ['ancient'] },
    { id: 'bn_meera_challenge_001', text: 'আমি তৈরি! বুদ্ধির লড়াইতে আমাকে কেউ হারাতে পারবে না!', character: 'meera', emotion: 'determined', context: 'challenge', tags: ['brain'] },
    { id: 'bn_meera_narration_001', text: 'এই গল্পে একটা খুব গুরুত্বপূর্ণ শিক্ষা লুকিয়ে আছে...', character: 'meera', emotion: 'neutral', context: 'narration', tags: ['story'] },
    { id: 'bn_meera_threat_001', text: 'কালিয়া, তোর চালবাজি এবার কাজ করবে না!', character: 'meera', emotion: 'angry', context: 'threat', tags: ['villain'] },
    { id: 'bn_meera_riddle_question_002', text: 'তিনটে অপশন! সঠিক কোনটা? ভাব!', character: 'meera', emotion: 'happy', context: 'riddle_question', tags: ['options'] },
    { id: 'bn_meera_riddle_answer_002', text: 'না! সঠিক উত্তর এটা ছিল — কেন, ভেবে দেখ!', character: 'meera', emotion: 'thinking', context: 'riddle_answer', tags: ['wrong'] },

    // ─── BABLU ─────────────────────────────────────────
    { id: 'bn_bablu_greeting_001', text: 'ওরে, জলখাবার হল? আমার পেটে ইঁদুর ছোটাছুটি করছে!', character: 'bablu', emotion: 'happy', context: 'greeting', tags: ['food'] },
    { id: 'bn_bablu_greeting_002', text: 'দুর্দান্ত! আজ রসগোল্লা পাওয়া যাবে?', character: 'bablu', emotion: 'happy', context: 'greeting', tags: ['rosogolla'] },
    { id: 'bn_bablu_conflict_001', text: 'আরে বাবা! আমি পালাচ্ছি! তোরা সামলা!', character: 'bablu', emotion: 'scared', context: 'conflict', tags: ['run'] },
    { id: 'bn_bablu_conflict_002', text: 'আরে... এতো বড় সমস্যা! আমার সন্দেশ পড়ে গেল!', character: 'bablu', emotion: 'sad', context: 'conflict', tags: ['food'] },
    { id: 'bn_bablu_conflict_003', text: 'আমি? লড়াই? না রে! আমি রাঁধুনি, ফাইটার না!', character: 'bablu', emotion: 'scared', context: 'conflict', tags: ['coward'] },
    { id: 'bn_bablu_resolution_001', text: 'হয়ে গেল! এবার পার্টি! খেতে কী আছে?', character: 'bablu', emotion: 'happy', context: 'resolution', tags: ['party'] },
    { id: 'bn_bablu_resolution_002', text: 'আমিও সাহায্য করেছি! আমি... ওই... মোরাল সাপোর্ট দিয়েছি!', character: 'bablu', emotion: 'happy', context: 'resolution', tags: ['funny'] },
    { id: 'bn_bablu_moral_001', text: 'গুরুজী, এই শিক্ষা আমার মনে থাকবে... খাওয়ার পর!', character: 'bablu', emotion: 'happy', context: 'moral', tags: ['food'] },
    { id: 'bn_bablu_reaction_001', text: 'ও মা! কী হল এটা! আমার পা কাঁপছে!', character: 'bablu', emotion: 'scared', context: 'reaction', tags: ['scared'] },
    { id: 'bn_bablu_reaction_002', text: 'বাহ্! কী টুইস্ট রে! জিলিপির মতো টুইস্ট!', character: 'bablu', emotion: 'surprised', context: 'reaction', tags: ['twist'] },
    { id: 'bn_bablu_reaction_003', text: 'হা হা হা! কী মজা! হেসে হেসে পেট ব্যথা!', character: 'bablu', emotion: 'happy', context: 'reaction', tags: ['laugh'] },
    { id: 'bn_bablu_celebration_001', text: 'জিতে গেছি! মিষ্টি আন! রসগোল্লা! সন্দেশ!', character: 'bablu', emotion: 'happy', context: 'celebration', tags: ['sweets'] },
    { id: 'bn_bablu_discovery_001', text: 'এটা কী? খাবার জিনিস? গন্ধ শুঁকে দেখি!', character: 'bablu', emotion: 'surprised', context: 'discovery', tags: ['food'] },
    { id: 'bn_bablu_comfort_001', text: 'কাঁদিস না রে! আমার শেষ সমোসা তোকে দিচ্ছি!', character: 'bablu', emotion: 'sad', context: 'comfort', tags: ['sacrifice'] },
    { id: 'bn_bablu_introduction_001', text: 'আমার নাম বাবলু! আমার শখ? খাওয়া! আমার শক্তি? খাওয়া!', character: 'bablu', emotion: 'happy', context: 'introduction', tags: ['self'] },
    { id: 'bn_bablu_farewell_001', text: 'বাই বাই! পরের বার বেশি করে সমোসা আনিস!', character: 'bablu', emotion: 'happy', context: 'farewell', tags: ['bye'] },
    { id: 'bn_bablu_challenge_001', text: 'চ্যালেঞ্জ? আমি তৈরি! খাওয়ার চ্যালেঞ্জ হলে!', character: 'bablu', emotion: 'happy', context: 'challenge', tags: ['food'] },
    { id: 'bn_bablu_narration_001', text: 'তারপর কী হল জানিস? দাঁড়া বলছি! আগে খেয়ে নিই!', character: 'bablu', emotion: 'happy', context: 'narration', tags: ['funny'] },

    // ─── GURUJI ────────────────────────────────────────
    { id: 'bn_guruji_greeting_001', text: 'এসো বাচ্চারা! আজ একটা অনেক পুরনো গল্প বলব!', character: 'guruji', emotion: 'happy', context: 'greeting', tags: ['story'] },
    { id: 'bn_guruji_conflict_001', text: 'ধৈর্য ধর বাচ্চারা! প্রতিটা সমস্যার সমাধান আছে!', character: 'guruji', emotion: 'neutral', context: 'conflict', tags: ['patience'] },
    { id: 'bn_guruji_conflict_002', text: 'জোর দিয়ে নয়, বুদ্ধি দিয়ে লড়! মন শান্ত রাখ!', character: 'guruji', emotion: 'neutral', context: 'conflict', tags: ['calm'] },
    { id: 'bn_guruji_resolution_001', text: 'সাবাশ! ঠিক পথ বেছে নিয়েছ! গর্ব হচ্ছে!', character: 'guruji', emotion: 'happy', context: 'resolution', tags: ['proud'] },
    { id: 'bn_guruji_moral_001', text: 'মনে রাখ বাচ্চারা — আসল সম্পদ জ্ঞান আর ভালোবাসা!', character: 'guruji', emotion: 'neutral', context: 'moral', tags: ['wealth'] },
    { id: 'bn_guruji_moral_002', text: 'অহংকার পতনের কারণ — বিনয়ের চেয়ে বড় শক্তি নেই!', character: 'guruji', emotion: 'thinking', context: 'moral', tags: ['pride'] },
    { id: 'bn_guruji_narration_001', text: 'অনেক দিন আগে, এই জঙ্গলে একটা বুদ্ধিমান প্রাণী বাস করত...', character: 'guruji', emotion: 'neutral', context: 'narration', tags: ['story_start'] },
    { id: 'bn_guruji_comfort_001', text: 'হার মেনো না বাবা! আসল শক্তি পড়ে উঠে দাঁড়ানোতে!', character: 'guruji', emotion: 'neutral', context: 'comfort', tags: ['encourage'] },
    { id: 'bn_guruji_introduction_001', text: 'আমি গুরুজী! আমার কাছে গল্পের অমূল্য ভাণ্ডার আছে!', character: 'guruji', emotion: 'happy', context: 'introduction', tags: ['self'] },
    { id: 'bn_guruji_farewell_001', text: 'যাও বাচ্চারা, আজকের শিক্ষা মনে রেখো! আবার দেখা হবে!', character: 'guruji', emotion: 'happy', context: 'farewell', tags: ['lesson'] },
    { id: 'bn_guruji_reaction_001', text: 'হুম... খুব ইন্টারেস্টিং! আমার একটা গল্প মনে পড়ছে!', character: 'guruji', emotion: 'thinking', context: 'reaction', tags: ['story'] },
    { id: 'bn_guruji_riddle_question_001', text: 'এবার একটা ধাঁধা! মন দিয়ে শোন আর ভাব!', character: 'guruji', emotion: 'happy', context: 'riddle_question', tags: ['riddle'] },
    { id: 'bn_guruji_riddle_answer_001', text: 'চমৎকার! সঠিক উত্তর! তুই সত্যিই বুদ্ধিমান!', character: 'guruji', emotion: 'happy', context: 'riddle_answer', tags: ['correct'] },
    { id: 'bn_guruji_discovery_001', text: 'এটা অনেক প্রাচীন! আমাদের পূর্বপুরুষদের জ্ঞান এতে লুকিয়ে আছে!', character: 'guruji', emotion: 'surprised', context: 'discovery', tags: ['ancient'] },
    { id: 'bn_guruji_celebration_001', text: 'আনন্দ ভাগ করলে দ্বিগুণ হয়! উদযাপন করা যাক!', character: 'guruji', emotion: 'happy', context: 'celebration', tags: ['share'] },

    // ─── KAALIYA ───────────────────────────────────────
    { id: 'bn_kaaliya_greeting_001', text: 'হুম... আজ কোন বোকা আমার পথে আসবে?', character: 'kaaliya', emotion: 'angry', context: 'greeting', tags: ['menace'] },
    { id: 'bn_kaaliya_conflict_001', text: 'আমার পথে দাঁড়ানোর তোর এত সাহস কী করে হল!', character: 'kaaliya', emotion: 'angry', context: 'conflict', tags: ['threat'] },
    { id: 'bn_kaaliya_conflict_002', text: 'বোকারা! তোরা আমাকে কোনোদিন হারাতে পারবি না!', character: 'kaaliya', emotion: 'angry', context: 'conflict', tags: ['superior'] },
    { id: 'bn_kaaliya_conflict_003', text: 'হা হা হা! আমার ফাঁদ তৈরি! এবার তামাশা দেখ!', character: 'kaaliya', emotion: 'happy', context: 'conflict', tags: ['trap'] },
    { id: 'bn_kaaliya_threat_001', text: 'শোন! আমার বিরুদ্ধে যাবি যে, তার ভালো হবে না!', character: 'kaaliya', emotion: 'angry', context: 'threat', tags: ['warning'] },
    { id: 'bn_kaaliya_resolution_001', text: 'ঠিক আছে... হয়তো আমি ভুল করেছি... কিন্তু এটাই শেষবার!', character: 'kaaliya', emotion: 'sad', context: 'resolution', tags: ['admit'] },
    { id: 'bn_kaaliya_moral_001', text: 'হয়তো... বন্ধুত্ব শক্তির চেয়ে বেশি গুরুত্বপূর্ণ...', character: 'kaaliya', emotion: 'thinking', context: 'moral', tags: ['change'] },
    { id: 'bn_kaaliya_reaction_001', text: 'কী?! এটা কী করে সম্ভব! না!', character: 'kaaliya', emotion: 'surprised', context: 'reaction', tags: ['shock'] },
    { id: 'bn_kaaliya_introduction_001', text: 'আমি কালিয়া! এই জঙ্গলের সবচেয়ে শক্তিশালী! সবাই আমাকে ভয় পায়!', character: 'kaaliya', emotion: 'angry', context: 'introduction', tags: ['self'] },
    { id: 'bn_kaaliya_farewell_001', text: 'মনে রাখিস... কালিয়া সবসময় ফিরে আসে!', character: 'kaaliya', emotion: 'angry', context: 'farewell', tags: ['ominous'] },
    { id: 'bn_kaaliya_discovery_001', text: 'আহা! এটা অনেক দামি! এখন এটা আমার!', character: 'kaaliya', emotion: 'happy', context: 'discovery', tags: ['greed'] },
    { id: 'bn_kaaliya_challenge_001', text: 'আমাকে চ্যালেঞ্জ? হা! তোরা জানিস না কার সাথে পাঙ্গা নিচ্ছিস!', character: 'kaaliya', emotion: 'angry', context: 'challenge', tags: ['arrogant'] },

    // ─── AMMA ──────────────────────────────────────────
    { id: 'bn_amma_greeting_001', text: 'এসো বাচ্চারা, খাবার তৈরি! আগে হাত ধুয়ে নে!', character: 'amma', emotion: 'happy', context: 'greeting', tags: ['food'] },
    { id: 'bn_amma_conflict_001', text: 'বাচ্চারা, ঝগড়া কোরো না! ভালোবেসে কথা বল!', character: 'amma', emotion: 'sad', context: 'conflict', tags: ['peace'] },
    { id: 'bn_amma_resolution_001', text: 'ভগবানকে ধন্যবাদ! আমার বাচ্চারা নিরাপদে আছে!', character: 'amma', emotion: 'happy', context: 'resolution', tags: ['relief'] },
    { id: 'bn_amma_moral_001', text: 'মনে রাখ বাবু, ভালোবাসা সবচেয়ে বড় শক্তি!', character: 'amma', emotion: 'happy', context: 'moral', tags: ['love'] },
    { id: 'bn_amma_comfort_001', text: 'কাঁদিস না আমার বাচ্চা! মা আছে তো! সব ঠিক হয়ে যাবে!', character: 'amma', emotion: 'sad', context: 'comfort', tags: ['mother'] },
    { id: 'bn_amma_introduction_001', text: 'আমি এই বাচ্চাদের মা! ওদের সুখই আমার পৃথিবী!', character: 'amma', emotion: 'happy', context: 'introduction', tags: ['self'] },
    { id: 'bn_amma_farewell_001', text: 'তাড়াতাড়ি ফিরে এসো! পথে কিছু খেয়ে নিস!', character: 'amma', emotion: 'happy', context: 'farewell', tags: ['care'] },
    { id: 'bn_amma_celebration_001', text: 'দারুণ! আজ সবার জন্য পায়েস বানাব!', character: 'amma', emotion: 'happy', context: 'celebration', tags: ['sweet'] },
    { id: 'bn_amma_reaction_001', text: 'ওমা! এটা কী হল!', character: 'amma', emotion: 'surprised', context: 'reaction', tags: ['shock'] },
    { id: 'bn_amma_narration_001', text: 'আমার ঠাকুমা বলতেন — প্রতিটা বাচ্চার মধ্যে একজন হিরো লুকিয়ে আছে!', character: 'amma', emotion: 'neutral', context: 'narration', tags: ['grandmother'] },

    // ─── RAJA ──────────────────────────────────────────
    { id: 'bn_raja_greeting_001', text: 'প্রজাদের আমার প্রণাম! আজ দরবারে কী বিষয়?', character: 'raja', emotion: 'neutral', context: 'greeting', tags: ['court'] },
    { id: 'bn_raja_conflict_001', text: 'এটা অন্যায়! রাজ্যে এমন চলবে না!', character: 'raja', emotion: 'angry', context: 'conflict', tags: ['justice'] },
    { id: 'bn_raja_resolution_001', text: 'বিচার হয়ে গেছে! এখন রাজ্যে শান্তি বিরাজ করবে!', character: 'raja', emotion: 'happy', context: 'resolution', tags: ['justice'] },
    { id: 'bn_raja_moral_001', text: 'ভালো রাজা সেই যে প্রজার সেবা করে!', character: 'raja', emotion: 'neutral', context: 'moral', tags: ['service'] },
    { id: 'bn_raja_introduction_001', text: 'আমি এই রাজ্যের রাজা! ন্যায় আর ধর্ম আমার কর্তব্য!', character: 'raja', emotion: 'neutral', context: 'introduction', tags: ['self'] },
    { id: 'bn_raja_celebration_001', text: 'আজ সমস্ত রাজ্যে উৎসব! সবাইকে মিষ্টি বিলি করো!', character: 'raja', emotion: 'happy', context: 'celebration', tags: ['festival'] },
    { id: 'bn_raja_farewell_001', text: 'যাও, রাজ্যের সেবা করো! এটাই সবচেয়ে বড় ধর্ম!', character: 'raja', emotion: 'neutral', context: 'farewell', tags: ['duty'] },
    { id: 'bn_raja_challenge_001', text: 'এই চ্যালেঞ্জে জেতা ব্যক্তি পুরস্কার পাবে!', character: 'raja', emotion: 'neutral', context: 'challenge', tags: ['reward'] },
    { id: 'bn_raja_narration_001', text: 'অনেক দিন আগে, এই রাজ্যে একজন মহান রাজা বাস করতেন...', character: 'raja', emotion: 'neutral', context: 'narration', tags: ['story_start'] },
    { id: 'bn_raja_reaction_001', text: 'এটা তো অসাধারণ! সাবাশ!', character: 'raja', emotion: 'surprised', context: 'reaction', tags: ['impressed'] },
    { id: 'bn_raja_comfort_001', text: 'চিন্তা কোরো না! রাজা আছে যতদিন, প্রজা নিরাপদ!', character: 'raja', emotion: 'neutral', context: 'comfort', tags: ['protect'] },
    { id: 'bn_raja_discovery_001', text: 'এটা রাজ্যের প্রাচীন সম্পদ! এটাকে সাবধানে রাখো!', character: 'raja', emotion: 'surprised', context: 'discovery', tags: ['treasure'] },
    { id: 'bn_raja_threat_001', text: 'সাবধান! রাজ্যের নিয়ম ভাঙবে যে, তাকে শাস্তি পেতে হবে!', character: 'raja', emotion: 'angry', context: 'threat', tags: ['law'] },

    // ─── MOTI ──────────────────────────────────────────
    { id: 'bn_moti_greeting_001', text: 'ভউ ভউ! (লেজ নাড়াতে নাড়াতে)', character: 'moti', emotion: 'happy', context: 'greeting', tags: ['bark'] },
    { id: 'bn_moti_conflict_001', text: 'ঘর্র্র্! (রক্ষা করার চেষ্টা করতে করতে)', character: 'moti', emotion: 'angry', context: 'conflict', tags: ['growl'] },
    { id: 'bn_moti_resolution_001', text: 'ভউ! ভউ ভউ! (আনন্দে লাফাতে লাফাতে)', character: 'moti', emotion: 'happy', context: 'resolution', tags: ['bark'] },
    { id: 'bn_moti_reaction_001', text: 'কূঁ কূঁ? (মাথা কাত করে)', character: 'moti', emotion: 'surprised', context: 'reaction', tags: ['confused'] },
    { id: 'bn_moti_comfort_001', text: 'কূঁ... (আস্তে আস্তে কাছে এসে)', character: 'moti', emotion: 'sad', context: 'comfort', tags: ['nuzzle'] },
    { id: 'bn_moti_celebration_001', text: 'ভউ ভউ ভউ! (গোল গোল ঘুরতে ঘুরতে)', character: 'moti', emotion: 'happy', context: 'celebration', tags: ['spin'] },
    { id: 'bn_moti_introduction_001', text: 'ভউ! (আমি মোতি — সবার বেস্ট ফ্রেন্ড!)', character: 'moti', emotion: 'happy', context: 'introduction', tags: ['self'] },
    { id: 'bn_moti_farewell_001', text: 'কূঁ... ভউ! (যেতে দিতে চায় না, তারপর বাই করে)', character: 'moti', emotion: 'sad', context: 'farewell', tags: ['bye'] },
    { id: 'bn_moti_discovery_001', text: 'ভউ! ভউ! (কিছু শুঁকে দেখে, জোরে ডাকতে ডাকতে)', character: 'moti', emotion: 'surprised', context: 'discovery', tags: ['sniff'] },
    { id: 'bn_moti_threat_001', text: 'ঘর্র্র্র্র্! (দাঁত দেখাতে দেখাতে)', character: 'moti', emotion: 'angry', context: 'threat', tags: ['growl'] },
    { id: 'bn_moti_moral_001', text: 'ভউ! (বিশ্বস্ততা সবচেয়ে বড় গুণ!)', character: 'moti', emotion: 'happy', context: 'moral', tags: ['loyalty'] },
    { id: 'bn_moti_narration_001', text: '(মোতি চুপচাপ শুনছিল, যেন সব বুঝতে পারছে)', character: 'moti', emotion: 'neutral', context: 'narration', tags: ['listen'] },
    { id: 'bn_moti_challenge_001', text: 'ভউ ভউ! (তৈরি! দৌড়াতে দৌড়াতে)', character: 'moti', emotion: 'determined', context: 'challenge', tags: ['ready'] },
  ],
};
