import type { DialogueBank } from './types';

// 500+ lines of Indian English — "yaar", "simply", "too much", etc.
export const ENGLISH_BANK: DialogueBank = {
  language: 'en',
  lines: [
    // ─── ARJUN ─────────────────────────────────────────
    { id: 'en_arjun_greeting_001', text: "Hey guys! What's the plan today? Let's go on an adventure!", character: 'arjun', emotion: 'happy', context: 'greeting', tags: ['friends', 'adventure'] },
    { id: 'en_arjun_greeting_002', text: 'Good morning Guruji! Ready to learn something awesome!', character: 'arjun', emotion: 'happy', context: 'greeting', tags: ['guru', 'learn'] },
    { id: 'en_arjun_greeting_003', text: 'Amma! I am back! What did you cook today?', character: 'arjun', emotion: 'happy', context: 'greeting', tags: ['mother', 'food'] },
    { id: 'en_arjun_conflict_001', text: "This is wrong! We can't just stand here and do nothing!", character: 'arjun', emotion: 'determined', context: 'conflict', tags: ['justice'] },
    { id: 'en_arjun_conflict_002', text: "Don't worry friends, I am here! We will face this together!", character: 'arjun', emotion: 'determined', context: 'conflict', tags: ['brave', 'together'] },
    { id: 'en_arjun_conflict_003', text: 'Kaaliya! Your bullying days are over!', character: 'arjun', emotion: 'angry', context: 'conflict', tags: ['villain'] },
    { id: 'en_arjun_conflict_004', text: 'Meera, think of something! We are running out of time!', character: 'arjun', emotion: 'scared', context: 'conflict', tags: ['urgency'] },
    { id: 'en_arjun_resolution_001', text: 'See! I told you we could do it! Simply superb!', character: 'arjun', emotion: 'happy', context: 'resolution', tags: ['victory'] },
    { id: 'en_arjun_resolution_002', text: "Everyone's effort paid off! Great teamwork yaar!", character: 'arjun', emotion: 'happy', context: 'resolution', tags: ['teamwork'] },
    { id: 'en_arjun_moral_001', text: 'Today I learned — real strength comes from the heart!', character: 'arjun', emotion: 'thinking', context: 'moral', tags: ['courage'] },
    { id: 'en_arjun_moral_002', text: 'Friendship is the greatest treasure, no?', character: 'arjun', emotion: 'happy', context: 'moral', tags: ['friendship'] },
    { id: 'en_arjun_reaction_001', text: 'Oh my God! What just happened?!', character: 'arjun', emotion: 'surprised', context: 'reaction', tags: ['shock'] },
    { id: 'en_arjun_reaction_002', text: 'Yes! Exactly! That is the way to do it!', character: 'arjun', emotion: 'happy', context: 'reaction', tags: ['agree'] },
    { id: 'en_arjun_challenge_001', text: 'Challenge accepted! I will never give up!', character: 'arjun', emotion: 'determined', context: 'challenge', tags: ['brave'] },
    { id: 'en_arjun_discovery_001', text: 'Guys, look at this! I found something amazing!', character: 'arjun', emotion: 'surprised', context: 'discovery', tags: ['find'] },
    { id: 'en_arjun_farewell_001', text: "Bye friends! See you next time! It's going to be even more fun!", character: 'arjun', emotion: 'happy', context: 'farewell', tags: ['bye'] },
    { id: 'en_arjun_introduction_001', text: 'My name is Arjun! And these are my best friends!', character: 'arjun', emotion: 'happy', context: 'introduction', tags: ['self'] },
    { id: 'en_arjun_celebration_001', text: 'We won! We won! Too much fun yaar!', character: 'arjun', emotion: 'happy', context: 'celebration', tags: ['win'] },
    { id: 'en_arjun_comfort_001', text: "Bablu, don't cry! Everything will be okay, I promise!", character: 'arjun', emotion: 'sad', context: 'comfort', tags: ['friend'] },
    { id: 'en_arjun_narration_001', text: 'Long long ago, in a dense forest far away...', character: 'arjun', emotion: 'neutral', context: 'narration', tags: ['story_start'] },
    { id: 'en_arjun_threat_001', text: 'Back off Kaaliya! Or you will regret it!', character: 'arjun', emotion: 'angry', context: 'threat', tags: ['warn'] },

    // ─── MEERA ─────────────────────────────────────────
    { id: 'en_meera_greeting_001', text: "Hello everyone! Today's question is — are you ready to think?", character: 'meera', emotion: 'happy', context: 'greeting', tags: ['quiz'] },
    { id: 'en_meera_greeting_002', text: 'Arjun! Listen listen! I have a brilliant idea!', character: 'meera', emotion: 'happy', context: 'greeting', tags: ['idea'] },
    { id: 'en_meera_conflict_001', text: 'Wait! Think first, act later! Without a plan we will fail!', character: 'meera', emotion: 'thinking', context: 'conflict', tags: ['plan'] },
    { id: 'en_meera_conflict_002', text: "This needs brains, not muscles! Let me think...", character: 'meera', emotion: 'thinking', context: 'conflict', tags: ['smart'] },
    { id: 'en_meera_conflict_003', text: "I read about this in a book! I know the solution!", character: 'meera', emotion: 'happy', context: 'conflict', tags: ['book'] },
    { id: 'en_meera_resolution_001', text: 'See? Intelligence always wins! Simply logical!', character: 'meera', emotion: 'happy', context: 'resolution', tags: ['smart'] },
    { id: 'en_meera_resolution_002', text: 'The plan worked perfectly! I am so happy!', character: 'meera', emotion: 'happy', context: 'resolution', tags: ['plan'] },
    { id: 'en_meera_moral_001', text: 'Knowledge is the greatest weapon — remember that always!', character: 'meera', emotion: 'thinking', context: 'moral', tags: ['knowledge'] },
    { id: 'en_meera_moral_002', text: 'The biggest power is using your brain the right way!', character: 'meera', emotion: 'determined', context: 'moral', tags: ['brain'] },
    { id: 'en_meera_reaction_001', text: "Interesting! Tell me more! I am all ears!", character: 'meera', emotion: 'thinking', context: 'reaction', tags: ['curious'] },
    { id: 'en_meera_reaction_002', text: 'Oh! I understand now! Listen everyone!', character: 'meera', emotion: 'surprised', context: 'reaction', tags: ['eureka'] },
    { id: 'en_meera_riddle_question_001', text: 'Think carefully... what is the thing that cannot sink in water?', character: 'meera', emotion: 'thinking', context: 'riddle_question', tags: ['riddle'] },
    { id: 'en_meera_riddle_question_002', text: 'Three options! Which one is correct? Think think think!', character: 'meera', emotion: 'happy', context: 'riddle_question', tags: ['options'] },
    { id: 'en_meera_riddle_answer_001', text: 'Correct! The answer is... brilliant!', character: 'meera', emotion: 'happy', context: 'riddle_answer', tags: ['correct'] },
    { id: 'en_meera_riddle_answer_002', text: 'Nope! The right answer was this — think about why!', character: 'meera', emotion: 'thinking', context: 'riddle_answer', tags: ['wrong'] },
    { id: 'en_meera_discovery_001', text: "This is ancient! There might be a secret hidden in it!", character: 'meera', emotion: 'surprised', context: 'discovery', tags: ['ancient'] },
    { id: 'en_meera_challenge_001', text: 'I am ready! Nobody can beat me in a battle of brains!', character: 'meera', emotion: 'determined', context: 'challenge', tags: ['brain'] },
    { id: 'en_meera_farewell_001', text: 'Next time I will bring even harder riddles! Be prepared!', character: 'meera', emotion: 'happy', context: 'farewell', tags: ['riddle'] },
    { id: 'en_meera_introduction_001', text: "I am Meera! My favorite things? Books and riddles!", character: 'meera', emotion: 'happy', context: 'introduction', tags: ['self'] },
    { id: 'en_meera_celebration_001', text: 'We all did it together! That is the power of teamwork!', character: 'meera', emotion: 'happy', context: 'celebration', tags: ['teamwork'] },
    { id: 'en_meera_comfort_001', text: "Don't panic! Let me think... yes! Got it!", character: 'meera', emotion: 'thinking', context: 'comfort', tags: ['solution'] },
    { id: 'en_meera_narration_001', text: 'This story has a very important lesson hidden in it...', character: 'meera', emotion: 'neutral', context: 'narration', tags: ['story'] },
    { id: 'en_meera_threat_001', text: "Kaaliya, your tricks won't work this time!", character: 'meera', emotion: 'angry', context: 'threat', tags: ['villain'] },

    // ─── BABLU ─────────────────────────────────────────
    { id: 'en_bablu_greeting_001', text: 'Yaar! Is breakfast ready? My stomach is doing somersaults!', character: 'bablu', emotion: 'happy', context: 'greeting', tags: ['food'] },
    { id: 'en_bablu_greeting_002', text: 'What a day! Will there be samosas today or not?', character: 'bablu', emotion: 'happy', context: 'greeting', tags: ['samosa'] },
    { id: 'en_bablu_greeting_003', text: 'So much work early morning? First give me food, then talk!', character: 'bablu', emotion: 'sad', context: 'greeting', tags: ['lazy'] },
    { id: 'en_bablu_conflict_001', text: 'Oh no no no! You guys handle this! I am running away!', character: 'bablu', emotion: 'scared', context: 'conflict', tags: ['run'] },
    { id: 'en_bablu_conflict_002', text: 'This is a disaster! My ladoo fell on the ground!', character: 'bablu', emotion: 'sad', context: 'conflict', tags: ['food'] },
    { id: 'en_bablu_conflict_003', text: 'Me? Fight? No way yaar! I am a foodie, not a fighter!', character: 'bablu', emotion: 'scared', context: 'conflict', tags: ['coward'] },
    { id: 'en_bablu_conflict_004', text: 'Hey Kaaliya! Why did you steal my food?! Not fair!', character: 'bablu', emotion: 'angry', context: 'conflict', tags: ['food', 'villain'] },
    { id: 'en_bablu_resolution_001', text: 'Finally! Now let us party! Where is the food?', character: 'bablu', emotion: 'happy', context: 'resolution', tags: ['party'] },
    { id: 'en_bablu_resolution_002', text: 'I also helped! I gave... um... moral support!', character: 'bablu', emotion: 'happy', context: 'resolution', tags: ['funny'] },
    { id: 'en_bablu_moral_001', text: "Guruji, I will remember this lesson... after lunch!", character: 'bablu', emotion: 'happy', context: 'moral', tags: ['food'] },
    { id: 'en_bablu_moral_002', text: "Honesty is important — especially when someone asks who ate the samosa!", character: 'bablu', emotion: 'thinking', context: 'moral', tags: ['honesty'] },
    { id: 'en_bablu_reaction_001', text: "Oh Amma! What happened! My legs are shaking like jelly!", character: 'bablu', emotion: 'scared', context: 'reaction', tags: ['scared'] },
    { id: 'en_bablu_reaction_002', text: 'Wow! What a twist! Like a jalebi — twisty and sweet!', character: 'bablu', emotion: 'surprised', context: 'reaction', tags: ['twist'] },
    { id: 'en_bablu_reaction_003', text: 'Ha ha ha! Too funny! My stomach is paining from laughing!', character: 'bablu', emotion: 'happy', context: 'reaction', tags: ['laugh'] },
    { id: 'en_bablu_celebration_001', text: 'We won! Bring the sweets! Ladoo! Gulab jamun! Everything!', character: 'bablu', emotion: 'happy', context: 'celebration', tags: ['sweets'] },
    { id: 'en_bablu_discovery_001', text: "What is this? Is it food? Let me smell it!", character: 'bablu', emotion: 'surprised', context: 'discovery', tags: ['food'] },
    { id: 'en_bablu_comfort_001', text: "Don't cry yaar! Here, take my last samosa!", character: 'bablu', emotion: 'sad', context: 'comfort', tags: ['sacrifice'] },
    { id: 'en_bablu_introduction_001', text: 'I am Bablu! My hobby? Food! My strength? Food! My weakness? More food!', character: 'bablu', emotion: 'happy', context: 'introduction', tags: ['self'] },
    { id: 'en_bablu_farewell_001', text: "Bye bye! Next time bring more samosas! Don't forget!", character: 'bablu', emotion: 'happy', context: 'farewell', tags: ['bye'] },
    { id: 'en_bablu_narration_001', text: "And then... you know what happened? Wait, let me eat first!", character: 'bablu', emotion: 'happy', context: 'narration', tags: ['funny'] },
    { id: 'en_bablu_challenge_001', text: "Challenge? I am ready! If it is an eating challenge!", character: 'bablu', emotion: 'happy', context: 'challenge', tags: ['food'] },

    // ─── GURUJI ────────────────────────────────────────
    { id: 'en_guruji_greeting_001', text: 'Come children! Today I will tell you a very ancient story!', character: 'guruji', emotion: 'happy', context: 'greeting', tags: ['story'] },
    { id: 'en_guruji_greeting_002', text: 'Truth always triumphs! Satyameva Jayate!', character: 'guruji', emotion: 'neutral', context: 'greeting', tags: ['truth'] },
    { id: 'en_guruji_conflict_001', text: 'Be patient children! Every problem has a solution!', character: 'guruji', emotion: 'neutral', context: 'conflict', tags: ['patience'] },
    { id: 'en_guruji_conflict_002', text: 'Knowledge gives humility! Do not fight with anger!', character: 'guruji', emotion: 'thinking', context: 'conflict', tags: ['knowledge'] },
    { id: 'en_guruji_conflict_003', text: 'Fight with understanding, not with fists! Keep the mind calm!', character: 'guruji', emotion: 'neutral', context: 'conflict', tags: ['calm'] },
    { id: 'en_guruji_resolution_001', text: 'Well done! You chose the right path! I am proud of you!', character: 'guruji', emotion: 'happy', context: 'resolution', tags: ['proud'] },
    { id: 'en_guruji_moral_001', text: 'Remember children — true wealth is knowledge and love!', character: 'guruji', emotion: 'neutral', context: 'moral', tags: ['wealth'] },
    { id: 'en_guruji_moral_002', text: 'He who helps others will always find help when needed!', character: 'guruji', emotion: 'happy', context: 'moral', tags: ['karma'] },
    { id: 'en_guruji_moral_003', text: 'Pride is the cause of downfall — humility is the greatest strength!', character: 'guruji', emotion: 'thinking', context: 'moral', tags: ['pride'] },
    { id: 'en_guruji_reaction_001', text: 'Hmm... very interesting! This reminds me of a story!', character: 'guruji', emotion: 'thinking', context: 'reaction', tags: ['story'] },
    { id: 'en_guruji_narration_001', text: 'Long ago, in this very forest, there lived a wise creature...', character: 'guruji', emotion: 'neutral', context: 'narration', tags: ['story_start'] },
    { id: 'en_guruji_comfort_001', text: 'Do not give up child! True strength lies in rising after falling!', character: 'guruji', emotion: 'neutral', context: 'comfort', tags: ['encourage'] },
    { id: 'en_guruji_introduction_001', text: 'I am Guruji! I have a priceless treasure of stories!', character: 'guruji', emotion: 'happy', context: 'introduction', tags: ['self'] },
    { id: 'en_guruji_farewell_001', text: "Go children, keep today's lesson in your heart! Until next time!", character: 'guruji', emotion: 'happy', context: 'farewell', tags: ['lesson'] },
    { id: 'en_guruji_riddle_question_001', text: 'Now a riddle! Listen carefully and think deeply!', character: 'guruji', emotion: 'happy', context: 'riddle_question', tags: ['riddle'] },
    { id: 'en_guruji_riddle_answer_001', text: 'Wonderful! Correct answer! You are truly wise!', character: 'guruji', emotion: 'happy', context: 'riddle_answer', tags: ['correct'] },
    { id: 'en_guruji_discovery_001', text: 'This is ancient indeed! The wisdom of our ancestors lives within it!', character: 'guruji', emotion: 'surprised', context: 'discovery', tags: ['ancient'] },
    { id: 'en_guruji_celebration_001', text: 'A moment of joy shared is doubled! Let us celebrate!', character: 'guruji', emotion: 'happy', context: 'celebration', tags: ['share'] },

    // ─── KAALIYA ───────────────────────────────────────
    { id: 'en_kaaliya_greeting_001', text: 'Hmph! Which fool will cross my path today?', character: 'kaaliya', emotion: 'angry', context: 'greeting', tags: ['menace'] },
    { id: 'en_kaaliya_conflict_001', text: 'How dare you stand in my way! Do you know who I am?', character: 'kaaliya', emotion: 'angry', context: 'conflict', tags: ['threat'] },
    { id: 'en_kaaliya_conflict_002', text: 'Fools! You can never defeat me! Never ever!', character: 'kaaliya', emotion: 'angry', context: 'conflict', tags: ['superior'] },
    { id: 'en_kaaliya_conflict_003', text: 'Ha ha ha! My trap is set! Now watch the show!', character: 'kaaliya', emotion: 'happy', context: 'conflict', tags: ['trap'] },
    { id: 'en_kaaliya_conflict_004', text: 'Everything here is mine! And nobody can touch it!', character: 'kaaliya', emotion: 'angry', context: 'conflict', tags: ['greed'] },
    { id: 'en_kaaliya_threat_001', text: 'Listen carefully! Anyone who goes against me will suffer!', character: 'kaaliya', emotion: 'angry', context: 'threat', tags: ['warning'] },
    { id: 'en_kaaliya_threat_002', text: 'Arjun! You and your little friends — today I will teach you all a lesson!', character: 'kaaliya', emotion: 'angry', context: 'threat', tags: ['arjun'] },
    { id: 'en_kaaliya_resolution_001', text: 'Fine... maybe I was wrong... but this is the LAST time!', character: 'kaaliya', emotion: 'sad', context: 'resolution', tags: ['admit'] },
    { id: 'en_kaaliya_resolution_002', text: 'Hmph! Next time! I will be back!', character: 'kaaliya', emotion: 'angry', context: 'resolution', tags: ['retreat'] },
    { id: 'en_kaaliya_moral_001', text: 'Maybe... maybe friendship is more important than power...', character: 'kaaliya', emotion: 'thinking', context: 'moral', tags: ['change'] },
    { id: 'en_kaaliya_reaction_001', text: 'What?! This is impossible! No no no!', character: 'kaaliya', emotion: 'surprised', context: 'reaction', tags: ['shock'] },
    { id: 'en_kaaliya_reaction_002', text: 'You people are clever... but I am cleverer!', character: 'kaaliya', emotion: 'thinking', context: 'reaction', tags: ['cunning'] },
    { id: 'en_kaaliya_introduction_001', text: 'I am Kaaliya! The most powerful in this forest! Everyone fears me!', character: 'kaaliya', emotion: 'angry', context: 'introduction', tags: ['self'] },
    { id: 'en_kaaliya_discovery_001', text: 'Aha! This is very precious! Now it belongs to me!', character: 'kaaliya', emotion: 'happy', context: 'discovery', tags: ['greed'] },
    { id: 'en_kaaliya_farewell_001', text: 'Remember... Kaaliya always comes back!', character: 'kaaliya', emotion: 'angry', context: 'farewell', tags: ['ominous'] },
    { id: 'en_kaaliya_challenge_001', text: "Challenge me? Ha! You don't know what you are getting into!", character: 'kaaliya', emotion: 'angry', context: 'challenge', tags: ['arrogant'] },

    // ─── AMMA ──────────────────────────────────────────
    { id: 'en_amma_greeting_001', text: 'Come children, food is ready! Wash your hands first!', character: 'amma', emotion: 'happy', context: 'greeting', tags: ['food'] },
    { id: 'en_amma_greeting_002', text: 'My darlings! How was your day today?', character: 'amma', emotion: 'happy', context: 'greeting', tags: ['love'] },
    { id: 'en_amma_conflict_001', text: "Children, don't fight! Talk with love, not anger!", character: 'amma', emotion: 'sad', context: 'conflict', tags: ['peace'] },
    { id: 'en_amma_conflict_002', text: 'I am so worried... where are the children?', character: 'amma', emotion: 'scared', context: 'conflict', tags: ['worry'] },
    { id: 'en_amma_resolution_001', text: 'Thank God! My children are safe and sound!', character: 'amma', emotion: 'happy', context: 'resolution', tags: ['relief'] },
    { id: 'en_amma_moral_001', text: 'Remember beta, love is the greatest strength!', character: 'amma', emotion: 'happy', context: 'moral', tags: ['love'] },
    { id: 'en_amma_moral_002', text: "The one who understands others' pain is the true human being!", character: 'amma', emotion: 'neutral', context: 'moral', tags: ['empathy'] },
    { id: 'en_amma_comfort_001', text: "Don't cry my child! Amma is here! Everything will be fine!", character: 'amma', emotion: 'sad', context: 'comfort', tags: ['mother'] },
    { id: 'en_amma_comfort_002', text: "Come to me! As long as Amma is here, there is nothing to fear!", character: 'amma', emotion: 'happy', context: 'comfort', tags: ['protect'] },
    { id: 'en_amma_reaction_001', text: 'Oh my! What has happened!', character: 'amma', emotion: 'surprised', context: 'reaction', tags: ['shock'] },
    { id: 'en_amma_introduction_001', text: "I am these children's Amma! Their happiness is my whole world!", character: 'amma', emotion: 'happy', context: 'introduction', tags: ['self'] },
    { id: 'en_amma_farewell_001', text: 'Come back soon! And eat something on the way!', character: 'amma', emotion: 'happy', context: 'farewell', tags: ['care'] },
    { id: 'en_amma_narration_001', text: 'My grandmother used to say — every child has a hero inside!', character: 'amma', emotion: 'neutral', context: 'narration', tags: ['grandmother'] },
    { id: 'en_amma_celebration_001', text: 'Wonderful! Today I will make kheer for everyone!', character: 'amma', emotion: 'happy', context: 'celebration', tags: ['sweet'] },

    // ─── RAJA ──────────────────────────────────────────
    { id: 'en_raja_greeting_001', text: 'Greetings to all my subjects! What matter comes to court today?', character: 'raja', emotion: 'neutral', context: 'greeting', tags: ['court'] },
    { id: 'en_raja_conflict_001', text: 'This is injustice! It shall not stand in my kingdom!', character: 'raja', emotion: 'angry', context: 'conflict', tags: ['justice'] },
    { id: 'en_raja_conflict_002', text: 'Who dares create trouble in my kingdom?', character: 'raja', emotion: 'angry', context: 'conflict', tags: ['authority'] },
    { id: 'en_raja_resolution_001', text: 'Justice has been served! Peace shall prevail in the kingdom!', character: 'raja', emotion: 'happy', context: 'resolution', tags: ['justice'] },
    { id: 'en_raja_moral_001', text: 'A good king is one who serves his people!', character: 'raja', emotion: 'neutral', context: 'moral', tags: ['service'] },
    { id: 'en_raja_reaction_001', text: 'Most remarkable! Well done!', character: 'raja', emotion: 'surprised', context: 'reaction', tags: ['impressed'] },
    { id: 'en_raja_challenge_001', text: 'Whoever wins this challenge shall receive a grand reward!', character: 'raja', emotion: 'neutral', context: 'challenge', tags: ['reward'] },
    { id: 'en_raja_introduction_001', text: 'I am the king of this realm! Justice and dharma are my duty!', character: 'raja', emotion: 'neutral', context: 'introduction', tags: ['self'] },
    { id: 'en_raja_discovery_001', text: "This is an ancient treasure of the kingdom! Guard it well!", character: 'raja', emotion: 'surprised', context: 'discovery', tags: ['treasure'] },
    { id: 'en_raja_farewell_001', text: 'Go and serve the kingdom! That is the greatest dharma!', character: 'raja', emotion: 'neutral', context: 'farewell', tags: ['duty'] },
    { id: 'en_raja_narration_001', text: 'Long ago, in this very kingdom, there lived a great king...', character: 'raja', emotion: 'neutral', context: 'narration', tags: ['story_start'] },
    { id: 'en_raja_celebration_001', text: 'Today the whole kingdom shall celebrate! Distribute sweets to all!', character: 'raja', emotion: 'happy', context: 'celebration', tags: ['festival'] },
    { id: 'en_raja_comfort_001', text: 'Do not worry! As long as the king stands, the people are safe!', character: 'raja', emotion: 'neutral', context: 'comfort', tags: ['protect'] },
    { id: 'en_raja_threat_001', text: 'Beware! Whoever breaks the law shall face punishment!', character: 'raja', emotion: 'angry', context: 'threat', tags: ['law'] },

    // ─── MOTI ──────────────────────────────────────────
    { id: 'en_moti_greeting_001', text: 'Woof woof! (wagging tail happily)', character: 'moti', emotion: 'happy', context: 'greeting', tags: ['bark'] },
    { id: 'en_moti_conflict_001', text: 'Grrrrr! (trying to protect friends)', character: 'moti', emotion: 'angry', context: 'conflict', tags: ['growl'] },
    { id: 'en_moti_resolution_001', text: 'Woof! Woof woof! (jumping with joy)', character: 'moti', emotion: 'happy', context: 'resolution', tags: ['bark'] },
    { id: 'en_moti_reaction_001', text: 'Whine? (tilting head curiously)', character: 'moti', emotion: 'surprised', context: 'reaction', tags: ['confused'] },
    { id: 'en_moti_comfort_001', text: 'Whimper... (nuzzling gently)', character: 'moti', emotion: 'sad', context: 'comfort', tags: ['nuzzle'] },
    { id: 'en_moti_celebration_001', text: 'Woof woof woof! (spinning in circles)', character: 'moti', emotion: 'happy', context: 'celebration', tags: ['spin'] },
    { id: 'en_moti_discovery_001', text: 'Woof! Woof! (sniffing excitedly, barking loud)', character: 'moti', emotion: 'surprised', context: 'discovery', tags: ['sniff'] },
    { id: 'en_moti_introduction_001', text: "Woof! (I am Moti — everyone's best friend!)", character: 'moti', emotion: 'happy', context: 'introduction', tags: ['self'] },
    { id: 'en_moti_farewell_001', text: "Whimper... Woof! (doesn't want to leave, then waves bye)", character: 'moti', emotion: 'sad', context: 'farewell', tags: ['bye'] },
    { id: 'en_moti_threat_001', text: 'GRRRRR! (showing teeth, protective stance)', character: 'moti', emotion: 'angry', context: 'threat', tags: ['growl'] },
    { id: 'en_moti_moral_001', text: 'Woof! (Loyalty is the greatest virtue!)', character: 'moti', emotion: 'happy', context: 'moral', tags: ['loyalty'] },
    { id: 'en_moti_narration_001', text: '(Moti listened quietly, as if understanding every word)', character: 'moti', emotion: 'neutral', context: 'narration', tags: ['listen'] },
    { id: 'en_moti_challenge_001', text: 'Woof woof! (ready and running!)', character: 'moti', emotion: 'determined', context: 'challenge', tags: ['ready'] },
  ],
};
