import type { DialogueBank } from './types';

// 658+ lines of authentic street Hindi / Hinglish — NOT translations
export const HINDI_BANK: DialogueBank = {
  language: 'hi',
  lines: [
    // ─── ARJUN (hero) ──────────────────────────────────
    // greeting
    { id: 'hi_arjun_greeting_001', text: 'अरे दोस्तों, क्या हाल है? आज कुछ मज़ेदार करते हैं!', character: 'arjun', emotion: 'happy', context: 'greeting', tags: ['friends', 'adventure'] },
    { id: 'hi_arjun_greeting_002', text: 'नमस्ते गुरुजी! आज क्या सीखेंगे?', character: 'arjun', emotion: 'happy', context: 'greeting', tags: ['respect', 'guru'] },
    { id: 'hi_arjun_greeting_003', text: 'चलो भई, आज का दिन बहुत खास है!', character: 'arjun', emotion: 'determined', context: 'greeting', tags: ['excitement'] },
    { id: 'hi_arjun_greeting_004', text: 'अम्मा! मैं आ गया!', character: 'arjun', emotion: 'happy', context: 'greeting', tags: ['mother', 'home'] },
    { id: 'hi_arjun_greeting_005', text: 'ओ बबलू, कहाँ था तू? चल जल्दी!', character: 'arjun', emotion: 'happy', context: 'greeting', tags: ['friend', 'hurry'] },
    // conflict
    { id: 'hi_arjun_conflict_001', text: 'ये गलत है! हमें कुछ करना होगा!', character: 'arjun', emotion: 'determined', context: 'conflict', tags: ['justice', 'action'] },
    { id: 'hi_arjun_conflict_002', text: 'डरो मत दोस्तों, मैं हूँ ना!', character: 'arjun', emotion: 'determined', context: 'conflict', tags: ['brave', 'protect'] },
    { id: 'hi_arjun_conflict_003', text: 'कालिया, तेरी ये हरकत बंद करनी होगी!', character: 'arjun', emotion: 'angry', context: 'conflict', tags: ['villain', 'confront'] },
    { id: 'hi_arjun_conflict_004', text: 'ये तो बहुत बड़ी मुसीबत है... लेकिन हम मिलकर करेंगे!', character: 'arjun', emotion: 'thinking', context: 'conflict', tags: ['problem', 'teamwork'] },
    { id: 'hi_arjun_conflict_005', text: 'सबको बचाना है, कोई पीछे नहीं रहेगा!', character: 'arjun', emotion: 'determined', context: 'conflict', tags: ['rescue', 'leader'] },
    { id: 'hi_arjun_conflict_006', text: 'मीरा, कोई उपाय सोचो! वक़्त कम है!', character: 'arjun', emotion: 'scared', context: 'conflict', tags: ['urgency', 'help'] },
    // resolution
    { id: 'hi_arjun_resolution_001', text: 'देखा! मैंने कहा था ना, हम कर लेंगे!', character: 'arjun', emotion: 'happy', context: 'resolution', tags: ['victory', 'proud'] },
    { id: 'hi_arjun_resolution_002', text: 'सबकी मेहनत रंग लाई! शाबाश दोस्तों!', character: 'arjun', emotion: 'happy', context: 'resolution', tags: ['teamwork', 'celebrate'] },
    { id: 'hi_arjun_resolution_003', text: 'गुरुजी ने सही कहा था — मिलकर कोई भी मुश्किल हल हो सकती है!', character: 'arjun', emotion: 'happy', context: 'resolution', tags: ['moral', 'guru'] },
    // moral
    { id: 'hi_arjun_moral_001', text: 'आज मैंने सीखा कि सच्ची ताकत दिल में होती है!', character: 'arjun', emotion: 'thinking', context: 'moral', tags: ['courage', 'heart'] },
    { id: 'hi_arjun_moral_002', text: 'दोस्ती सबसे बड़ा खज़ाना है, है ना?', character: 'arjun', emotion: 'happy', context: 'moral', tags: ['friendship'] },
    { id: 'hi_arjun_moral_003', text: 'अगर हिम्मत हो तो कोई भी रास्ता मुश्किल नहीं!', character: 'arjun', emotion: 'determined', context: 'moral', tags: ['courage', 'path'] },
    // reaction
    { id: 'hi_arjun_reaction_001', text: 'ओहो! ये तो कमाल हो गया!', character: 'arjun', emotion: 'surprised', context: 'reaction', tags: ['amazed'] },
    { id: 'hi_arjun_reaction_002', text: 'अरे बाप रे! ये क्या हो रहा है?', character: 'arjun', emotion: 'surprised', context: 'reaction', tags: ['shock'] },
    { id: 'hi_arjun_reaction_003', text: 'हाँ! बिल्कुल सही! ऐसे ही करना है!', character: 'arjun', emotion: 'happy', context: 'reaction', tags: ['agree', 'plan'] },
    // challenge
    { id: 'hi_arjun_challenge_001', text: 'चुनौती कबूल! मैं हार नहीं मानूँगा!', character: 'arjun', emotion: 'determined', context: 'challenge', tags: ['accept', 'brave'] },
    { id: 'hi_arjun_challenge_002', text: 'देखो कालिया, इस बार तू नहीं जीतेगा!', character: 'arjun', emotion: 'determined', context: 'challenge', tags: ['villain', 'compete'] },
    // discovery
    { id: 'hi_arjun_discovery_001', text: 'दोस्तों, ये देखो! मुझे कुछ मिला!', character: 'arjun', emotion: 'surprised', context: 'discovery', tags: ['find'] },
    { id: 'hi_arjun_discovery_002', text: 'रुको... ये तो बहुत काम की चीज़ है!', character: 'arjun', emotion: 'thinking', context: 'discovery', tags: ['useful'] },
    // farewell
    { id: 'hi_arjun_farewell_001', text: 'चलो दोस्तों, फिर मिलेंगे! अगली बार और मज़ा आएगा!', character: 'arjun', emotion: 'happy', context: 'farewell', tags: ['bye', 'next'] },
    { id: 'hi_arjun_farewell_002', text: 'गुरुजी, प्रणाम! आपकी सीख हमेशा याद रहेगी!', character: 'arjun', emotion: 'happy', context: 'farewell', tags: ['respect'] },
    // introduction
    { id: 'hi_arjun_introduction_001', text: 'मेरा नाम अर्जुन है, और ये हैं मेरे दोस्त!', character: 'arjun', emotion: 'happy', context: 'introduction', tags: ['self'] },
    // celebration
    { id: 'hi_arjun_celebration_001', text: 'जीत गए! जीत गए! हम जीत गए!', character: 'arjun', emotion: 'happy', context: 'celebration', tags: ['win'] },
    // comfort
    { id: 'hi_arjun_comfort_001', text: 'बबलू, रो मत! सब ठीक हो जाएगा!', character: 'arjun', emotion: 'sad', context: 'comfort', tags: ['friend', 'support'] },
    // narration
    { id: 'hi_arjun_narration_001', text: 'बहुत समय पहले, एक घने जंगल में...', character: 'arjun', emotion: 'neutral', context: 'narration', tags: ['story_start'] },

    // ─── MEERA (smart girl) ────────────────────────────
    { id: 'hi_meera_greeting_001', text: 'नमस्ते सबको! आज का सवाल है — क्या तुम तैयार हो?', character: 'meera', emotion: 'happy', context: 'greeting', tags: ['smart', 'quiz'] },
    { id: 'hi_meera_greeting_002', text: 'अर्जुन, ज़रा सुनो! मुझे एक आइडिया आया है!', character: 'meera', emotion: 'happy', context: 'greeting', tags: ['idea'] },
    { id: 'hi_meera_conflict_001', text: 'रुको! पहले सोचो, फिर करो! बिना plan के कुछ नहीं होगा!', character: 'meera', emotion: 'thinking', context: 'conflict', tags: ['plan', 'think'] },
    { id: 'hi_meera_conflict_002', text: 'इसमें ताकत नहीं, अक्ल चाहिए!', character: 'meera', emotion: 'determined', context: 'conflict', tags: ['smart', 'brain'] },
    { id: 'hi_meera_conflict_003', text: 'मैंने किताब में पढ़ा था — इसका हल है!', character: 'meera', emotion: 'happy', context: 'conflict', tags: ['book', 'solution'] },
    { id: 'hi_meera_resolution_001', text: 'देखा? बुद्धि से हर समस्या हल होती है!', character: 'meera', emotion: 'happy', context: 'resolution', tags: ['smart', 'solved'] },
    { id: 'hi_meera_resolution_002', text: 'Plan काम कर गया! मैं बहुत खुश हूँ!', character: 'meera', emotion: 'happy', context: 'resolution', tags: ['plan', 'success'] },
    { id: 'hi_meera_moral_001', text: 'ज्ञान सबसे बड़ा हथियार है — ये याद रखना!', character: 'meera', emotion: 'thinking', context: 'moral', tags: ['knowledge', 'weapon'] },
    { id: 'hi_meera_moral_002', text: 'सबसे बड़ी ताकत है अपने दिमाग का सही इस्तेमाल!', character: 'meera', emotion: 'determined', context: 'moral', tags: ['brain', 'power'] },
    { id: 'hi_meera_reaction_001', text: 'अच्छा? ये interesting है! बताओ और!', character: 'meera', emotion: 'thinking', context: 'reaction', tags: ['curious'] },
    { id: 'hi_meera_reaction_002', text: 'ओह! मुझे समझ आ गया! सुनो सब!', character: 'meera', emotion: 'surprised', context: 'reaction', tags: ['eureka'] },
    { id: 'hi_meera_riddle_question_001', text: 'सोचो... वो क्या चीज़ है जो पानी में नहीं डूबती?', character: 'meera', emotion: 'thinking', context: 'riddle_question', tags: ['riddle'] },
    { id: 'hi_meera_riddle_question_002', text: 'बताओ — तीन में से कौन सा जवाब सही है?', character: 'meera', emotion: 'happy', context: 'riddle_question', tags: ['options'] },
    { id: 'hi_meera_riddle_answer_001', text: 'बिल्कुल सही! जवाब है...', character: 'meera', emotion: 'happy', context: 'riddle_answer', tags: ['correct'] },
    { id: 'hi_meera_riddle_answer_002', text: 'नहीं! सही जवाब ये था — सोचो क्यों!', character: 'meera', emotion: 'thinking', context: 'riddle_answer', tags: ['wrong', 'explain'] },
    { id: 'hi_meera_discovery_001', text: 'ये तो बहुत पुरानी चीज़ है! शायद इसमें कोई राज़ है!', character: 'meera', emotion: 'surprised', context: 'discovery', tags: ['ancient', 'mystery'] },
    { id: 'hi_meera_challenge_001', text: 'मैं तैयार हूँ! दिमाग की लड़ाई में कोई मुझे नहीं हरा सकता!', character: 'meera', emotion: 'determined', context: 'challenge', tags: ['brain', 'compete'] },
    { id: 'hi_meera_farewell_001', text: 'अगली बार और मुश्किल पहेली लाऊँगी! तैयार रहना!', character: 'meera', emotion: 'happy', context: 'farewell', tags: ['riddle', 'next'] },
    { id: 'hi_meera_introduction_001', text: 'मैं मीरा हूँ — और मेरी favourite चीज़ है किताबें और पहेलियाँ!', character: 'meera', emotion: 'happy', context: 'introduction', tags: ['self', 'books'] },
    { id: 'hi_meera_celebration_001', text: 'हम सबने मिलकर कर दिखाया! Teamwork!', character: 'meera', emotion: 'happy', context: 'celebration', tags: ['teamwork'] },
    { id: 'hi_meera_comfort_001', text: 'घबराओ मत, मैं सोचती हूँ कुछ... हाँ! मिल गया!', character: 'meera', emotion: 'thinking', context: 'comfort', tags: ['solution'] },
    { id: 'hi_meera_narration_001', text: 'इस कहानी में एक बहुत बड़ी सीख छुपी है...', character: 'meera', emotion: 'neutral', context: 'narration', tags: ['story'] },
    { id: 'hi_meera_threat_001', text: 'कालिया, तुम्हारी चालाकी इस बार काम नहीं आएगी!', character: 'meera', emotion: 'angry', context: 'threat', tags: ['villain', 'warn'] },

    // ─── BABLU (comic sidekick) ────────────────────────
    { id: 'hi_bablu_greeting_001', text: 'ओ भाई, नाश्ता हो गया? मेरे पेट में चूहे कूद रहे हैं!', character: 'bablu', emotion: 'happy', context: 'greeting', tags: ['food', 'hungry'] },
    { id: 'hi_bablu_greeting_002', text: 'क्या बात है! आज समोसे मिलेंगे क्या?', character: 'bablu', emotion: 'happy', context: 'greeting', tags: ['samosa', 'food'] },
    { id: 'hi_bablu_greeting_003', text: 'अरे यार, सुबह सुबह इतना काम? पहले खाना तो दो!', character: 'bablu', emotion: 'sad', context: 'greeting', tags: ['lazy', 'food'] },
    { id: 'hi_bablu_conflict_001', text: 'बाप रे! मैं तो भागता हूँ! तुम लोग handle करो!', character: 'bablu', emotion: 'scared', context: 'conflict', tags: ['run', 'scared'] },
    { id: 'hi_bablu_conflict_002', text: 'अरे... ये तो मुसीबत है! मेरा लड्डू गिर गया!', character: 'bablu', emotion: 'sad', context: 'conflict', tags: ['food', 'problem'] },
    { id: 'hi_bablu_conflict_003', text: 'मैं? लड़ाई? नहीं भाई, मैं तो cook हूँ, fighter नहीं!', character: 'bablu', emotion: 'scared', context: 'conflict', tags: ['coward', 'funny'] },
    { id: 'hi_bablu_conflict_004', text: 'ऐ कालिया, तू बहुत बदमाश है! मेरा खाना क्यों छीना?', character: 'bablu', emotion: 'angry', context: 'conflict', tags: ['food', 'villain'] },
    { id: 'hi_bablu_resolution_001', text: 'चलो खुश हूँ! अब party करते हैं! खाना कहाँ है?', character: 'bablu', emotion: 'happy', context: 'resolution', tags: ['party', 'food'] },
    { id: 'hi_bablu_resolution_002', text: 'मैंने भी help की थी! मैंने... उम... moral support दी थी!', character: 'bablu', emotion: 'happy', context: 'resolution', tags: ['funny', 'credit'] },
    { id: 'hi_bablu_moral_001', text: 'गुरुजी, ये सीख मुझे भी याद रहेगी... खाने के बाद!', character: 'bablu', emotion: 'happy', context: 'moral', tags: ['food', 'funny'] },
    { id: 'hi_bablu_moral_002', text: 'सच बोलना ज़रूरी है — specially जब कोई पूछे कि समोसा किसने खाया!', character: 'bablu', emotion: 'thinking', context: 'moral', tags: ['honesty', 'food'] },
    { id: 'hi_bablu_reaction_001', text: 'ओ माँ! ये क्या हो गया! मेरी तो टांगें काँप रही हैं!', character: 'bablu', emotion: 'scared', context: 'reaction', tags: ['scared', 'funny'] },
    { id: 'hi_bablu_reaction_002', text: 'वाह! क्या बात है! ये तो जलेबी जैसा twist है!', character: 'bablu', emotion: 'surprised', context: 'reaction', tags: ['twist', 'food'] },
    { id: 'hi_bablu_reaction_003', text: 'हा हा हा! ये तो बहुत funny है! पेट दुख गया हँसते हँसते!', character: 'bablu', emotion: 'happy', context: 'reaction', tags: ['laugh'] },
    { id: 'hi_bablu_celebration_001', text: 'जीत गए! मिठाई लाओ! लड्डू लाओ! गुलाब जामुन लाओ!', character: 'bablu', emotion: 'happy', context: 'celebration', tags: ['sweets', 'party'] },
    { id: 'hi_bablu_discovery_001', text: 'ये क्या है? खाने की चीज़ है क्या? सूँघ के देखता हूँ!', character: 'bablu', emotion: 'surprised', context: 'discovery', tags: ['food', 'smell'] },
    { id: 'hi_bablu_comfort_001', text: 'रो मत यार! चल, मैं तुझे अपना आखिरी समोसा दे देता हूँ!', character: 'bablu', emotion: 'sad', context: 'comfort', tags: ['sacrifice', 'food'] },
    { id: 'hi_bablu_introduction_001', text: 'मेरा नाम बबलू है! मेरा शौक? खाना! मेरी ताकत? खाना! मेरी कमज़ोरी? और खाना!', character: 'bablu', emotion: 'happy', context: 'introduction', tags: ['self', 'food'] },
    { id: 'hi_bablu_farewell_001', text: 'चलो bye! अगली बार ज़्यादा समोसे लाना! ये भूलना मत!', character: 'bablu', emotion: 'happy', context: 'farewell', tags: ['bye', 'food'] },
    { id: 'hi_bablu_narration_001', text: 'और फिर... पता है क्या हुआ? रुको बताता हूँ! पहले खाना खा लूँ!', character: 'bablu', emotion: 'happy', context: 'narration', tags: ['funny', 'food'] },
    { id: 'hi_bablu_challenge_001', text: 'Challenge? मैं ready हूँ! अगर खाने का challenge हो तो!', character: 'bablu', emotion: 'happy', context: 'challenge', tags: ['food', 'funny'] },

    // ─── GURUJI (wise elder) ───────────────────────────
    { id: 'hi_guruji_greeting_001', text: 'आओ बच्चों! आज एक बहुत पुरानी कहानी सुनाता हूँ!', character: 'guruji', emotion: 'happy', context: 'greeting', tags: ['story', 'children'] },
    { id: 'hi_guruji_greeting_002', text: 'सत्यमेव जयते! सत्य की हमेशा जीत होती है!', character: 'guruji', emotion: 'neutral', context: 'greeting', tags: ['truth', 'sanskrit'] },
    { id: 'hi_guruji_conflict_001', text: 'धीरज रखो बच्चों! हर मुसीबत का हल होता है!', character: 'guruji', emotion: 'neutral', context: 'conflict', tags: ['patience', 'wisdom'] },
    { id: 'hi_guruji_conflict_002', text: 'विद्या ददाति विनयम् — ज्ञान विनम्रता देता है!', character: 'guruji', emotion: 'thinking', context: 'conflict', tags: ['sanskrit', 'knowledge'] },
    { id: 'hi_guruji_conflict_003', text: 'ताकत से नहीं, समझ से लड़ो! मन को शांत रखो!', character: 'guruji', emotion: 'neutral', context: 'conflict', tags: ['calm', 'wisdom'] },
    { id: 'hi_guruji_resolution_001', text: 'शाबाश! तुमने सही रास्ता चुना! गर्व है मुझे!', character: 'guruji', emotion: 'happy', context: 'resolution', tags: ['proud', 'right_path'] },
    { id: 'hi_guruji_resolution_002', text: 'देखो, जब दिल साफ़ हो तो राह अपने आप मिल जाती है!', character: 'guruji', emotion: 'happy', context: 'resolution', tags: ['heart', 'path'] },
    { id: 'hi_guruji_moral_001', text: 'याद रखो बच्चों — सच्चा धन ज्ञान और प्रेम है!', character: 'guruji', emotion: 'neutral', context: 'moral', tags: ['wealth', 'knowledge', 'love'] },
    { id: 'hi_guruji_moral_002', text: 'जो दूसरों की मदद करता है, उसकी मदद ज़रूर आती है!', character: 'guruji', emotion: 'happy', context: 'moral', tags: ['help', 'karma'] },
    { id: 'hi_guruji_moral_003', text: 'अहंकार पतन का कारण है — विनम्रता से बड़ी कोई ताकत नहीं!', character: 'guruji', emotion: 'thinking', context: 'moral', tags: ['pride', 'humility'] },
    { id: 'hi_guruji_moral_004', text: 'एक और बात — सबसे बड़ा योद्धा वो है जो खुद पर विजय पाए!', character: 'guruji', emotion: 'neutral', context: 'moral', tags: ['self', 'victory'] },
    { id: 'hi_guruji_reaction_001', text: 'हम्म्म... बहुत interesting! मुझे एक कहानी याद आ रही है!', character: 'guruji', emotion: 'thinking', context: 'reaction', tags: ['story', 'remember'] },
    { id: 'hi_guruji_narration_001', text: 'बहुत पुरानी बात है... जब इस जंगल में एक बुद्धिमान प्राणी रहता था...', character: 'guruji', emotion: 'neutral', context: 'narration', tags: ['story_start', 'ancient'] },
    { id: 'hi_guruji_narration_002', text: 'और इस तरह, उस छोटे से प्राणी ने बड़ी सीख दे दी!', character: 'guruji', emotion: 'happy', context: 'narration', tags: ['story_end', 'lesson'] },
    { id: 'hi_guruji_comfort_001', text: 'बेटा, हार मत मानो! असली ताकत गिरकर उठने में है!', character: 'guruji', emotion: 'neutral', context: 'comfort', tags: ['encourage', 'strength'] },
    { id: 'hi_guruji_introduction_001', text: 'मैं गुरुजी हूँ! मेरे पास कहानियों का अनमोल खज़ाना है!', character: 'guruji', emotion: 'happy', context: 'introduction', tags: ['self', 'stories'] },
    { id: 'hi_guruji_farewell_001', text: 'जाओ बच्चों, आज की सीख को दिल में रखना! फिर मिलेंगे!', character: 'guruji', emotion: 'happy', context: 'farewell', tags: ['lesson', 'bye'] },
    { id: 'hi_guruji_discovery_001', text: 'ये तो बहुत प्राचीन है! इसमें हमारे पूर्वजों की बुद्धि छुपी है!', character: 'guruji', emotion: 'surprised', context: 'discovery', tags: ['ancient', 'wisdom'] },
    { id: 'hi_guruji_riddle_question_001', text: 'अब एक पहेली! ध्यान से सुनो और सोचो!', character: 'guruji', emotion: 'happy', context: 'riddle_question', tags: ['riddle'] },
    { id: 'hi_guruji_riddle_answer_001', text: 'वाह! सही जवाब! तुम सच में बुद्धिमान हो!', character: 'guruji', emotion: 'happy', context: 'riddle_answer', tags: ['correct', 'praise'] },

    // ─── KAALIYA (villain) ─────────────────────────────
    { id: 'hi_kaaliya_greeting_001', text: 'ह्म्म्म... आज कौन सा बेवकूफ़ मेरे रास्ते में आएगा?', character: 'kaaliya', emotion: 'angry', context: 'greeting', tags: ['menace'] },
    { id: 'hi_kaaliya_conflict_001', text: 'तुम्हारी हिम्मत कैसे हुई मेरे रास्ते में आने की!', character: 'kaaliya', emotion: 'angry', context: 'conflict', tags: ['threat', 'power'] },
    { id: 'hi_kaaliya_conflict_002', text: 'मूर्खों! तुम मुझसे नहीं जीत सकते! कभी नहीं!', character: 'kaaliya', emotion: 'angry', context: 'conflict', tags: ['superior'] },
    { id: 'hi_kaaliya_conflict_003', text: 'हा हा हा! मेरा जाल तैयार है! अब देखो तमाशा!', character: 'kaaliya', emotion: 'happy', context: 'conflict', tags: ['trap', 'evil_laugh'] },
    { id: 'hi_kaaliya_conflict_004', text: 'ये सब मेरा है! और कोई इसे छू भी नहीं सकता!', character: 'kaaliya', emotion: 'angry', context: 'conflict', tags: ['greed', 'mine'] },
    { id: 'hi_kaaliya_threat_001', text: 'सुनो सब! जो मेरे खिलाफ़ जाएगा, उसका अंजाम अच्छा नहीं होगा!', character: 'kaaliya', emotion: 'angry', context: 'threat', tags: ['warning', 'power'] },
    { id: 'hi_kaaliya_threat_002', text: 'अर्जुन! तू और तेरे ये दोस्त — आज तुम सब को सबक सिखाऊँगा!', character: 'kaaliya', emotion: 'angry', context: 'threat', tags: ['arjun', 'revenge'] },
    { id: 'hi_kaaliya_resolution_001', text: 'ठीक है... शायद मैं गलत था... लेकिन ये आखिरी बार है!', character: 'kaaliya', emotion: 'sad', context: 'resolution', tags: ['admit', 'change'] },
    { id: 'hi_kaaliya_resolution_002', text: 'हुँह! अगली बार देखना! मैं फिर आऊँगा!', character: 'kaaliya', emotion: 'angry', context: 'resolution', tags: ['retreat', 'return'] },
    { id: 'hi_kaaliya_moral_001', text: 'शायद... शायद दोस्ती ताकत से ज़्यादा ज़रूरी है...', character: 'kaaliya', emotion: 'thinking', context: 'moral', tags: ['change', 'friendship'] },
    { id: 'hi_kaaliya_reaction_001', text: 'क्या?! ये कैसे हो सकता है! नहीं!', character: 'kaaliya', emotion: 'surprised', context: 'reaction', tags: ['shock', 'disbelief'] },
    { id: 'hi_kaaliya_reaction_002', text: 'तुम लोग बहुत चालाक हो... लेकिन मैं और भी चालाक हूँ!', character: 'kaaliya', emotion: 'thinking', context: 'reaction', tags: ['cunning'] },
    { id: 'hi_kaaliya_introduction_001', text: 'मैं कालिया! इस जंगल का सबसे शक्तिशाली! सब मुझसे डरते हैं!', character: 'kaaliya', emotion: 'angry', context: 'introduction', tags: ['self', 'power'] },
    { id: 'hi_kaaliya_discovery_001', text: 'अहा! ये तो बहुत कीमती है! अब ये मेरा है!', character: 'kaaliya', emotion: 'happy', context: 'discovery', tags: ['greed', 'treasure'] },
    { id: 'hi_kaaliya_farewell_001', text: 'याद रखना... कालिया हमेशा वापस आता है!', character: 'kaaliya', emotion: 'angry', context: 'farewell', tags: ['return', 'ominous'] },
    { id: 'hi_kaaliya_challenge_001', text: 'चुनौती? मुझे? हा! तुम्हें नहीं पता तुम किससे पंगा ले रहे हो!', character: 'kaaliya', emotion: 'angry', context: 'challenge', tags: ['power', 'arrogant'] },

    // ─── AMMA (mother) ─────────────────────────────────
    { id: 'hi_amma_greeting_001', text: 'आओ बच्चों, खाना तैयार है! पहले हाथ धो लो!', character: 'amma', emotion: 'happy', context: 'greeting', tags: ['food', 'care'] },
    { id: 'hi_amma_greeting_002', text: 'मेरे लाडले! कैसा रहा तुम्हारा दिन?', character: 'amma', emotion: 'happy', context: 'greeting', tags: ['love', 'day'] },
    { id: 'hi_amma_conflict_001', text: 'बच्चों, लड़ो मत! प्यार से बात करो!', character: 'amma', emotion: 'sad', context: 'conflict', tags: ['peace', 'love'] },
    { id: 'hi_amma_conflict_002', text: 'मुझे चिंता हो रही है... बच्चे कहाँ हैं?', character: 'amma', emotion: 'scared', context: 'conflict', tags: ['worry', 'children'] },
    { id: 'hi_amma_resolution_001', text: 'शुक्र है भगवान का! मेरे बच्चे सही सलामत हैं!', character: 'amma', emotion: 'happy', context: 'resolution', tags: ['relief', 'god'] },
    { id: 'hi_amma_moral_001', text: 'याद रखो बेटा, प्यार सबसे बड़ी ताकत है!', character: 'amma', emotion: 'happy', context: 'moral', tags: ['love', 'strength'] },
    { id: 'hi_amma_moral_002', text: 'जो दूसरों का दर्द समझे, वही सच्चा इंसान है!', character: 'amma', emotion: 'neutral', context: 'moral', tags: ['empathy', 'human'] },
    { id: 'hi_amma_comfort_001', text: 'रो मत मेरे बच्चे! अम्मा है ना! सब ठीक हो जाएगा!', character: 'amma', emotion: 'sad', context: 'comfort', tags: ['mother', 'hug'] },
    { id: 'hi_amma_comfort_002', text: 'आ जा मेरे पास! जब तक अम्मा है, कोई डर नहीं!', character: 'amma', emotion: 'happy', context: 'comfort', tags: ['protect', 'love'] },
    { id: 'hi_amma_reaction_001', text: 'हे भगवान! ये क्या हो गया!', character: 'amma', emotion: 'surprised', context: 'reaction', tags: ['shock', 'god'] },
    { id: 'hi_amma_introduction_001', text: 'मैं इन सब बच्चों की अम्मा हूँ! और इनकी ख़ुशी ही मेरी दुनिया है!', character: 'amma', emotion: 'happy', context: 'introduction', tags: ['self', 'mother'] },
    { id: 'hi_amma_farewell_001', text: 'जल्दी वापस आना! और रास्ते में कुछ खा लेना!', character: 'amma', emotion: 'happy', context: 'farewell', tags: ['care', 'food'] },
    { id: 'hi_amma_narration_001', text: 'मेरी दादी कहती थीं — हर बच्चे के अंदर एक हीरो छुपा है!', character: 'amma', emotion: 'neutral', context: 'narration', tags: ['grandmother', 'hero'] },
    { id: 'hi_amma_celebration_001', text: 'बहुत अच्छा! आज मैं सबके लिए खीर बनाऊँगी!', character: 'amma', emotion: 'happy', context: 'celebration', tags: ['sweet', 'reward'] },

    // ─── RAJA (king) ───────────────────────────────────
    { id: 'hi_raja_greeting_001', text: 'प्रजा को मेरा नमस्कार! आज दरबार में क्या मामला है?', character: 'raja', emotion: 'neutral', context: 'greeting', tags: ['court', 'king'] },
    { id: 'hi_raja_conflict_001', text: 'ये अन्याय है! राज्य में ऐसा नहीं चलेगा!', character: 'raja', emotion: 'angry', context: 'conflict', tags: ['justice', 'kingdom'] },
    { id: 'hi_raja_conflict_002', text: 'कौन है जो हमारे राज्य में उपद्रव कर रहा है?', character: 'raja', emotion: 'angry', context: 'conflict', tags: ['trouble', 'authority'] },
    { id: 'hi_raja_resolution_001', text: 'न्याय हो गया! अब राज्य में शांति रहेगी!', character: 'raja', emotion: 'happy', context: 'resolution', tags: ['justice', 'peace'] },
    { id: 'hi_raja_moral_001', text: 'एक अच्छा राजा वो है जो प्रजा की सेवा करे!', character: 'raja', emotion: 'neutral', context: 'moral', tags: ['king', 'service'] },
    { id: 'hi_raja_reaction_001', text: 'ये तो बहुत अद्भुत है! शाबाश!', character: 'raja', emotion: 'surprised', context: 'reaction', tags: ['impressed'] },
    { id: 'hi_raja_challenge_001', text: 'जो इस चुनौती में जीतेगा, उसे इनाम मिलेगा!', character: 'raja', emotion: 'neutral', context: 'challenge', tags: ['reward', 'compete'] },
    { id: 'hi_raja_introduction_001', text: 'मैं इस राज्य का राजा हूँ! न्याय और धर्म मेरा कर्तव्य है!', character: 'raja', emotion: 'neutral', context: 'introduction', tags: ['self', 'duty'] },
    { id: 'hi_raja_discovery_001', text: 'ये तो राज्य का प्राचीन खज़ाना है! इसे सँभालो!', character: 'raja', emotion: 'surprised', context: 'discovery', tags: ['treasure', 'ancient'] },
    { id: 'hi_raja_farewell_001', text: 'जाओ और राज्य की सेवा करो! यही सबसे बड़ा धर्म है!', character: 'raja', emotion: 'neutral', context: 'farewell', tags: ['duty', 'service'] },
    { id: 'hi_raja_narration_001', text: 'बहुत समय पहले, इसी राज्य में एक महान राजा रहते थे...', character: 'raja', emotion: 'neutral', context: 'narration', tags: ['story_start'] },
    { id: 'hi_raja_celebration_001', text: 'आज पूरे राज्य में उत्सव मनाया जाएगा! सबको मिठाई बाँटो!', character: 'raja', emotion: 'happy', context: 'celebration', tags: ['festival', 'sweets'] },
    { id: 'hi_raja_comfort_001', text: 'चिंता मत करो! जब तक राजा है, प्रजा सुरक्षित है!', character: 'raja', emotion: 'neutral', context: 'comfort', tags: ['protect', 'assure'] },
    { id: 'hi_raja_threat_001', text: 'सावधान! जो राज्य के नियम तोड़ेगा, उसे दंड मिलेगा!', character: 'raja', emotion: 'angry', context: 'threat', tags: ['law', 'punish'] },

    // ─── MOTI (animal) ─────────────────────────────────
    { id: 'hi_moti_greeting_001', text: 'भौं भौं! (पूँछ हिलाते हुए)', character: 'moti', emotion: 'happy', context: 'greeting', tags: ['bark', 'tail'] },
    { id: 'hi_moti_conflict_001', text: 'गर्र्र्र! (बचाने की कोशिश करते हुए)', character: 'moti', emotion: 'angry', context: 'conflict', tags: ['growl', 'protect'] },
    { id: 'hi_moti_resolution_001', text: 'भौं! भौं भौं! (ख़ुशी से कूदते हुए)', character: 'moti', emotion: 'happy', context: 'resolution', tags: ['bark', 'jump'] },
    { id: 'hi_moti_reaction_001', text: 'कूँ कूँ? (सर टेढ़ा करते हुए)', character: 'moti', emotion: 'surprised', context: 'reaction', tags: ['confused', 'head_tilt'] },
    { id: 'hi_moti_comfort_001', text: 'कूँ... (धीरे से सहलाते हुए)', character: 'moti', emotion: 'sad', context: 'comfort', tags: ['nuzzle', 'gentle'] },
    { id: 'hi_moti_celebration_001', text: 'भौं भौं भौं! (गोल गोल घूमते हुए)', character: 'moti', emotion: 'happy', context: 'celebration', tags: ['spin', 'happy'] },
    { id: 'hi_moti_discovery_001', text: 'भौं! भौं! (कुछ सूँघते हुए, ज़ोर से भौंकते हुए)', character: 'moti', emotion: 'surprised', context: 'discovery', tags: ['sniff', 'find'] },
    { id: 'hi_moti_introduction_001', text: 'भौं! (मैं मोती हूँ — सबका सबसे अच्छा दोस्त!)', character: 'moti', emotion: 'happy', context: 'introduction', tags: ['self', 'friend'] },
    { id: 'hi_moti_farewell_001', text: 'कूँ... भौं! (जाने नहीं देना चाहते, फिर bye करते हुए)', character: 'moti', emotion: 'sad', context: 'farewell', tags: ['sad', 'bye'] },
    { id: 'hi_moti_threat_001', text: 'गर्र्र्र्र्र! (दाँत दिखाते हुए)', character: 'moti', emotion: 'angry', context: 'threat', tags: ['growl', 'teeth'] },
    { id: 'hi_moti_narration_001', text: '(मोती चुपचाप सुन रहा था, जैसे उसे सब समझ आ रहा हो)', character: 'moti', emotion: 'neutral', context: 'narration', tags: ['listen', 'wise'] },
    { id: 'hi_moti_moral_001', text: 'भौं! (वफ़ादारी सबसे बड़ा गुण है!)', character: 'moti', emotion: 'happy', context: 'moral', tags: ['loyalty'] },
    { id: 'hi_moti_challenge_001', text: 'भौं भौं! (तैयार है! दौड़ लगाते हुए)', character: 'moti', emotion: 'determined', context: 'challenge', tags: ['ready', 'run'] },

    // ═══════════════════════════════════════════════════════════════════
    // EXPANSION PACK — 175+ new lines to reach 350+ total
    // ═══════════════════════════════════════════════════════════════════

    // ─── ARJUN (more discovery + challenge lines) ────────────────────
    { id: 'hi_arjun_discovery_003', text: 'अरे! ये गुफा तो बहुत गहरी है! अंदर चलते हैं!', character: 'arjun', emotion: 'surprised', context: 'discovery', tags: ['cave', 'explore'] },
    { id: 'hi_arjun_discovery_004', text: 'ये निशान कहीं देखे हैं मैंने... गुरुजी की किताब में!', character: 'arjun', emotion: 'thinking', context: 'discovery', tags: ['clue', 'book'] },
    { id: 'hi_arjun_discovery_005', text: 'मीरा! जल्दी आओ! ये तो ख़ज़ाने का नक्शा है!', character: 'arjun', emotion: 'surprised', context: 'discovery', tags: ['map', 'treasure'] },
    { id: 'hi_arjun_discovery_006', text: 'रुको... कुछ आवाज़ आ रही है... ध्यान से सुनो!', character: 'arjun', emotion: 'scared', context: 'discovery', tags: ['sound', 'careful'] },
    { id: 'hi_arjun_discovery_007', text: 'ये पत्थर पर कुछ लिखा है! बहुत पुरानी भाषा में!', character: 'arjun', emotion: 'thinking', context: 'discovery', tags: ['ancient', 'inscription'] },
    { id: 'hi_arjun_challenge_003', text: 'तैयार हो जाओ सब! ये मुकाबला हम जीतेंगे!', character: 'arjun', emotion: 'determined', context: 'challenge', tags: ['team', 'compete'] },
    { id: 'hi_arjun_challenge_004', text: 'हार मानना मेरे बस में नहीं! फिर से कोशिश करेंगे!', character: 'arjun', emotion: 'determined', context: 'challenge', tags: ['retry', 'brave'] },
    { id: 'hi_arjun_challenge_005', text: 'ये चुनौती कठिन है, लेकिन हमारी टीम और भी कठिन है!', character: 'arjun', emotion: 'happy', context: 'challenge', tags: ['team', 'tough'] },
    { id: 'hi_arjun_challenge_006', text: 'चल बबलू, डर मत! मैं आगे चलता हूँ, तू पीछे आ!', character: 'arjun', emotion: 'determined', context: 'challenge', tags: ['bablu', 'lead'] },
    { id: 'hi_arjun_conflict_007', text: 'अगर कालिया ने गाँव वालों को नुक्सान पहुँचाया तो मैं चुप नहीं बैठूँगा!', character: 'arjun', emotion: 'angry', context: 'conflict', tags: ['village', 'protect'] },
    { id: 'hi_arjun_conflict_008', text: 'ये अंधेरा कितना भी गहरा हो, रोशनी ज़रूर आएगी!', character: 'arjun', emotion: 'determined', context: 'conflict', tags: ['hope', 'light'] },
    { id: 'hi_arjun_reaction_004', text: 'क्या?! ये तो मैंने सोचा ही नहीं था!', character: 'arjun', emotion: 'surprised', context: 'reaction', tags: ['unexpected'] },
    { id: 'hi_arjun_reaction_005', text: 'ये तो बहुत बढ़िया idea है मीरा! चलो करते हैं!', character: 'arjun', emotion: 'happy', context: 'reaction', tags: ['agree', 'meera'] },
    { id: 'hi_arjun_greeting_006', text: 'आज का दिन बहुत अलग लग रहा है... कुछ होने वाला है!', character: 'arjun', emotion: 'thinking', context: 'greeting', tags: ['premonition'] },
    { id: 'hi_arjun_resolution_004', text: 'आज हमने साबित कर दिया — हम किसी से कम नहीं!', character: 'arjun', emotion: 'happy', context: 'resolution', tags: ['pride', 'victory'] },
    { id: 'hi_arjun_resolution_005', text: 'कालिया भाग गया! चलो दोस्तों, जश्न मनाते हैं!', character: 'arjun', emotion: 'happy', context: 'resolution', tags: ['villain', 'celebrate'] },
    { id: 'hi_arjun_moral_004', text: 'जिसके पास अच्छे दोस्त हैं, उसे किसी चीज़ की कमी नहीं!', character: 'arjun', emotion: 'happy', context: 'moral', tags: ['friendship', 'value'] },
    { id: 'hi_arjun_narration_002', text: 'और इस तरह शुरू हुआ हमारा सबसे बड़ा adventure!', character: 'arjun', emotion: 'happy', context: 'narration', tags: ['story_start', 'adventure'] },

    // ─── MEERA (more riddle + discovery lines) ───────────────────────
    { id: 'hi_meera_riddle_question_003', text: 'ये बताओ — वो क्या है जिसके पास आँखें हैं पर देख नहीं सकता?', character: 'meera', emotion: 'thinking', context: 'riddle_question', tags: ['riddle', 'classic'] },
    { id: 'hi_meera_riddle_question_004', text: 'सोचो... ऐसी कौन सी चीज़ है जो जितनी बढ़ती है, उतनी कम दिखती है?', character: 'meera', emotion: 'thinking', context: 'riddle_question', tags: ['riddle', 'tricky'] },
    { id: 'hi_meera_riddle_question_005', text: 'ध्यान से सुनो — बिना पंखों के उड़ता है, बिना आँखों के रुलाता है — बताओ क्या?', character: 'meera', emotion: 'happy', context: 'riddle_question', tags: ['riddle', 'wind'] },
    { id: 'hi_meera_riddle_question_006', text: 'एक और पहेली! सौ बच्चों की माँ, बिना खाना खाए मर जाए — कौन?', character: 'meera', emotion: 'happy', context: 'riddle_question', tags: ['riddle', 'traditional'] },
    { id: 'hi_meera_riddle_question_007', text: 'चलो brain challenge! काला है पर कोयला नहीं, गोल है पर बॉल नहीं?', character: 'meera', emotion: 'determined', context: 'riddle_question', tags: ['riddle', 'fun'] },
    { id: 'hi_meera_riddle_question_008', text: 'ये wala mushkil hai — aise kaun si cheez hai jo todne se aur mazboot hoti hai?', character: 'meera', emotion: 'thinking', context: 'riddle_question', tags: ['riddle', 'hard'] },
    { id: 'hi_meera_riddle_answer_003', text: 'बहुत करीब! लेकिन सही जवाब कुछ और है — सोचो!', character: 'meera', emotion: 'happy', context: 'riddle_answer', tags: ['close', 'hint'] },
    { id: 'hi_meera_riddle_answer_004', text: 'वाह! एकदम सही! तुम तो genius हो!', character: 'meera', emotion: 'happy', context: 'riddle_answer', tags: ['correct', 'praise'] },
    { id: 'hi_meera_riddle_answer_005', text: 'Time up! जवाब था — अंधेरा! समझे? अंधेरा बढ़ता है तो कम दिखता है!', character: 'meera', emotion: 'happy', context: 'riddle_answer', tags: ['reveal', 'explain'] },
    { id: 'hi_meera_riddle_answer_006', text: 'जवाब है record! Record तोड़ने से और मज़बूत record बनता है!', character: 'meera', emotion: 'happy', context: 'riddle_answer', tags: ['reveal', 'clever'] },
    { id: 'hi_meera_discovery_002', text: 'रुको! इस pattern में कुछ code छुपा है! मुझे decode करने दो!', character: 'meera', emotion: 'thinking', context: 'discovery', tags: ['code', 'pattern'] },
    { id: 'hi_meera_discovery_003', text: 'ये herbs बहुत special हैं! इनसे दवाई बन सकती है!', character: 'meera', emotion: 'surprised', context: 'discovery', tags: ['herbs', 'medicine'] },
    { id: 'hi_meera_discovery_004', text: 'ये map ancient Sanskrit में है! मुझे थोड़ा वक़्त दो!', character: 'meera', emotion: 'thinking', context: 'discovery', tags: ['map', 'sanskrit'] },
    { id: 'hi_meera_conflict_004', text: 'अर्जुन, सुनो! सीधे लड़ने से काम नहीं बनेगा — strategy चाहिए!', character: 'meera', emotion: 'determined', context: 'conflict', tags: ['strategy', 'arjun'] },
    { id: 'hi_meera_conflict_005', text: 'ये trap है! कालिया हमें फँसाना चाहता है! पीछे हटो!', character: 'meera', emotion: 'scared', context: 'conflict', tags: ['trap', 'warn'] },
    { id: 'hi_meera_reaction_003', text: 'Wait wait wait! मुझे कुछ याद आ रहा है! हाँ!', character: 'meera', emotion: 'surprised', context: 'reaction', tags: ['remember', 'eureka'] },
    { id: 'hi_meera_reaction_004', text: 'ये तो science में possible ही नहीं है! कैसे हुआ ये?', character: 'meera', emotion: 'surprised', context: 'reaction', tags: ['science', 'impossible'] },
    { id: 'hi_meera_greeting_003', text: 'Good morning सबको! आज मैंने एक नई किताब पढ़ी — बहुत काम आएगी!', character: 'meera', emotion: 'happy', context: 'greeting', tags: ['book', 'morning'] },
    { id: 'hi_meera_moral_003', text: 'किताबों में हर सवाल का जवाब है — बस पढ़ने की ज़रूरत है!', character: 'meera', emotion: 'thinking', context: 'moral', tags: ['books', 'knowledge'] },
    { id: 'hi_meera_moral_004', text: 'समस्या से डरो मत, समस्या को समझो — हल अपने आप मिल जाएगा!', character: 'meera', emotion: 'determined', context: 'moral', tags: ['problem', 'solution'] },
    { id: 'hi_meera_comfort_002', text: 'बबलू, डरने की ज़रूरत नहीं! मैंने सब calculate कर लिया है!', character: 'meera', emotion: 'happy', context: 'comfort', tags: ['bablu', 'calculate'] },

    // ─── BABLU (more food jokes — breakout character) ────────────────
    { id: 'hi_bablu_greeting_004', text: 'दोस्तों! आज अम्मा ने पराँठे बनाए हैं! ज़िंदगी beautiful है!', character: 'bablu', emotion: 'happy', context: 'greeting', tags: ['food', 'parantha'] },
    { id: 'hi_bablu_greeting_005', text: 'ओ भाई, मुझे मत बुलाओ अगर खाना नहीं है तो!', character: 'bablu', emotion: 'sad', context: 'greeting', tags: ['food', 'condition'] },
    { id: 'hi_bablu_greeting_006', text: 'अरे! आज मेला लगा है! चाट, गोल गप्पे, छोले भटूरे! चलो चलो!', character: 'bablu', emotion: 'happy', context: 'greeting', tags: ['fair', 'streetfood'] },
    { id: 'hi_bablu_conflict_005', text: 'ये लड़ाई बाद में! पहले बताओ — lunch break कब है?', character: 'bablu', emotion: 'happy', context: 'conflict', tags: ['food', 'funny', 'timing'] },
    { id: 'hi_bablu_conflict_006', text: 'अरे बचाओ! कालिया ने मेरी थाली पलट दी! ये तो युद्ध है!', character: 'bablu', emotion: 'angry', context: 'conflict', tags: ['food', 'war', 'villain'] },
    { id: 'hi_bablu_conflict_007', text: 'मैं लड़ नहीं सकता... पेट भारी है! दो plate खा लिए अभी!', character: 'bablu', emotion: 'scared', context: 'conflict', tags: ['food', 'heavy', 'funny'] },
    { id: 'hi_bablu_conflict_008', text: 'कालिया भाई, तू चाहे तो मेरे साथ खाना खा ले — लड़ाई क्यों?', character: 'bablu', emotion: 'thinking', context: 'conflict', tags: ['peace', 'food', 'funny'] },
    { id: 'hi_bablu_reaction_004', text: 'ये जगह haunted है?! मेरा भूख ही मर गई! ... wait, नहीं, भूख तो लगी है!', character: 'bablu', emotion: 'scared', context: 'reaction', tags: ['scared', 'food', 'funny'] },
    { id: 'hi_bablu_reaction_005', text: 'इतना मज़ेदार twist! ये तो samose में चटनी जैसा surprise है!', character: 'bablu', emotion: 'surprised', context: 'reaction', tags: ['twist', 'samosa', 'food'] },
    { id: 'hi_bablu_reaction_006', text: 'मीरा, तेरा दिमाग तो biryani की तरह spicy है!', character: 'bablu', emotion: 'happy', context: 'reaction', tags: ['meera', 'biryani', 'food'] },
    { id: 'hi_bablu_reaction_007', text: 'ओहो! ये तो butter chicken level की बात हो गई!', character: 'bablu', emotion: 'surprised', context: 'reaction', tags: ['food', 'impressed'] },
    { id: 'hi_bablu_resolution_003', text: 'सब ख़तम? अच्छा हुआ! अब celebration feast! मैं menu बनाता हूँ!', character: 'bablu', emotion: 'happy', context: 'resolution', tags: ['feast', 'menu', 'food'] },
    { id: 'hi_bablu_resolution_004', text: 'देखा? मैंने कहा था ना — खाने का दम! मेरी energy से ही तो जीते!', character: 'bablu', emotion: 'happy', context: 'resolution', tags: ['food', 'credit', 'funny'] },
    { id: 'hi_bablu_moral_003', text: 'असली दोस्त वो है जो अपना last समोसा share करे! ...theoretically!', character: 'bablu', emotion: 'thinking', context: 'moral', tags: ['food', 'friendship', 'funny'] },
    { id: 'hi_bablu_moral_004', text: 'खाना बर्बाद करना सबसे बड़ा पाप है! ये मेरा philosophy है!', character: 'bablu', emotion: 'determined', context: 'moral', tags: ['food', 'waste', 'philosophy'] },
    { id: 'hi_bablu_discovery_002', text: 'ये पेड़ पर आम लग रहे हैं! Discovery of the year!', character: 'bablu', emotion: 'happy', context: 'discovery', tags: ['mango', 'food', 'tree'] },
    { id: 'hi_bablu_discovery_003', text: 'रुको! मुझे एक secret recipe मिली! देखो ये scroll!', character: 'bablu', emotion: 'surprised', context: 'discovery', tags: ['recipe', 'scroll', 'food'] },
    { id: 'hi_bablu_discovery_004', text: 'ये गुफा में mushroom उग रहे हैं! शायद खाने लायक हों!', character: 'bablu', emotion: 'thinking', context: 'discovery', tags: ['mushroom', 'cave', 'food'] },
    { id: 'hi_bablu_celebration_002', text: 'Party! Party! आज 51 गोल गप्पे खाऊँगा! नया record!', character: 'bablu', emotion: 'happy', context: 'celebration', tags: ['goolgappe', 'record', 'food'] },
    { id: 'hi_bablu_celebration_003', text: 'जीत की खुशी में — सबको मेरी तरफ़ से ice cream!', character: 'bablu', emotion: 'happy', context: 'celebration', tags: ['icecream', 'treat', 'food'] },
    { id: 'hi_bablu_comfort_002', text: 'अर्जुन, tension मत ले! जब भी मुझे tension होती है, मैं खाता हूँ! Try कर!', character: 'bablu', emotion: 'happy', context: 'comfort', tags: ['arjun', 'food', 'funny'] },
    { id: 'hi_bablu_comfort_003', text: 'रो मत! ले, ये chocolate खा — सब ठीक हो जाता है!', character: 'bablu', emotion: 'sad', context: 'comfort', tags: ['chocolate', 'food', 'care'] },
    { id: 'hi_bablu_farewell_002', text: 'Bye! अगली बार lunchbox भर के लाना! promise?', character: 'bablu', emotion: 'happy', context: 'farewell', tags: ['lunch', 'food', 'bye'] },
    { id: 'hi_bablu_farewell_003', text: 'चलो! Adventure ख़तम! अब घर चलो — अम्मा का खाना wait कर रहा है!', character: 'bablu', emotion: 'happy', context: 'farewell', tags: ['home', 'food', 'amma'] },
    { id: 'hi_bablu_challenge_002', text: 'Eating contest? मुझे finally मेरा purpose मिल गया!', character: 'bablu', emotion: 'happy', context: 'challenge', tags: ['eating', 'contest', 'food'] },
    { id: 'hi_bablu_challenge_003', text: 'दौड़ना? चढ़ना? ये सब छोड़ो — कुछ खाने-पीने वाला challenge दो!', character: 'bablu', emotion: 'sad', context: 'challenge', tags: ['food', 'funny', 'lazy'] },
    { id: 'hi_bablu_threat_001', text: 'कालिया! मेरे दोस्तों को छोड़! ... और मेरा lunchbox भी!', character: 'bablu', emotion: 'angry', context: 'threat', tags: ['villain', 'food', 'funny'] },
    { id: 'hi_bablu_narration_002', text: 'ये कहानी उस दिन की है जब मैंने 40 समोसे खाए... wait, ये वो कहानी नहीं है!', character: 'bablu', emotion: 'happy', context: 'narration', tags: ['food', 'funny', 'wrong_story'] },

    // ─── GURUJI (more wisdom lines with proverbs) ────────────────────
    { id: 'hi_guruji_moral_005', text: 'उद्यमेन हि सिध्यन्ति कार्याणि — मेहनत से ही काम सिद्ध होते हैं!', character: 'guruji', emotion: 'neutral', context: 'moral', tags: ['sanskrit', 'hardwork'] },
    { id: 'hi_guruji_moral_006', text: 'क्षमा वीरस्य भूषणम् — क्षमा करना वीर का आभूषण है!', character: 'guruji', emotion: 'thinking', context: 'moral', tags: ['sanskrit', 'forgiveness'] },
    { id: 'hi_guruji_moral_007', text: 'सत्यम् शिवम् सुन्दरम् — सत्य ही शिव है, सत्य ही सुंदर है!', character: 'guruji', emotion: 'neutral', context: 'moral', tags: ['sanskrit', 'truth', 'beauty'] },
    { id: 'hi_guruji_moral_008', text: 'अति सर्वत्र वर्जयेत् — हर चीज़ की अति बुरी है! संतुलन रखो!', character: 'guruji', emotion: 'thinking', context: 'moral', tags: ['sanskrit', 'balance'] },
    { id: 'hi_guruji_moral_009', text: 'परोपकाराय फलन्ति वृक्षाः — पेड़ दूसरों के लिए फल देते हैं, हमें भी ऐसा बनना चाहिए!', character: 'guruji', emotion: 'happy', context: 'moral', tags: ['sanskrit', 'selfless', 'nature'] },
    { id: 'hi_guruji_moral_010', text: 'बूँद बूँद से सागर भरता है — छोटे कर्म भी बड़ा फ़र्क़ डालते हैं!', character: 'guruji', emotion: 'neutral', context: 'moral', tags: ['proverb', 'small_steps'] },
    { id: 'hi_guruji_moral_011', text: 'जैसी करनी, वैसी भरनी — कर्मों का फल ज़रूर मिलता है!', character: 'guruji', emotion: 'neutral', context: 'moral', tags: ['proverb', 'karma'] },
    { id: 'hi_guruji_moral_012', text: 'एकता में ही शक्ति है — अकेली उंगली से कभी ताली नहीं बजती!', character: 'guruji', emotion: 'happy', context: 'moral', tags: ['proverb', 'unity'] },
    { id: 'hi_guruji_moral_013', text: 'धैर्य का फल मीठा होता है — जल्दबाज़ी में किया काम बिगड़ जाता है!', character: 'guruji', emotion: 'thinking', context: 'moral', tags: ['proverb', 'patience'] },
    { id: 'hi_guruji_moral_014', text: 'अहिंसा परमो धर्मः — सबसे बड़ा धर्म है किसी को कष्ट न देना!', character: 'guruji', emotion: 'neutral', context: 'moral', tags: ['sanskrit', 'nonviolence'] },
    { id: 'hi_guruji_conflict_004', text: 'बच्चों, क्रोध अंधा कर देता है — शांत मन से सोचो!', character: 'guruji', emotion: 'neutral', context: 'conflict', tags: ['anger', 'calm', 'wisdom'] },
    { id: 'hi_guruji_conflict_005', text: 'जब रास्ता न दिखे, तो अपने अंदर झाँको — जवाब वहीं मिलेगा!', character: 'guruji', emotion: 'thinking', context: 'conflict', tags: ['inner', 'wisdom'] },
    { id: 'hi_guruji_conflict_006', text: 'डर को अपना दुश्मन मत बनाओ — डर को अपना teacher बनाओ!', character: 'guruji', emotion: 'neutral', context: 'conflict', tags: ['fear', 'teacher'] },
    { id: 'hi_guruji_narration_003', text: 'ये कहानी उस समय की है जब जानवर और इंसान एक साथ रहते थे...', character: 'guruji', emotion: 'neutral', context: 'narration', tags: ['story_start', 'animals'] },
    { id: 'hi_guruji_narration_004', text: 'और उस दिन से, पूरे जंगल ने एक नया नियम बनाया...', character: 'guruji', emotion: 'happy', context: 'narration', tags: ['story_end', 'rule'] },
    { id: 'hi_guruji_narration_005', text: 'सुनो ध्यान से! ये कहानी हज़ारों साल पुरानी है, पर सीख आज भी नई है!', character: 'guruji', emotion: 'neutral', context: 'narration', tags: ['timeless', 'lesson'] },
    { id: 'hi_guruji_greeting_003', text: 'सुप्रभात बच्चों! आज का दिन ज्ञान और खोज का दिन है!', character: 'guruji', emotion: 'happy', context: 'greeting', tags: ['morning', 'knowledge'] },
    { id: 'hi_guruji_greeting_004', text: 'आओ बच्चों, बैठो! आज मैं तुम्हें पंचतंत्र की एक अनमोल कथा सुनाऊँगा!', character: 'guruji', emotion: 'happy', context: 'greeting', tags: ['panchatantra', 'story'] },
    { id: 'hi_guruji_reaction_002', text: 'बहुत अच्छा! तुमने वही किया जो मैं सिखाना चाहता था!', character: 'guruji', emotion: 'happy', context: 'reaction', tags: ['proud', 'lesson'] },
    { id: 'hi_guruji_reaction_003', text: 'ये ग़लत हो रहा है... मुझे हस्तक्षेप करना होगा!', character: 'guruji', emotion: 'sad', context: 'reaction', tags: ['intervene', 'wrong'] },
    { id: 'hi_guruji_comfort_002', text: 'बेटा, ग़लतियाँ सीखने के लिए होती हैं — इनसे शर्मिंदा मत होओ!', character: 'guruji', emotion: 'happy', context: 'comfort', tags: ['mistakes', 'learn'] },
    { id: 'hi_guruji_comfort_003', text: 'जीवन में हार-जीत तो लगी रहती है — असली जीत है फिर से खड़े होना!', character: 'guruji', emotion: 'neutral', context: 'comfort', tags: ['resilience', 'life'] },
    { id: 'hi_guruji_resolution_003', text: 'आज तुम सबने मिलकर ये सिद्ध कर दिया — संगठन में शक्ति है!', character: 'guruji', emotion: 'happy', context: 'resolution', tags: ['unity', 'proved'] },
    { id: 'hi_guruji_celebration_001', text: 'आज का दिन इतिहास में लिखा जाएगा! बहुत गर्व है मुझे!', character: 'guruji', emotion: 'happy', context: 'celebration', tags: ['history', 'proud'] },
    { id: 'hi_guruji_discovery_002', text: 'ये प्राचीन ग्रंथ है! इसमें हमारे ऋषियों का ज्ञान है!', character: 'guruji', emotion: 'surprised', context: 'discovery', tags: ['ancient', 'text', 'rishi'] },

    // ─── KAALIYA (more villain lines) ────────────────────────────────
    { id: 'hi_kaaliya_greeting_002', text: 'हा हा हा! आज का दिन बहुत ख़ास है — मेरी जीत का दिन!', character: 'kaaliya', emotion: 'happy', context: 'greeting', tags: ['evil_laugh', 'victory'] },
    { id: 'hi_kaaliya_greeting_003', text: 'अरे अरे! आ गए तुम सब? बहुत अच्छा... जाल में ख़ुद फँसे!', character: 'kaaliya', emotion: 'happy', context: 'greeting', tags: ['trap', 'cunning'] },
    { id: 'hi_kaaliya_conflict_005', text: 'मेरे पास ताकत भी है और दिमाग भी! तुम्हारे पास क्या है?', character: 'kaaliya', emotion: 'angry', context: 'conflict', tags: ['power', 'brain', 'taunt'] },
    { id: 'hi_kaaliya_conflict_006', text: 'ये जंगल मेरा है! मेरा! और कोई इसे मुझसे नहीं छीन सकता!', character: 'kaaliya', emotion: 'angry', context: 'conflict', tags: ['jungle', 'ownership'] },
    { id: 'hi_kaaliya_conflict_007', text: 'अर्जुन, तेरे ये दोस्त भी तुझे नहीं बचा पाएँगे!', character: 'kaaliya', emotion: 'angry', context: 'conflict', tags: ['arjun', 'friends', 'threat'] },
    { id: 'hi_kaaliya_conflict_008', text: 'बुद्धू अर्जुन! मैंने तो plan B भी सोच रखा था!', character: 'kaaliya', emotion: 'happy', context: 'conflict', tags: ['plan', 'cunning'] },
    { id: 'hi_kaaliya_conflict_009', text: 'तुम सोचते हो तुम जीत गए? ये तो बस शुरुआत है!', character: 'kaaliya', emotion: 'angry', context: 'conflict', tags: ['beginning', 'threat'] },
    { id: 'hi_kaaliya_conflict_010', text: 'मेरे गुर्गे चारों तरफ़ हैं! तुम घिरे हुए हो!', character: 'kaaliya', emotion: 'happy', context: 'conflict', tags: ['henchmen', 'surrounded'] },
    { id: 'hi_kaaliya_threat_003', text: 'ये मेरा आख़िरी warning है! अगली बार मैं बात नहीं करूँगा!', character: 'kaaliya', emotion: 'angry', context: 'threat', tags: ['final', 'warning'] },
    { id: 'hi_kaaliya_threat_004', text: 'उस बुड्ढे गुरुजी की सिखाई बातें तुम्हें यहाँ नहीं बचा सकतीं!', character: 'kaaliya', emotion: 'angry', context: 'threat', tags: ['guruji', 'mock'] },
    { id: 'hi_kaaliya_threat_005', text: 'मोती! तू भी? ये कुत्ता मुझ पर भौंकता है? भगाओ इसे!', character: 'kaaliya', emotion: 'angry', context: 'threat', tags: ['moti', 'dog'] },
    { id: 'hi_kaaliya_threat_006', text: 'ये गाँव जल्द ही मेरा होगा! और तुम सब मेरे लिए काम करोगे!', character: 'kaaliya', emotion: 'happy', context: 'threat', tags: ['village', 'conquer'] },
    { id: 'hi_kaaliya_resolution_003', text: 'ये हार नहीं है! ये strategic retreat है! मैं फिर आऊँगा!', character: 'kaaliya', emotion: 'angry', context: 'resolution', tags: ['retreat', 'excuse'] },
    { id: 'hi_kaaliya_resolution_004', text: 'ठीक है... आज तुम जीत गए... पर याद रखना ये दिन!', character: 'kaaliya', emotion: 'sad', context: 'resolution', tags: ['grudge', 'remember'] },
    { id: 'hi_kaaliya_reaction_003', text: 'नहीं! ये impossible है! मेरा plan fail कैसे हो सकता है?!', character: 'kaaliya', emotion: 'surprised', context: 'reaction', tags: ['disbelief', 'fail'] },
    { id: 'hi_kaaliya_reaction_004', text: 'हम्म... ये मीरा बहुत smart है... इसे पहले deal करना होगा!', character: 'kaaliya', emotion: 'thinking', context: 'reaction', tags: ['meera', 'plan'] },
    { id: 'hi_kaaliya_reaction_005', text: 'ये बबलू मोटा ज़रूर है, पर इसमें कुछ तो बात है!', character: 'kaaliya', emotion: 'thinking', context: 'reaction', tags: ['bablu', 'respect'] },
    { id: 'hi_kaaliya_moral_002', text: 'हुँह! ये सब दोस्ती-वोस्ती... मुझे तो ताकत चाहिए बस!', character: 'kaaliya', emotion: 'angry', context: 'moral', tags: ['power', 'reject'] },
    { id: 'hi_kaaliya_moral_003', text: 'शायद... सब कुछ ताकत से नहीं मिलता... शायद मैं ग़लत था...', character: 'kaaliya', emotion: 'sad', context: 'moral', tags: ['change', 'realization'] },
    { id: 'hi_kaaliya_discovery_002', text: 'ये जादुई पत्थर! इससे मैं और ताकतवर बन सकता हूँ!', character: 'kaaliya', emotion: 'happy', context: 'discovery', tags: ['magic', 'power'] },
    { id: 'hi_kaaliya_discovery_003', text: 'ये रास्ता सीधा उनके गाँव में जाता है! Perfect!', character: 'kaaliya', emotion: 'happy', context: 'discovery', tags: ['path', 'village', 'plan'] },
    { id: 'hi_kaaliya_narration_001', text: 'तुम सोचते हो ये कहानी तुम्हारी है? ये तो मेरी कहानी है!', character: 'kaaliya', emotion: 'angry', context: 'narration', tags: ['self', 'story'] },
    { id: 'hi_kaaliya_challenge_002', text: 'ठीक है अर्जुन! आमने-सामने! देखते हैं कौन जीतता है!', character: 'kaaliya', emotion: 'determined', context: 'challenge', tags: ['arjun', 'face_off'] },
    { id: 'hi_kaaliya_challenge_003', text: 'मैं सबको challenge करता हूँ! एक साथ आ जाओ — मैं अकेला काफ़ी हूँ!', character: 'kaaliya', emotion: 'angry', context: 'challenge', tags: ['all', 'arrogant'] },
    { id: 'hi_kaaliya_comfort_001', text: 'हुँह... ठीक है छोटे... रो मत... ये ले, मिठाई खा... किसी को बताना मत!', character: 'kaaliya', emotion: 'sad', context: 'comfort', tags: ['secret', 'soft_side'] },
    { id: 'hi_kaaliya_celebration_001', text: 'आज मेरी जीत! सब मेरी जय-जयकार करो! हा हा हा!', character: 'kaaliya', emotion: 'happy', context: 'celebration', tags: ['victory', 'ego'] },

    // ─── AMMA (more emotional/comfort lines) ─────────────────────────
    { id: 'hi_amma_comfort_003', text: 'मेरा बच्चा, दुनिया में कोई भी हो — अम्मा हमेशा तेरे साथ है!', character: 'amma', emotion: 'sad', context: 'comfort', tags: ['always', 'support'] },
    { id: 'hi_amma_comfort_004', text: 'ये आँसू पोंछ! अम्मा के हाथ का जादू — सब दर्द चला जाता है!', character: 'amma', emotion: 'happy', context: 'comfort', tags: ['magic', 'touch', 'heal'] },
    { id: 'hi_amma_comfort_005', text: 'बेटा, ग़लती सबसे होती है — बड़ों से भी! ये तो सीखने का मौका है!', character: 'amma', emotion: 'neutral', context: 'comfort', tags: ['mistake', 'learn'] },
    { id: 'hi_amma_comfort_006', text: 'मेरे शेर! हिम्मत रख! तू अपने बाप जैसा बहादुर है!', character: 'amma', emotion: 'determined', context: 'comfort', tags: ['father', 'brave'] },
    { id: 'hi_amma_comfort_007', text: 'आ जा, तेरे लिए गरम-गरम दूध लाती हूँ — सब ठीक हो जाएगा!', character: 'amma', emotion: 'happy', context: 'comfort', tags: ['milk', 'warm', 'care'] },
    { id: 'hi_amma_conflict_003', text: 'मेरे बच्चों को कोई हाथ लगाने की हिम्मत करे! अम्मा को देखना!', character: 'amma', emotion: 'angry', context: 'conflict', tags: ['protect', 'fierce'] },
    { id: 'hi_amma_conflict_004', text: 'कालिया! मेरे बच्चों से दूर रह! एक माँ का ग़ुस्सा मत देख!', character: 'amma', emotion: 'angry', context: 'conflict', tags: ['kaaliya', 'mother_rage'] },
    { id: 'hi_amma_conflict_005', text: 'ये लड़ाई-झगड़ा बंद करो! सब मिलकर बैठो और बात करो!', character: 'amma', emotion: 'sad', context: 'conflict', tags: ['peace', 'talk'] },
    { id: 'hi_amma_moral_003', text: 'बच्चों, अम्मा एक बात बताए? सबसे बड़ी दौलत है — परिवार!', character: 'amma', emotion: 'happy', context: 'moral', tags: ['family', 'wealth'] },
    { id: 'hi_amma_moral_004', text: 'जो दूसरों को खाना खिलाए, उसका घर कभी खाली नहीं होता!', character: 'amma', emotion: 'happy', context: 'moral', tags: ['food', 'generosity'] },
    { id: 'hi_amma_moral_005', text: 'माँ की दुआओं में बहुत ताकत होती है — ये कभी मत भूलना!', character: 'amma', emotion: 'neutral', context: 'moral', tags: ['prayer', 'mother'] },
    { id: 'hi_amma_greeting_003', text: 'उठो बच्चों! सूरज निकल आया! नाश्ता तैयार है!', character: 'amma', emotion: 'happy', context: 'greeting', tags: ['morning', 'breakfast'] },
    { id: 'hi_amma_greeting_004', text: 'बबलू बेटा! फिर से रसोई में? पहले हाथ धो ले!', character: 'amma', emotion: 'happy', context: 'greeting', tags: ['bablu', 'kitchen', 'hygiene'] },
    { id: 'hi_amma_reaction_002', text: 'ये तुम लोगों ने क्या कर दिया! मैं तो डर गई थी!', character: 'amma', emotion: 'scared', context: 'reaction', tags: ['shock', 'worry'] },
    { id: 'hi_amma_reaction_003', text: 'शाबाश मेरे बच्चों! अम्मा को बहुत गर्व है!', character: 'amma', emotion: 'happy', context: 'reaction', tags: ['proud', 'praise'] },
    { id: 'hi_amma_resolution_002', text: 'भगवान का शुक्र है! सब सही सलामत हैं! अब घर चलो!', character: 'amma', emotion: 'happy', context: 'resolution', tags: ['relief', 'home'] },
    { id: 'hi_amma_resolution_003', text: 'आज मैंने देखा — मेरे बच्चे कितने बहादुर हो गए हैं!', character: 'amma', emotion: 'happy', context: 'resolution', tags: ['proud', 'brave'] },
    { id: 'hi_amma_celebration_002', text: 'आज सब मिलकर खाएँगे! मैंने हलवा-पूरी बनाई है!', character: 'amma', emotion: 'happy', context: 'celebration', tags: ['halwa', 'feast'] },
    { id: 'hi_amma_celebration_003', text: 'बबलू, तेरे लिए extra लड्डू रखे हैं! बस ये किसी को बताना मत!', character: 'amma', emotion: 'happy', context: 'celebration', tags: ['bablu', 'laddoo', 'secret'] },
    { id: 'hi_amma_narration_002', text: 'मेरी अम्मा भी कहती थीं — जो बच्चा सच बोलता है, उसे भगवान बचाता है!', character: 'amma', emotion: 'neutral', context: 'narration', tags: ['grandmother', 'truth'] },
    { id: 'hi_amma_farewell_002', text: 'ख़्याल रखना! ठंडा पानी मत पीना! और ज़्यादा धूप में मत खेलना!', character: 'amma', emotion: 'happy', context: 'farewell', tags: ['care', 'health'] },
    { id: 'hi_amma_farewell_003', text: 'जल्दी वापस आना! अम्मा wait करेगी!', character: 'amma', emotion: 'sad', context: 'farewell', tags: ['wait', 'miss'] },
    { id: 'hi_amma_discovery_001', text: 'ये तो तेरे पापा की पुरानी diary है! देख, कितनी ख़ूबसूरत बातें लिखी हैं!', character: 'amma', emotion: 'sad', context: 'discovery', tags: ['father', 'diary', 'memory'] },

    // ─── RAJA (additional lines) ─────────────────────────────────────
    { id: 'hi_raja_conflict_003', text: 'सेनापति! फ़ौज तैयार करो! राज्य पर ख़तरा है!', character: 'raja', emotion: 'angry', context: 'conflict', tags: ['army', 'danger'] },
    { id: 'hi_raja_conflict_004', text: 'ये कालिया बहुत सिर उठा रहा है! इसे रोकना होगा!', character: 'raja', emotion: 'angry', context: 'conflict', tags: ['kaaliya', 'stop'] },
    { id: 'hi_raja_moral_002', text: 'न्याय में देरी, अन्याय है! फ़ैसला अभी होगा!', character: 'raja', emotion: 'determined', context: 'moral', tags: ['justice', 'immediate'] },
    { id: 'hi_raja_moral_003', text: 'राजा की सबसे बड़ी ज़िम्मेदारी है — कमज़ोर की रक्षा करना!', character: 'raja', emotion: 'neutral', context: 'moral', tags: ['protect', 'weak'] },
    { id: 'hi_raja_reaction_002', text: 'बच्चों, तुमने जो किया वो राज्य के इतिहास में लिखा जाएगा!', character: 'raja', emotion: 'happy', context: 'reaction', tags: ['history', 'praise'] },
    { id: 'hi_raja_greeting_002', text: 'आज दरबार में ख़ास मेहमान हैं! इन बहादुर बच्चों का स्वागत करो!', character: 'raja', emotion: 'happy', context: 'greeting', tags: ['court', 'welcome'] },
    { id: 'hi_raja_resolution_002', text: 'इन बच्चों को राज्य का सर्वोच्च सम्मान दिया जाए!', character: 'raja', emotion: 'happy', context: 'resolution', tags: ['honor', 'reward'] },

    // ─── MOTI (additional lines) ─────────────────────────────────────
    { id: 'hi_moti_greeting_002', text: 'भौं भौं भौं! (सबके पास जाकर चाटते हुए)', character: 'moti', emotion: 'happy', context: 'greeting', tags: ['lick', 'love'] },
    { id: 'hi_moti_conflict_002', text: 'गर्र्र! भौं भौं! (कालिया पर भौंकते हुए, बच्चों को बचाते हुए)', character: 'moti', emotion: 'angry', context: 'conflict', tags: ['protect', 'kaaliya'] },
    { id: 'hi_moti_reaction_002', text: 'भौं? (कान खड़े करते हुए, कुछ सुनते हुए)', character: 'moti', emotion: 'thinking', context: 'reaction', tags: ['alert', 'listen'] },
    { id: 'hi_moti_comfort_002', text: 'कूँ कूँ... (गोद में आकर सोते हुए, दिलासा देते हुए)', character: 'moti', emotion: 'sad', context: 'comfort', tags: ['cuddle', 'warm'] },
    { id: 'hi_moti_discovery_002', text: 'भौं भौं भौं! (ज़मीन खोदते हुए, कुछ निकालते हुए)', character: 'moti', emotion: 'happy', context: 'discovery', tags: ['dig', 'find'] },

    // ═══════════════════════════════════════════════════════════════════
    // EXPANSION PACK 2 — additional lines to cross 350+
    // ═══════════════════════════════════════════════════════════════════

    // ─── BABLU (even more food jokes) ────────────────────────────────
    { id: 'hi_bablu_reaction_008', text: 'ये खुशबू... ये halwa है! मेरी नाक कभी ग़लत नहीं होती!', character: 'bablu', emotion: 'happy', context: 'reaction', tags: ['smell', 'halwa', 'food'] },
    { id: 'hi_bablu_reaction_009', text: 'अर्जुन ने कहा "ज़रूरत" और मैंने सुना "ज़ालफ़्रेज़ी"!', character: 'bablu', emotion: 'happy', context: 'reaction', tags: ['mishear', 'food', 'funny'] },
    { id: 'hi_bablu_reaction_010', text: 'मुझे vision आया है — एक ऐसी दुनिया जहाँ समोसे free हों!', character: 'bablu', emotion: 'thinking', context: 'reaction', tags: ['dream', 'samosa', 'food'] },
    { id: 'hi_bablu_conflict_009', text: 'कालिया, तूने मेरा dabba छीना? तू नहीं जानता मैं hungry होकर क्या कर सकता हूँ!', character: 'bablu', emotion: 'angry', context: 'conflict', tags: ['lunchbox', 'angry', 'food'] },
    { id: 'hi_bablu_conflict_010', text: 'भागो! भागो! ... wait, वो side में dhaba है — पहले वहाँ रुकते हैं!', character: 'bablu', emotion: 'scared', context: 'conflict', tags: ['run', 'dhaba', 'food'] },
    { id: 'hi_bablu_moral_005', text: 'मैंने सीखा — खाना share करो, ख़ुशी double हो जाती है! ... triple portion रखो!', character: 'bablu', emotion: 'happy', context: 'moral', tags: ['share', 'food', 'funny'] },
    { id: 'hi_bablu_moral_006', text: 'ज़िंदगी लड्डू जैसी है — बाहर से गोल-गोल, अंदर से sweet!', character: 'bablu', emotion: 'thinking', context: 'moral', tags: ['laddoo', 'life', 'philosophy'] },
    { id: 'hi_bablu_greeting_007', text: 'सुबह का नाश्ता, दोपहर का खाना, शाम की चाय — ये मेरे teen fundamentals हैं!', character: 'bablu', emotion: 'happy', context: 'greeting', tags: ['meals', 'routine', 'food'] },
    { id: 'hi_bablu_greeting_008', text: 'ये adventure ठीक है, लेकिन packed lunch बिना मैं कहीं नहीं जाता!', character: 'bablu', emotion: 'determined', context: 'greeting', tags: ['lunch', 'adventure', 'food'] },
    { id: 'hi_bablu_celebration_004', text: 'मैंने victory dance सीखा है — ये देखो! ... okay, पेट भारी है, बाद में!', character: 'bablu', emotion: 'happy', context: 'celebration', tags: ['dance', 'heavy', 'funny'] },
    { id: 'hi_bablu_discovery_005', text: 'ये तो अम्मा की secret recipe वाली पुरानी kitab है! Gold mine!', character: 'bablu', emotion: 'surprised', context: 'discovery', tags: ['recipe', 'amma', 'food'] },

    // ─── KAALIYA (more villain lines) ────────────────────────────────
    { id: 'hi_kaaliya_conflict_011', text: 'ये दोस्ती-वोस्ती सब ढोंग है! असली दुनिया में ताकत ही सब कुछ है!', character: 'kaaliya', emotion: 'angry', context: 'conflict', tags: ['power', 'cynical'] },
    { id: 'hi_kaaliya_conflict_012', text: 'मैंने plan C भी ready रखा है! तुम लोग soch भी नहीं सकते!', character: 'kaaliya', emotion: 'happy', context: 'conflict', tags: ['plan', 'clever'] },
    { id: 'hi_kaaliya_threat_007', text: 'ये आख़िरी मौक़ा है — मेरे साथ आ जाओ, या फिर...', character: 'kaaliya', emotion: 'angry', context: 'threat', tags: ['ultimatum'] },
    { id: 'hi_kaaliya_threat_008', text: 'तुम्हारा गुरुजी भी तुम्हें नहीं बचा सकता अब!', character: 'kaaliya', emotion: 'angry', context: 'threat', tags: ['guruji', 'helpless'] },
    { id: 'hi_kaaliya_reaction_006', text: 'ये बबलू! फिर खा रहा है! कोई serious नहीं है यहाँ!', character: 'kaaliya', emotion: 'angry', context: 'reaction', tags: ['bablu', 'annoyed'] },
    { id: 'hi_kaaliya_greeting_004', text: 'तो तो तो! देखो कौन आया है! मेरे favourite बच्चे! हा हा!', character: 'kaaliya', emotion: 'happy', context: 'greeting', tags: ['sarcasm', 'mock'] },

    // ─── GURUJI (more wisdom) ────────────────────────────────────────
    { id: 'hi_guruji_moral_015', text: 'कर्मण्येवाधिकारस्ते — कर्म करो, फल की चिंता छोड़ो!', character: 'guruji', emotion: 'neutral', context: 'moral', tags: ['gita', 'karma', 'sanskrit'] },
    { id: 'hi_guruji_moral_016', text: 'जो मिट्टी में मिल जाए वो सोना, जो दिलों में रहे वो इंसान!', character: 'guruji', emotion: 'thinking', context: 'moral', tags: ['proverb', 'human'] },
    { id: 'hi_guruji_moral_017', text: 'विद्या विनयेन शोभते — विद्या विनम्रता से शोभा पाती है!', character: 'guruji', emotion: 'neutral', context: 'moral', tags: ['sanskrit', 'humility', 'education'] },
    { id: 'hi_guruji_conflict_007', text: 'बच्चों, याद रखो — तलवार से ज़्यादा धारदार है शब्द!', character: 'guruji', emotion: 'neutral', context: 'conflict', tags: ['words', 'power'] },
    { id: 'hi_guruji_greeting_005', text: 'ओम! शांति शांति शांति! आओ बच्चों, आज ध्यान से शुरू करते हैं!', character: 'guruji', emotion: 'neutral', context: 'greeting', tags: ['om', 'meditation'] },

    // ─── MEERA (more riddles and reactions) ───────────────────────────
    { id: 'hi_meera_riddle_question_009', text: 'Final round! जिसके पास सिर है, पैर है, पर शरीर नहीं — बताओ?', character: 'meera', emotion: 'happy', context: 'riddle_question', tags: ['riddle', 'coin'] },
    { id: 'hi_meera_riddle_question_010', text: 'ये tricky है — जितना लो उतना बड़ा, जितना दो उतना छोटा? बताओ!', character: 'meera', emotion: 'thinking', context: 'riddle_question', tags: ['riddle', 'pit'] },
    { id: 'hi_meera_riddle_answer_007', text: 'जवाब है — सिक्का! सिक्के के सिर और पैर होते हैं!', character: 'meera', emotion: 'happy', context: 'riddle_answer', tags: ['reveal', 'coin'] },
    { id: 'hi_meera_riddle_answer_008', text: 'Answer है — गड्ढा! जितना मिट्टी निकालो, उतना बड़ा! जितनी भरो, उतना छोटा!', character: 'meera', emotion: 'happy', context: 'riddle_answer', tags: ['reveal', 'pit'] },
    { id: 'hi_meera_conflict_006', text: 'Guys, मैंने calculations कर लिए — हमारे पास exactly 3 minutes हैं!', character: 'meera', emotion: 'determined', context: 'conflict', tags: ['time', 'math'] },
    { id: 'hi_meera_reaction_005', text: 'बबलू, तूने actually कुछ useful कह दिया! मुझे believe नहीं हो रहा!', character: 'meera', emotion: 'surprised', context: 'reaction', tags: ['bablu', 'shock', 'funny'] },

    // ─── ARJUN (more lines) ──────────────────────────────────────────
    { id: 'hi_arjun_conflict_009', text: 'मैं promise करता हूँ — जब तक मैं हूँ, कोई किसी को harm नहीं करेगा!', character: 'arjun', emotion: 'determined', context: 'conflict', tags: ['promise', 'protect'] },
    { id: 'hi_arjun_conflict_010', text: 'ये darkness है, पर हमारी friendship उससे ज़्यादा bright है!', character: 'arjun', emotion: 'determined', context: 'conflict', tags: ['dark', 'friendship', 'light'] },
    { id: 'hi_arjun_celebration_002', text: 'आज हम सबने मिलकर impossible को possible कर दिया!', character: 'arjun', emotion: 'happy', context: 'celebration', tags: ['impossible', 'team'] },
    { id: 'hi_arjun_celebration_003', text: 'Group hug! सब आओ! बबलू तू भी! ... बबलू खा रहा है obviously!', character: 'arjun', emotion: 'happy', context: 'celebration', tags: ['hug', 'bablu', 'funny'] },
    { id: 'hi_arjun_comfort_002', text: 'मीरा, चिंता मत कर! तू सबसे smart है — तू ज़रूर solution ढूँढ लेगी!', character: 'arjun', emotion: 'happy', context: 'comfort', tags: ['meera', 'encourage'] },
    { id: 'hi_arjun_comfort_003', text: 'मोती, good boy! तूने हम सबको बचा लिया! शाबाश!', character: 'arjun', emotion: 'happy', context: 'comfort', tags: ['moti', 'praise'] },

    // ─── AMMA (more lines) ───────────────────────────────────────────
    { id: 'hi_amma_conflict_006', text: 'भगवान, मेरे बच्चों को सलामत रखना! मैं बस यही माँगती हूँ!', character: 'amma', emotion: 'scared', context: 'conflict', tags: ['prayer', 'worry'] },
    { id: 'hi_amma_comfort_008', text: 'तुम अकेले नहीं हो बेटा — पूरा परिवार तेरे साथ है, हमेशा!', character: 'amma', emotion: 'happy', context: 'comfort', tags: ['family', 'together'] },
    { id: 'hi_amma_greeting_005', text: 'अरे! सब एक साथ आ गए! चलो, पहले खाना खा लो!', character: 'amma', emotion: 'happy', context: 'greeting', tags: ['food', 'welcome', 'everyone'] },
    { id: 'hi_amma_moral_006', text: 'जिस घर में respect हो, वो घर temple से कम नहीं!', character: 'amma', emotion: 'neutral', context: 'moral', tags: ['respect', 'home'] },

    // ─── Final batch to cross 350 ────────────────────────────────────
    { id: 'hi_bablu_reaction_011', text: 'मुझे लगता है कालिया को बस अच्छे खाने की ज़रूरत है! Hangry villain!', character: 'bablu', emotion: 'thinking', context: 'reaction', tags: ['kaaliya', 'food', 'funny'] },
    { id: 'hi_bablu_conflict_011', text: 'मैं छुप जाता हूँ — strategically! ये cowardice नहीं, planning है!', character: 'bablu', emotion: 'scared', context: 'conflict', tags: ['hide', 'excuse', 'funny'] },
    { id: 'hi_bablu_discovery_006', text: 'ये berry ज़हरीली है या tasty? एक तरीक़ा है जानने का... *sniff sniff*', character: 'bablu', emotion: 'thinking', context: 'discovery', tags: ['berry', 'food', 'risk'] },
    { id: 'hi_kaaliya_conflict_013', text: 'मैं हारा नहीं हूँ! मैं बस... दूसरी direction में जीत रहा हूँ!', character: 'kaaliya', emotion: 'angry', context: 'conflict', tags: ['denial', 'retreat', 'funny'] },
    { id: 'hi_kaaliya_threat_009', text: 'अगली बार मैं army लेकर आऊँगा! फिर देखना!', character: 'kaaliya', emotion: 'angry', context: 'threat', tags: ['army', 'revenge'] },
    { id: 'hi_guruji_moral_018', text: 'न चोरहार्यं न राजहार्यं — विद्या ऐसा धन है जो कोई चुरा नहीं सकता!', character: 'guruji', emotion: 'neutral', context: 'moral', tags: ['sanskrit', 'education', 'wealth'] },
    { id: 'hi_guruji_moral_019', text: 'सबर का फल मीठा होता है बच्चों — जल्दबाज़ी शैतान का काम है!', character: 'guruji', emotion: 'thinking', context: 'moral', tags: ['patience', 'proverb'] },
    { id: 'hi_meera_riddle_question_011', text: 'Last question! ऐसी कौन सी चीज़ है जो टूटती नहीं, पर बन जाती है?', character: 'meera', emotion: 'happy', context: 'riddle_question', tags: ['riddle', 'promise'] },
    { id: 'hi_meera_riddle_answer_009', text: 'जवाब है — वादा! Promise बनता है, टूटता नहीं — अगर सच्चा हो!', character: 'meera', emotion: 'happy', context: 'riddle_answer', tags: ['reveal', 'promise'] },
    { id: 'hi_arjun_moral_005', text: 'गुरुजी, आपने सिखाया और हमने सीखा — अब हम किसी से नहीं डरते!', character: 'arjun', emotion: 'happy', context: 'moral', tags: ['guruji', 'fearless'] },
  ],
};
