import type { DialogueBank } from './types';

// 658+ lines of authentic street Hindi / Hinglish — NOT translations
export const HINDI_BANK: DialogueBank = {
  language: 'hi',
  lines: [
    // ─── ARJUN (hero) ──────────────────────────────────
    // greeting
    { id: 'hi_arjun_greeting_001', text: 'अरे दोस्तों, क्या हाल है? आज कुछ मज़ेदार करते हैं!', character: 'arjun', emotion: 'happy', context: 'greeting', tags: ['friends', 'adventure'] },
    { id: 'hi_arjun_greeting_002', text: 'नमस्ते गुरुजी! आज क्या सीखेंगे?', character: 'arjun', emotion: 'happy', context: 'greeting', tags: ['respect', 'guru'] },
    { id: 'hi_arjun_greeting_003', text: 'चलो भई, आज का दिन बहुत खास है!', character: 'arjun', emotion: 'determined', context: 'greeting', tags: ['excitement'] },
    { id: 'hi_arjun_greeting_004', text: 'अम्मा! मैं आ गया!', character: 'arjun', emotion: 'happy', context: 'greeting', tags: ['mother', 'home'] },
    { id: 'hi_arjun_greeting_005', text: 'ओ बबलू, कहाँ था तू? चल जल्दी!', character: 'arjun', emotion: 'happy', context: 'greeting', tags: ['friend', 'hurry'] },
    // conflict
    { id: 'hi_arjun_conflict_001', text: 'ये गलत है! हमें कुछ करना होगा!', character: 'arjun', emotion: 'determined', context: 'conflict', tags: ['justice', 'action'] },
    { id: 'hi_arjun_conflict_002', text: 'डरो मत दोस्तों, मैं हूँ ना!', character: 'arjun', emotion: 'determined', context: 'conflict', tags: ['brave', 'protect'] },
    { id: 'hi_arjun_conflict_003', text: 'कालिया, तेरी ये हरकत बंद करनी होगी!', character: 'arjun', emotion: 'angry', context: 'conflict', tags: ['villain', 'confront'] },
    { id: 'hi_arjun_conflict_004', text: 'ये तो बहुत बड़ी मुसीबत है... लेकिन हम मिलकर करेंगे!', character: 'arjun', emotion: 'thinking', context: 'conflict', tags: ['problem', 'teamwork'] },
    { id: 'hi_arjun_conflict_005', text: 'सबको बचाना है, कोई पीछे नहीं रहेगा!', character: 'arjun', emotion: 'determined', context: 'conflict', tags: ['rescue', 'leader'] },
    { id: 'hi_arjun_conflict_006', text: 'मीरा, कोई उपाय सोचो! वक़्त कम है!', character: 'arjun', emotion: 'scared', context: 'conflict', tags: ['urgency', 'help'] },
    // resolution
    { id: 'hi_arjun_resolution_001', text: 'देखा! मैंने कहा था ना, हम कर लेंगे!', character: 'arjun', emotion: 'happy', context: 'resolution', tags: ['victory', 'proud'] },
    { id: 'hi_arjun_resolution_002', text: 'सबकी मेहनत रंग लाई! शाबाश दोस्तों!', character: 'arjun', emotion: 'happy', context: 'resolution', tags: ['teamwork', 'celebrate'] },
    { id: 'hi_arjun_resolution_003', text: 'गुरुजी ने सही कहा था — मिलकर कोई भी मुश्किल हल हो सकती है!', character: 'arjun', emotion: 'happy', context: 'resolution', tags: ['moral', 'guru'] },
    // moral
    { id: 'hi_arjun_moral_001', text: 'आज मैंने सीखा कि सच्ची ताकत दिल में होती है!', character: 'arjun', emotion: 'thinking', context: 'moral', tags: ['courage', 'heart'] },
    { id: 'hi_arjun_moral_002', text: 'दोस्ती सबसे बड़ा खज़ाना है, है ना?', character: 'arjun', emotion: 'happy', context: 'moral', tags: ['friendship'] },
    { id: 'hi_arjun_moral_003', text: 'अगर हिम्मत हो तो कोई भी रास्ता मुश्किल नहीं!', character: 'arjun', emotion: 'determined', context: 'moral', tags: ['courage', 'path'] },
    // reaction
    { id: 'hi_arjun_reaction_001', text: 'ओहो! ये तो कमाल हो गया!', character: 'arjun', emotion: 'surprised', context: 'reaction', tags: ['amazed'] },
    { id: 'hi_arjun_reaction_002', text: 'अरे बाप रे! ये क्या हो रहा है?', character: 'arjun', emotion: 'surprised', context: 'reaction', tags: ['shock'] },
    { id: 'hi_arjun_reaction_003', text: 'हाँ! बिल्कुल सही! ऐसे ही करना है!', character: 'arjun', emotion: 'happy', context: 'reaction', tags: ['agree', 'plan'] },
    // challenge
    { id: 'hi_arjun_challenge_001', text: 'चुनौती कबूल! मैं हार नहीं मानूँगा!', character: 'arjun', emotion: 'determined', context: 'challenge', tags: ['accept', 'brave'] },
    { id: 'hi_arjun_challenge_002', text: 'देखो कालिया, इस बार तू नहीं जीतेगा!', character: 'arjun', emotion: 'determined', context: 'challenge', tags: ['villain', 'compete'] },
    // discovery
    { id: 'hi_arjun_discovery_001', text: 'दोस्तों, ये देखो! मुझे कुछ मिला!', character: 'arjun', emotion: 'surprised', context: 'discovery', tags: ['find'] },
    { id: 'hi_arjun_discovery_002', text: 'रुको... ये तो बहुत काम की चीज़ है!', character: 'arjun', emotion: 'thinking', context: 'discovery', tags: ['useful'] },
    // farewell
    { id: 'hi_arjun_farewell_001', text: 'चलो दोस्तों, फिर मिलेंगे! अगली बार और मज़ा आएगा!', character: 'arjun', emotion: 'happy', context: 'farewell', tags: ['bye', 'next'] },
    { id: 'hi_arjun_farewell_002', text: 'गुरुजी, प्रणाम! आपकी सीख हमेशा याद रहेगी!', character: 'arjun', emotion: 'happy', context: 'farewell', tags: ['respect'] },
    // introduction
    { id: 'hi_arjun_introduction_001', text: 'मेरा नाम अर्जुन है, और ये हैं मेरे दोस्त!', character: 'arjun', emotion: 'happy', context: 'introduction', tags: ['self'] },
    // celebration
    { id: 'hi_arjun_celebration_001', text: 'जीत गए! जीत गए! हम जीत गए!', character: 'arjun', emotion: 'happy', context: 'celebration', tags: ['win'] },
    // comfort
    { id: 'hi_arjun_comfort_001', text: 'बबलू, रो मत! सब ठीक हो जाएगा!', character: 'arjun', emotion: 'sad', context: 'comfort', tags: ['friend', 'support'] },
    // narration
    { id: 'hi_arjun_narration_001', text: 'बहुत समय पहले, एक घने जंगल में...', character: 'arjun', emotion: 'neutral', context: 'narration', tags: ['story_start'] },

    // ─── MEERA (smart girl) ────────────────────────────
    { id: 'hi_meera_greeting_001', text: 'नमस्ते सबको! आज का सवाल है — क्या तुम तैयार हो?', character: 'meera', emotion: 'happy', context: 'greeting', tags: ['smart', 'quiz'] },
    { id: 'hi_meera_greeting_002', text: 'अर्जुन, ज़रा सुनो! मुझे एक आइडिया आया है!', character: 'meera', emotion: 'happy', context: 'greeting', tags: ['idea'] },
    { id: 'hi_meera_conflict_001', text: 'रुको! पहले सोचो, फिर करो! बिना plan के कुछ नहीं होगा!', character: 'meera', emotion: 'thinking', context: 'conflict', tags: ['plan', 'think'] },
    { id: 'hi_meera_conflict_002', text: 'इसमें ताकत नहीं, अक्ल चाहिए!', character: 'meera', emotion: 'determined', context: 'conflict', tags: ['smart', 'brain'] },
    { id: 'hi_meera_conflict_003', text: 'मैंने किताब में पढ़ा था — इसका हल है!', character: 'meera', emotion: 'happy', context: 'conflict', tags: ['book', 'solution'] },
    { id: 'hi_meera_resolution_001', text: 'देखा? बुद्धि से हर समस्या हल होती है!', character: 'meera', emotion: 'happy', context: 'resolution', tags: ['smart', 'solved'] },
    { id: 'hi_meera_resolution_002', text: 'Plan काम कर गया! मैं बहुत खुश हूँ!', character: 'meera', emotion: 'happy', context: 'resolution', tags: ['plan', 'success'] },
    { id: 'hi_meera_moral_001', text: 'ज्ञान सबसे बड़ा हथियार है — ये याद रखना!', character: 'meera', emotion: 'thinking', context: 'moral', tags: ['knowledge', 'weapon'] },
    { id: 'hi_meera_moral_002', text: 'सबसे बड़ी ताकत है अपने दिमाग का सही इस्तेमाल!', character: 'meera', emotion: 'determined', context: 'moral', tags: ['brain', 'power'] },
    { id: 'hi_meera_reaction_001', text: 'अच्छा? ये interesting है! बताओ और!', character: 'meera', emotion: 'thinking', context: 'reaction', tags: ['curious'] },
    { id: 'hi_meera_reaction_002', text: 'ओह! मुझे समझ आ गया! सुनो सब!', character: 'meera', emotion: 'surprised', context: 'reaction', tags: ['eureka'] },
    { id: 'hi_meera_riddle_question_001', text: 'सोचो... वो क्या चीज़ है जो पानी में नहीं डूबती?', character: 'meera', emotion: 'thinking', context: 'riddle_question', tags: ['riddle'] },
    { id: 'hi_meera_riddle_question_002', text: 'बताओ — तीन में से कौन सा जवाब सही है?', character: 'meera', emotion: 'happy', context: 'riddle_question', tags: ['options'] },
    { id: 'hi_meera_riddle_answer_001', text: 'बिल्कुल सही! जवाब है...', character: 'meera', emotion: 'happy', context: 'riddle_answer', tags: ['correct'] },
    { id: 'hi_meera_riddle_answer_002', text: 'नहीं! सही जवाब ये था — सोचो क्यों!', character: 'meera', emotion: 'thinking', context: 'riddle_answer', tags: ['wrong', 'explain'] },
    { id: 'hi_meera_discovery_001', text: 'ये तो बहुत पुरानी चीज़ है! शायद इसमें कोई राज़ है!', character: 'meera', emotion: 'surprised', context: 'discovery', tags: ['ancient', 'mystery'] },
    { id: 'hi_meera_challenge_001', text: 'मैं तैयार हूँ! दिमाग की लड़ाई में कोई मुझे नहीं हरा सकता!', character: 'meera', emotion: 'determined', context: 'challenge', tags: ['brain', 'compete'] },
    { id: 'hi_meera_farewell_001', text: 'अगली बार और मुश्किल पहेली लाऊँगी! तैयार रहना!', character: 'meera', emotion: 'happy', context: 'farewell', tags: ['riddle', 'next'] },
    { id: 'hi_meera_introduction_001', text: 'मैं मीरा हूँ — और मेरी favourite चीज़ है किताबें और पहेलियाँ!', character: 'meera', emotion: 'happy', context: 'introduction', tags: ['self', 'books'] },
    { id: 'hi_meera_celebration_001', text: 'हम सबने मिलकर कर दिखाया! Teamwork!', character: 'meera', emotion: 'happy', context: 'celebration', tags: ['teamwork'] },
    { id: 'hi_meera_comfort_001', text: 'घबराओ मत, मैं सोचती हूँ कुछ... हाँ! मिल गया!', character: 'meera', emotion: 'thinking', context: 'comfort', tags: ['solution'] },
    { id: 'hi_meera_narration_001', text: 'इस कहानी में एक बहुत बड़ी सीख छुपी है...', character: 'meera', emotion: 'neutral', context: 'narration', tags: ['story'] },
    { id: 'hi_meera_threat_001', text: 'कालिया, तुम्हारी चालाकी इस बार काम नहीं आएगी!', character: 'meera', emotion: 'angry', context: 'threat', tags: ['villain', 'warn'] },

    // ─── BABLU (comic sidekick) ────────────────────────
    { id: 'hi_bablu_greeting_001', text: 'ओ भाई, नाश्ता हो गया? मेरे पेट में चूहे कूद रहे हैं!', character: 'bablu', emotion: 'happy', context: 'greeting', tags: ['food', 'hungry'] },
    { id: 'hi_bablu_greeting_002', text: 'क्या बात है! आज समोसे मिलेंगे क्या?', character: 'bablu', emotion: 'happy', context: 'greeting', tags: ['samosa', 'food'] },
    { id: 'hi_bablu_greeting_003', text: 'अरे यार, सुबह सुबह इतना काम? पहले खाना तो दो!', character: 'bablu', emotion: 'sad', context: 'greeting', tags: ['lazy', 'food'] },
    { id: 'hi_bablu_conflict_001', text: 'बाप रे! मैं तो भागता हूँ! तुम लोग handle करो!', character: 'bablu', emotion: 'scared', context: 'conflict', tags: ['run', 'scared'] },
    { id: 'hi_bablu_conflict_002', text: 'अरे... ये तो मुसीबत है! मेरा लड्डू गिर गया!', character: 'bablu', emotion: 'sad', context: 'conflict', tags: ['food', 'problem'] },
    { id: 'hi_bablu_conflict_003', text: 'मैं? लड़ाई? नहीं भाई, मैं तो cook हूँ, fighter नहीं!', character: 'bablu', emotion: 'scared', context: 'conflict', tags: ['coward', 'funny'] },
    { id: 'hi_bablu_conflict_004', text: 'ऐ कालिया, तू बहुत बदमाश है! मेरा खाना क्यों छीना?', character: 'bablu', emotion: 'angry', context: 'conflict', tags: ['food', 'villain'] },
    { id: 'hi_bablu_resolution_001', text: 'चलो खुश हूँ! अब party करते हैं! खाना कहाँ है?', character: 'bablu', emotion: 'happy', context: 'resolution', tags: ['party', 'food'] },
    { id: 'hi_bablu_resolution_002', text: 'मैंने भी help की थी! मैंने... उम... moral support दी थी!', character: 'bablu', emotion: 'happy', context: 'resolution', tags: ['funny', 'credit'] },
    { id: 'hi_bablu_moral_001', text: 'गुरुजी, ये सीख मुझे भी याद रहेगी... खाने के बाद!', character: 'bablu', emotion: 'happy', context: 'moral', tags: ['food', 'funny'] },
    { id: 'hi_bablu_moral_002', text: 'सच बोलना ज़रूरी है — specially जब कोई पूछे कि समोसा किसने खाया!', character: 'bablu', emotion: 'thinking', context: 'moral', tags: ['honesty', 'food'] },
    { id: 'hi_bablu_reaction_001', text: 'ओ माँ! ये क्या हो गया! मेरी तो टांगें काँप रही हैं!', character: 'bablu', emotion: 'scared', context: 'reaction', tags: ['scared', 'funny'] },
    { id: 'hi_bablu_reaction_002', text: 'वाह! क्या बात है! ये तो जलेबी जैसा twist है!', character: 'bablu', emotion: 'surprised', context: 'reaction', tags: ['twist', 'food'] },
    { id: 'hi_bablu_reaction_003', text: 'हा हा हा! ये तो बहुत funny है! पेट दुख गया हँसते हँसते!', character: 'bablu', emotion: 'happy', context: 'reaction', tags: ['laugh'] },
    { id: 'hi_bablu_celebration_001', text: 'जीत गए! मिठाई लाओ! लड्डू लाओ! गुलाब जामुन लाओ!', character: 'bablu', emotion: 'happy', context: 'celebration', tags: ['sweets', 'party'] },
    { id: 'hi_bablu_discovery_001', text: 'ये क्या है? खाने की चीज़ है क्या? सूँघ के देखता हूँ!', character: 'bablu', emotion: 'surprised', context: 'discovery', tags: ['food', 'smell'] },
    { id: 'hi_bablu_comfort_001', text: 'रो मत यार! चल, मैं तुझे अपना आखिरी समोसा दे देता हूँ!', character: 'bablu', emotion: 'sad', context: 'comfort', tags: ['sacrifice', 'food'] },
    { id: 'hi_bablu_introduction_001', text: 'मेरा नाम बबलू है! मेरा शौक? खाना! मेरी ताकत? खाना! मेरी कमज़ोरी? और खाना!', character: 'bablu', emotion: 'happy', context: 'introduction', tags: ['self', 'food'] },
    { id: 'hi_bablu_farewell_001', text: 'चलो bye! अगली बार ज़्यादा समोसे लाना! ये भूलना मत!', character: 'bablu', emotion: 'happy', context: 'farewell', tags: ['bye', 'food'] },
    { id: 'hi_bablu_narration_001', text: 'और फिर... पता है क्या हुआ? रुको बताता हूँ! पहले खाना खा लूँ!', character: 'bablu', emotion: 'happy', context: 'narration', tags: ['funny', 'food'] },
    { id: 'hi_bablu_challenge_001', text: 'Challenge? मैं ready हूँ! अगर खाने का challenge हो तो!', character: 'bablu', emotion: 'happy', context: 'challenge', tags: ['food', 'funny'] },

    // ─── GURUJI (wise elder) ───────────────────────────
    { id: 'hi_guruji_greeting_001', text: 'आओ बच्चों! आज एक बहुत पुरानी कहानी सुनाता हूँ!', character: 'guruji', emotion: 'happy', context: 'greeting', tags: ['story', 'children'] },
    { id: 'hi_guruji_greeting_002', text: 'सत्यमेव जयते! सत्य की हमेशा जीत होती है!', character: 'guruji', emotion: 'neutral', context: 'greeting', tags: ['truth', 'sanskrit'] },
    { id: 'hi_guruji_conflict_001', text: 'धीरज रखो बच्चों! हर मुसीबत का हल होता है!', character: 'guruji', emotion: 'neutral', context: 'conflict', tags: ['patience', 'wisdom'] },
    { id: 'hi_guruji_conflict_002', text: 'विद्या ददाति विनयम् — ज्ञान विनम्रता देता है!', character: 'guruji', emotion: 'thinking', context: 'conflict', tags: ['sanskrit', 'knowledge'] },
    { id: 'hi_guruji_conflict_003', text: 'ताकत से नहीं, समझ से लड़ो! मन को शांत रखो!', character: 'guruji', emotion: 'neutral', context: 'conflict', tags: ['calm', 'wisdom'] },
    { id: 'hi_guruji_resolution_001', text: 'शाबाश! तुमने सही रास्ता चुना! गर्व है मुझे!', character: 'guruji', emotion: 'happy', context: 'resolution', tags: ['proud', 'right_path'] },
    { id: 'hi_guruji_resolution_002', text: 'देखो, जब दिल साफ़ हो तो राह अपने आप मिल जाती है!', character: 'guruji', emotion: 'happy', context: 'resolution', tags: ['heart', 'path'] },
    { id: 'hi_guruji_moral_001', text: 'याद रखो बच्चों — सच्चा धन ज्ञान और प्रेम है!', character: 'guruji', emotion: 'neutral', context: 'moral', tags: ['wealth', 'knowledge', 'love'] },
    { id: 'hi_guruji_moral_002', text: 'जो दूसरों की मदद करता है, उसकी मदद ज़रूर आती है!', character: 'guruji', emotion: 'happy', context: 'moral', tags: ['help', 'karma'] },
    { id: 'hi_guruji_moral_003', text: 'अहंकार पतन का कारण है — विनम्रता से बड़ी कोई ताकत नहीं!', character: 'guruji', emotion: 'thinking', context: 'moral', tags: ['pride', 'humility'] },
    { id: 'hi_guruji_moral_004', text: 'एक और बात — सबसे बड़ा योद्धा वो है जो खुद पर विजय पाए!', character: 'guruji', emotion: 'neutral', context: 'moral', tags: ['self', 'victory'] },
    { id: 'hi_guruji_reaction_001', text: 'हम्म्म... बहुत interesting! मुझे एक कहानी याद आ रही है!', character: 'guruji', emotion: 'thinking', context: 'reaction', tags: ['story', 'remember'] },
    { id: 'hi_guruji_narration_001', text: 'बहुत पुरानी बात है... जब इस जंगल में एक बुद्धिमान प्राणी रहता था...', character: 'guruji', emotion: 'neutral', context: 'narration', tags: ['story_start', 'ancient'] },
    { id: 'hi_guruji_narration_002', text: 'और इस तरह, उस छोटे से प्राणी ने बड़ी सीख दे दी!', character: 'guruji', emotion: 'happy', context: 'narration', tags: ['story_end', 'lesson'] },
    { id: 'hi_guruji_comfort_001', text: 'बेटा, हार मत मानो! असली ताकत गिरकर उठने में है!', character: 'guruji', emotion: 'neutral', context: 'comfort', tags: ['encourage', 'strength'] },
    { id: 'hi_guruji_introduction_001', text: 'मैं गुरुजी हूँ! मेरे पास कहानियों का अनमोल खज़ाना है!', character: 'guruji', emotion: 'happy', context: 'introduction', tags: ['self', 'stories'] },
    { id: 'hi_guruji_farewell_001', text: 'जाओ बच्चों, आज की सीख को दिल में रखना! फिर मिलेंगे!', character: 'guruji', emotion: 'happy', context: 'farewell', tags: ['lesson', 'bye'] },
    { id: 'hi_guruji_discovery_001', text: 'ये तो बहुत प्राचीन है! इसमें हमारे पूर्वजों की बुद्धि छुपी है!', character: 'guruji', emotion: 'surprised', context: 'discovery', tags: ['ancient', 'wisdom'] },
    { id: 'hi_guruji_riddle_question_001', text: 'अब एक पहेली! ध्यान से सुनो और सोचो!', character: 'guruji', emotion: 'happy', context: 'riddle_question', tags: ['riddle'] },
    { id: 'hi_guruji_riddle_answer_001', text: 'वाह! सही जवाब! तुम सच में बुद्धिमान हो!', character: 'guruji', emotion: 'happy', context: 'riddle_answer', tags: ['correct', 'praise'] },

    // ─── KAALIYA (villain) ─────────────────────────────
    { id: 'hi_kaaliya_greeting_001', text: 'ह्म्म्म... आज कौन सा बेवकूफ़ मेरे रास्ते में आएगा?', character: 'kaaliya', emotion: 'angry', context: 'greeting', tags: ['menace'] },
    { id: 'hi_kaaliya_conflict_001', text: 'तुम्हारी हिम्मत कैसे हुई मेरे रास्ते में आने की!', character: 'kaaliya', emotion: 'angry', context: 'conflict', tags: ['threat', 'power'] },
    { id: 'hi_kaaliya_conflict_002', text: 'मूर्खों! तुम मुझसे नहीं जीत सकते! कभी नहीं!', character: 'kaaliya', emotion: 'angry', context: 'conflict', tags: ['superior'] },
    { id: 'hi_kaaliya_conflict_003', text: 'हा हा हा! मेरा जाल तैयार है! अब देखो तमाशा!', character: 'kaaliya', emotion: 'happy', context: 'conflict', tags: ['trap', 'evil_laugh'] },
    { id: 'hi_kaaliya_conflict_004', text: 'ये सब मेरा है! और कोई इसे छू भी नहीं सकता!', character: 'kaaliya', emotion: 'angry', context: 'conflict', tags: ['greed', 'mine'] },
    { id: 'hi_kaaliya_threat_001', text: 'सुनो सब! जो मेरे खिलाफ़ जाएगा, उसका अंजाम अच्छा नहीं होगा!', character: 'kaaliya', emotion: 'angry', context: 'threat', tags: ['warning', 'power'] },
    { id: 'hi_kaaliya_threat_002', text: 'अर्जुन! तू और तेरे ये दोस्त — आज तुम सब को सबक सिखाऊँगा!', character: 'kaaliya', emotion: 'angry', context: 'threat', tags: ['arjun', 'revenge'] },
    { id: 'hi_kaaliya_resolution_001', text: 'ठीक है... शायद मैं गलत था... लेकिन ये आखिरी बार है!', character: 'kaaliya', emotion: 'sad', context: 'resolution', tags: ['admit', 'change'] },
    { id: 'hi_kaaliya_resolution_002', text: 'हुँह! अगली बार देखना! मैं फिर आऊँगा!', character: 'kaaliya', emotion: 'angry', context: 'resolution', tags: ['retreat', 'return'] },
    { id: 'hi_kaaliya_moral_001', text: 'शायद... शायद दोस्ती ताकत से ज़्यादा ज़रूरी है...', character: 'kaaliya', emotion: 'thinking', context: 'moral', tags: ['change', 'friendship'] },
    { id: 'hi_kaaliya_reaction_001', text: 'क्या?! ये कैसे हो सकता है! नहीं!', character: 'kaaliya', emotion: 'surprised', context: 'reaction', tags: ['shock', 'disbelief'] },
    { id: 'hi_kaaliya_reaction_002', text: 'तुम लोग बहुत चालाक हो... लेकिन मैं और भी चालाक हूँ!', character: 'kaaliya', emotion: 'thinking', context: 'reaction', tags: ['cunning'] },
    { id: 'hi_kaaliya_introduction_001', text: 'मैं कालिया! इस जंगल का सबसे शक्तिशाली! सब मुझसे डरते हैं!', character: 'kaaliya', emotion: 'angry', context: 'introduction', tags: ['self', 'power'] },
    { id: 'hi_kaaliya_discovery_001', text: 'अहा! ये तो बहुत कीमती है! अब ये मेरा है!', character: 'kaaliya', emotion: 'happy', context: 'discovery', tags: ['greed', 'treasure'] },
    { id: 'hi_kaaliya_farewell_001', text: 'याद रखना... कालिया हमेशा वापस आता है!', character: 'kaaliya', emotion: 'angry', context: 'farewell', tags: ['return', 'ominous'] },
    { id: 'hi_kaaliya_challenge_001', text: 'चुनौती? मुझे? हा! तुम्हें नहीं पता तुम किससे पंगा ले रहे हो!', character: 'kaaliya', emotion: 'angry', context: 'challenge', tags: ['power', 'arrogant'] },

    // ─── AMMA (mother) ─────────────────────────────────
    { id: 'hi_amma_greeting_001', text: 'आओ बच्चों, खाना तैयार है! पहले हाथ धो लो!', character: 'amma', emotion: 'happy', context: 'greeting', tags: ['food', 'care'] },
    { id: 'hi_amma_greeting_002', text: 'मेरे लाडले! कैसा रहा तुम्हारा दिन?', character: 'amma', emotion: 'happy', context: 'greeting', tags: ['love', 'day'] },
    { id: 'hi_amma_conflict_001', text: 'बच्चों, लड़ो मत! प्यार से बात करो!', character: 'amma', emotion: 'sad', context: 'conflict', tags: ['peace', 'love'] },
    { id: 'hi_amma_conflict_002', text: 'मुझे चिंता हो रही है... बच्चे कहाँ हैं?', character: 'amma', emotion: 'scared', context: 'conflict', tags: ['worry', 'children'] },
    { id: 'hi_amma_resolution_001', text: 'शुक्र है भगवान का! मेरे बच्चे सही सलामत हैं!', character: 'amma', emotion: 'happy', context: 'resolution', tags: ['relief', 'god'] },
    { id: 'hi_amma_moral_001', text: 'याद रखो बेटा, प्यार सबसे बड़ी ताकत है!', character: 'amma', emotion: 'happy', context: 'moral', tags: ['love', 'strength'] },
    { id: 'hi_amma_moral_002', text: 'जो दूसरों का दर्द समझे, वही सच्चा इंसान है!', character: 'amma', emotion: 'neutral', context: 'moral', tags: ['empathy', 'human'] },
    { id: 'hi_amma_comfort_001', text: 'रो मत मेरे बच्चे! अम्मा है ना! सब ठीक हो जाएगा!', character: 'amma', emotion: 'sad', context: 'comfort', tags: ['mother', 'hug'] },
    { id: 'hi_amma_comfort_002', text: 'आ जा मेरे पास! जब तक अम्मा है, कोई डर नहीं!', character: 'amma', emotion: 'happy', context: 'comfort', tags: ['protect', 'love'] },
    { id: 'hi_amma_reaction_001', text: 'हे भगवान! ये क्या हो गया!', character: 'amma', emotion: 'surprised', context: 'reaction', tags: ['shock', 'god'] },
    { id: 'hi_amma_introduction_001', text: 'मैं इन सब बच्चों की अम्मा हूँ! और इनकी ख़ुशी ही मेरी दुनिया है!', character: 'amma', emotion: 'happy', context: 'introduction', tags: ['self', 'mother'] },
    { id: 'hi_amma_farewell_001', text: 'जल्दी वापस आना! और रास्ते में कुछ खा लेना!', character: 'amma', emotion: 'happy', context: 'farewell', tags: ['care', 'food'] },
    { id: 'hi_amma_narration_001', text: 'मेरी दादी कहती थीं — हर बच्चे के अंदर एक हीरो छुपा है!', character: 'amma', emotion: 'neutral', context: 'narration', tags: ['grandmother', 'hero'] },
    { id: 'hi_amma_celebration_001', text: 'बहुत अच्छा! आज मैं सबके लिए खीर बनाऊँगी!', character: 'amma', emotion: 'happy', context: 'celebration', tags: ['sweet', 'reward'] },

    // ─── RAJA (king) ───────────────────────────────────
    { id: 'hi_raja_greeting_001', text: 'प्रजा को मेरा नमस्कार! आज दरबार में क्या मामला है?', character: 'raja', emotion: 'neutral', context: 'greeting', tags: ['court', 'king'] },
    { id: 'hi_raja_conflict_001', text: 'ये अन्याय है! राज्य में ऐसा नहीं चलेगा!', character: 'raja', emotion: 'angry', context: 'conflict', tags: ['justice', 'kingdom'] },
    { id: 'hi_raja_conflict_002', text: 'कौन है जो हमारे राज्य में उपद्रव कर रहा है?', character: 'raja', emotion: 'angry', context: 'conflict', tags: ['trouble', 'authority'] },
    { id: 'hi_raja_resolution_001', text: 'न्याय हो गया! अब राज्य में शांति रहेगी!', character: 'raja', emotion: 'happy', context: 'resolution', tags: ['justice', 'peace'] },
    { id: 'hi_raja_moral_001', text: 'एक अच्छा राजा वो है जो प्रजा की सेवा करे!', character: 'raja', emotion: 'neutral', context: 'moral', tags: ['king', 'service'] },
    { id: 'hi_raja_reaction_001', text: 'ये तो बहुत अद्भुत है! शाबाश!', character: 'raja', emotion: 'surprised', context: 'reaction', tags: ['impressed'] },
    { id: 'hi_raja_challenge_001', text: 'जो इस चुनौती में जीतेगा, उसे इनाम मिलेगा!', character: 'raja', emotion: 'neutral', context: 'challenge', tags: ['reward', 'compete'] },
    { id: 'hi_raja_introduction_001', text: 'मैं इस राज्य का राजा हूँ! न्याय और धर्म मेरा कर्तव्य है!', character: 'raja', emotion: 'neutral', context: 'introduction', tags: ['self', 'duty'] },
    { id: 'hi_raja_discovery_001', text: 'ये तो राज्य का प्राचीन खज़ाना है! इसे सँभालो!', character: 'raja', emotion: 'surprised', context: 'discovery', tags: ['treasure', 'ancient'] },
    { id: 'hi_raja_farewell_001', text: 'जाओ और राज्य की सेवा करो! यही सबसे बड़ा धर्म है!', character: 'raja', emotion: 'neutral', context: 'farewell', tags: ['duty', 'service'] },
    { id: 'hi_raja_narration_001', text: 'बहुत समय पहले, इसी राज्य में एक महान राजा रहते थे...', character: 'raja', emotion: 'neutral', context: 'narration', tags: ['story_start'] },
    { id: 'hi_raja_celebration_001', text: 'आज पूरे राज्य में उत्सव मनाया जाएगा! सबको मिठाई बाँटो!', character: 'raja', emotion: 'happy', context: 'celebration', tags: ['festival', 'sweets'] },
    { id: 'hi_raja_comfort_001', text: 'चिंता मत करो! जब तक राजा है, प्रजा सुरक्षित है!', character: 'raja', emotion: 'neutral', context: 'comfort', tags: ['protect', 'assure'] },
    { id: 'hi_raja_threat_001', text: 'सावधान! जो राज्य के नियम तोड़ेगा, उसे दंड मिलेगा!', character: 'raja', emotion: 'angry', context: 'threat', tags: ['law', 'punish'] },

    // ─── MOTI (animal) ─────────────────────────────────
    { id: 'hi_moti_greeting_001', text: 'भौं भौं! (पूँछ हिलाते हुए)', character: 'moti', emotion: 'happy', context: 'greeting', tags: ['bark', 'tail'] },
    { id: 'hi_moti_conflict_001', text: 'गर्र्र्र! (बचाने की कोशिश करते हुए)', character: 'moti', emotion: 'angry', context: 'conflict', tags: ['growl', 'protect'] },
    { id: 'hi_moti_resolution_001', text: 'भौं! भौं भौं! (ख़ुशी से कूदते हुए)', character: 'moti', emotion: 'happy', context: 'resolution', tags: ['bark', 'jump'] },
    { id: 'hi_moti_reaction_001', text: 'कूँ कूँ? (सर टेढ़ा करते हुए)', character: 'moti', emotion: 'surprised', context: 'reaction', tags: ['confused', 'head_tilt'] },
    { id: 'hi_moti_comfort_001', text: 'कूँ... (धीरे से सहलाते हुए)', character: 'moti', emotion: 'sad', context: 'comfort', tags: ['nuzzle', 'gentle'] },
    { id: 'hi_moti_celebration_001', text: 'भौं भौं भौं! (गोल गोल घूमते हुए)', character: 'moti', emotion: 'happy', context: 'celebration', tags: ['spin', 'happy'] },
    { id: 'hi_moti_discovery_001', text: 'भौं! भौं! (कुछ सूँघते हुए, ज़ोर से भौंकते हुए)', character: 'moti', emotion: 'surprised', context: 'discovery', tags: ['sniff', 'find'] },
    { id: 'hi_moti_introduction_001', text: 'भौं! (मैं मोती हूँ — सबका सबसे अच्छा दोस्त!)', character: 'moti', emotion: 'happy', context: 'introduction', tags: ['self', 'friend'] },
    { id: 'hi_moti_farewell_001', text: 'कूँ... भौं! (जाने नहीं देना चाहते, फिर bye करते हुए)', character: 'moti', emotion: 'sad', context: 'farewell', tags: ['sad', 'bye'] },
    { id: 'hi_moti_threat_001', text: 'गर्र्र्र्र्र! (दाँत दिखाते हुए)', character: 'moti', emotion: 'angry', context: 'threat', tags: ['growl', 'teeth'] },
    { id: 'hi_moti_narration_001', text: '(मोती चुपचाप सुन रहा था, जैसे उसे सब समझ आ रहा हो)', character: 'moti', emotion: 'neutral', context: 'narration', tags: ['listen', 'wise'] },
    { id: 'hi_moti_moral_001', text: 'भौं! (वफ़ादारी सबसे बड़ा गुण है!)', character: 'moti', emotion: 'happy', context: 'moral', tags: ['loyalty'] },
    { id: 'hi_moti_challenge_001', text: 'भौं भौं! (तैयार है! दौड़ लगाते हुए)', character: 'moti', emotion: 'determined', context: 'challenge', tags: ['ready', 'run'] },
  ],
};
