import type { DialogueBank } from './types';

// 361+ lines of authentic Kannada — Bangalore + North Karnataka mix
export const KANNADA_BANK: DialogueBank = {
  language: 'kn',
  lines: [
    // ─── ARJUN ─────────────────────────────────────────
    { id: 'kn_arjun_greeting_001', text: 'ಏನ್ ಮಾಡ್ತಿದ್ದೀರಾ? ಇವತ್ತು ಏನಾದ್ರೂ ಫನ್ ಮಾಡೋಣ!', character: 'arjun', emotion: 'happy', context: 'greeting', tags: ['friends'] },
    { id: 'kn_arjun_greeting_002', text: 'ಗುರುಜೀ ನಮಸ್ಕಾರ! ಇವತ್ತು ಏನ್ ಕಲಿಯೋಣ?', character: 'arjun', emotion: 'happy', context: 'greeting', tags: ['guru'] },
    { id: 'kn_arjun_greeting_003', text: 'ಅಮ್ಮಾ! ನಾನು ಬಂದೆ!', character: 'arjun', emotion: 'happy', context: 'greeting', tags: ['mother'] },
    { id: 'kn_arjun_conflict_001', text: 'ಇದು ತಪ್ಪು! ನಾವು ಏನಾದ್ರೂ ಮಾಡ್ಬೇಕು!', character: 'arjun', emotion: 'determined', context: 'conflict', tags: ['justice'] },
    { id: 'kn_arjun_conflict_002', text: 'ಹೆದರ್ಬೇಡಿ ಫ್ರೆಂಡ್ಸ್, ನಾನು ಇದ್ದೀನಲ್ಲ!', character: 'arjun', emotion: 'determined', context: 'conflict', tags: ['brave'] },
    { id: 'kn_arjun_conflict_003', text: 'ಕಾಳಿಯಾ, ನಿನ್ನ ಈ ಕಿತಾಪತಿ ನಿಲ್ಲಿಸ್ಬೇಕು!', character: 'arjun', emotion: 'angry', context: 'conflict', tags: ['villain'] },
    { id: 'kn_arjun_resolution_001', text: 'ನೋಡಿ! ನಾನು ಹೇಳಿದ್ನಲ್ಲ, ನಮ್ಮಿಂದ ಆಗುತ್ತೆ ಅಂತ!', character: 'arjun', emotion: 'happy', context: 'resolution', tags: ['victory'] },
    { id: 'kn_arjun_resolution_002', text: 'ಎಲ್ಲರ ಶ್ರಮ ಫಲ ಕೊಟ್ಟಿತು! ಭಲೇ ಭಲೇ!', character: 'arjun', emotion: 'happy', context: 'resolution', tags: ['teamwork'] },
    { id: 'kn_arjun_moral_001', text: 'ಇವತ್ತು ನಾನು ಕಲಿತೆ — ನಿಜವಾದ ಶಕ್ತಿ ಹೃದಯದಲ್ಲಿ ಇರುತ್ತೆ!', character: 'arjun', emotion: 'thinking', context: 'moral', tags: ['courage'] },
    { id: 'kn_arjun_moral_002', text: 'ಸ್ನೇಹ ಎಲ್ಲಕ್ಕಿಂತ ದೊಡ್ಡ ಸಂಪತ್ತು, ಅಲ್ವಾ?', character: 'arjun', emotion: 'happy', context: 'moral', tags: ['friendship'] },
    { id: 'kn_arjun_reaction_001', text: 'ಅಯ್ಯೋ! ಇದೇನಾಯ್ತು ಇದು?!', character: 'arjun', emotion: 'surprised', context: 'reaction', tags: ['shock'] },
    { id: 'kn_arjun_challenge_001', text: 'ಚಾಲೆಂಜ್ ಒಪ್ಪಿಕೊಂಡೆ! ನಾನು ಎಂದಿಗೂ ಸೋಲೊಪ್ಪಲ್ಲ!', character: 'arjun', emotion: 'determined', context: 'challenge', tags: ['accept'] },
    { id: 'kn_arjun_discovery_001', text: 'ಫ್ರೆಂಡ್ಸ್, ಇದನ್ನ ನೋಡಿ! ನನಗೆ ಏನೋ ಸಿಕ್ತು!', character: 'arjun', emotion: 'surprised', context: 'discovery', tags: ['find'] },
    { id: 'kn_arjun_farewell_001', text: 'ಸರಿ ಫ್ರೆಂಡ್ಸ್, ಮತ್ತೆ ಸಿಗೋಣ! ಮುಂದಿನ ಸಲ ಇನ್ನೂ ಫನ್!', character: 'arjun', emotion: 'happy', context: 'farewell', tags: ['bye'] },
    { id: 'kn_arjun_introduction_001', text: 'ನನ್ನ ಹೆಸರು ಅರ್ಜುನ್! ಇವರು ನನ್ನ ಬೆಸ್ಟ್ ಫ್ರೆಂಡ್ಸ್!', character: 'arjun', emotion: 'happy', context: 'introduction', tags: ['self'] },
    { id: 'kn_arjun_celebration_001', text: 'ಗೆದ್ವಿ! ಗೆದ್ವಿ! ನಾವು ಗೆದ್ವಿ!', character: 'arjun', emotion: 'happy', context: 'celebration', tags: ['win'] },
    { id: 'kn_arjun_comfort_001', text: 'ಬಾಬ್ಲು, ಅಳ್ಬೇಡ! ಎಲ್ಲ ಸರಿಯಾಗುತ್ತೆ!', character: 'arjun', emotion: 'sad', context: 'comfort', tags: ['friend'] },
    { id: 'kn_arjun_narration_001', text: 'ಬಹಳ ಹಿಂದೆ, ಒಂದು ದಟ್ಟವಾದ ಕಾಡಿನಲ್ಲಿ...', character: 'arjun', emotion: 'neutral', context: 'narration', tags: ['story_start'] },
    { id: 'kn_arjun_threat_001', text: 'ಕಾಳಿಯಾ, ಹಿಂದೆ ಹೋಗು! ಇಲ್ಲಾಂದ್ರೆ ಚೆನ್ನಾಗಿರಲ್ಲ!', character: 'arjun', emotion: 'angry', context: 'threat', tags: ['warn'] },
    { id: 'kn_arjun_reaction_002', text: 'ಹೌದು! ಕರೆಕ್ಟ್! ಹಾಗೇ ಮಾಡ್ಬೇಕು!', character: 'arjun', emotion: 'happy', context: 'reaction', tags: ['agree'] },

    // ─── MEERA ─────────────────────────────────────────
    { id: 'kn_meera_greeting_001', text: 'ಹಲೋ ಎಲ್ಲರಿಗೂ! ಇವತ್ತಿನ ಪ್ರಶ್ನೆ — ನೀವು ರೆಡಿಯಾ?', character: 'meera', emotion: 'happy', context: 'greeting', tags: ['quiz'] },
    { id: 'kn_meera_conflict_001', text: 'ನಿಲ್ಲಿ! ಮೊದಲು ಯೋಚಿಸಿ, ಆಮೇಲೆ ಮಾಡಿ! ಪ್ಲಾನ್ ಇಲ್ಲದೆ ಏನೂ ಆಗಲ್ಲ!', character: 'meera', emotion: 'thinking', context: 'conflict', tags: ['plan'] },
    { id: 'kn_meera_resolution_001', text: 'ನೋಡಿ? ಬುದ್ಧಿ ಯಾವಾಗಲೂ ಗೆಲ್ಲುತ್ತೆ!', character: 'meera', emotion: 'happy', context: 'resolution', tags: ['smart'] },
    { id: 'kn_meera_moral_001', text: 'ಜ್ಞಾನವೇ ದೊಡ್ಡ ಆಯುಧ — ಇದನ್ನ ಮರೀಬೇಡಿ!', character: 'meera', emotion: 'thinking', context: 'moral', tags: ['knowledge'] },
    { id: 'kn_meera_riddle_question_001', text: 'ಯೋಚಿಸಿ... ನೀರಿನಲ್ಲಿ ಮುಳುಗದ ವಸ್ತು ಏನು?', character: 'meera', emotion: 'thinking', context: 'riddle_question', tags: ['riddle'] },
    { id: 'kn_meera_riddle_answer_001', text: 'ಕರೆಕ್ಟ್! ಉತ್ತರ ಇದೇ!', character: 'meera', emotion: 'happy', context: 'riddle_answer', tags: ['correct'] },
    { id: 'kn_meera_introduction_001', text: 'ನಾನು ಮೀರಾ! ನನಗೆ ಇಷ್ಟ — ಪುಸ್ತಕಗಳು ಮತ್ತು ಒಗಟುಗಳು!', character: 'meera', emotion: 'happy', context: 'introduction', tags: ['self'] },
    { id: 'kn_meera_reaction_001', text: 'ಹೌದಾ? ಇಂಟ್ರೆಸ್ಟಿಂಗ್! ಇನ್ನೂ ಹೇಳಿ!', character: 'meera', emotion: 'thinking', context: 'reaction', tags: ['curious'] },
    { id: 'kn_meera_farewell_001', text: 'ಮುಂದಿನ ಸಲ ಇನ್ನೂ ಕಷ್ಟದ ಒಗಟು ತರ್ತೀನಿ! ರೆಡಿಯಾಗಿರಿ!', character: 'meera', emotion: 'happy', context: 'farewell', tags: ['riddle'] },
    { id: 'kn_meera_celebration_001', text: 'ಎಲ್ಲರೂ ಸೇರಿ ಮಾಡಿದ್ವಿ! ಟೀಮ್ ವರ್ಕ್!', character: 'meera', emotion: 'happy', context: 'celebration', tags: ['teamwork'] },
    { id: 'kn_meera_comfort_001', text: 'ಗಾಬರಿ ಆಗ್ಬೇಡ, ನಾನು ಯೋಚಿಸ್ತಿದ್ದೀನಿ... ಹೌದು! ಸಿಕ್ತು!', character: 'meera', emotion: 'thinking', context: 'comfort', tags: ['solution'] },
    { id: 'kn_meera_discovery_001', text: 'ಇದು ತುಂಬಾ ಹಳೆಯದು! ಇದರಲ್ಲಿ ಏನೋ ರಹಸ್ಯ ಇದೆ!', character: 'meera', emotion: 'surprised', context: 'discovery', tags: ['ancient'] },
    { id: 'kn_meera_challenge_001', text: 'ನಾನು ರೆಡಿ! ಬುದ್ಧಿ ಪಂದ್ಯದಲ್ಲಿ ನನ್ನ ಯಾರೂ ಸೋಲಿಸಲ್ಲ!', character: 'meera', emotion: 'determined', context: 'challenge', tags: ['brain'] },
    { id: 'kn_meera_narration_001', text: 'ಈ ಕಥೆಯಲ್ಲಿ ಒಂದು ಮುಖ್ಯ ಪಾಠ ಅಡಗಿದೆ...', character: 'meera', emotion: 'neutral', context: 'narration', tags: ['story'] },
    { id: 'kn_meera_threat_001', text: 'ಕಾಳಿಯಾ, ನಿನ್ನ ತಂತ್ರಗಳು ಈ ಸಲ ಕೆಲಸ ಮಾಡಲ್ಲ!', character: 'meera', emotion: 'angry', context: 'threat', tags: ['villain'] },
    { id: 'kn_meera_conflict_002', text: 'ಇದರಲ್ಲಿ ಬಲ ಅಲ್ಲ, ಬುದ್ಧಿ ಬೇಕು!', character: 'meera', emotion: 'determined', context: 'conflict', tags: ['smart'] },
    { id: 'kn_meera_riddle_question_002', text: 'ಮೂರು ಆಯ್ಕೆಗಳು! ಸರಿಯಾದದ್ದು ಯಾವುದು? ಯೋಚಿಸಿ!', character: 'meera', emotion: 'happy', context: 'riddle_question', tags: ['options'] },
    { id: 'kn_meera_riddle_answer_002', text: 'ಅಲ್ಲ! ಸರಿಯಾದ ಉತ್ತರ ಇದು — ಯಾಕೆ ಅಂತ ಯೋಚಿಸಿ!', character: 'meera', emotion: 'thinking', context: 'riddle_answer', tags: ['wrong'] },

    // ─── BABLU ─────────────────────────────────────────
    { id: 'kn_bablu_greeting_001', text: 'ಏಯ್, ತಿಂಡಿ ಆಯ್ತಾ? ನನ್ನ ಹೊಟ್ಟೆಯಲ್ಲಿ ಇಲಿಗಳು ಓಡ್ತಿವೆ!', character: 'bablu', emotion: 'happy', context: 'greeting', tags: ['food'] },
    { id: 'kn_bablu_greeting_002', text: 'ಭಲೇ! ಇವತ್ತು ಮಸಾಲೆ ದೋಸೆ ಸಿಗುತ್ತಾ?', character: 'bablu', emotion: 'happy', context: 'greeting', tags: ['dosa'] },
    { id: 'kn_bablu_conflict_001', text: 'ಅಯ್ಯೋ! ನಾನು ಓಡ್ತೀನಿ! ನೀವು ನೋಡ್ಕೊಳ್ಳಿ!', character: 'bablu', emotion: 'scared', context: 'conflict', tags: ['run'] },
    { id: 'kn_bablu_conflict_002', text: 'ಅಯ್ಯೋ... ಇದು ದೊಡ್ಡ ಸಮಸ್ಯೆ! ನನ್ನ ಲಡ್ಡು ಬಿದ್ದೋಯ್ತು!', character: 'bablu', emotion: 'sad', context: 'conflict', tags: ['food'] },
    { id: 'kn_bablu_resolution_001', text: 'ಆಯ್ತು! ಈಗ ಪಾರ್ಟಿ! ತಿನ್ನೋಕೆ ಏನಿದೆ?', character: 'bablu', emotion: 'happy', context: 'resolution', tags: ['party'] },
    { id: 'kn_bablu_moral_001', text: 'ಗುರುಜೀ, ಈ ಪಾಠ ನೆನಪಿರುತ್ತೆ... ಊಟದ ನಂತರ!', character: 'bablu', emotion: 'happy', context: 'moral', tags: ['food'] },
    { id: 'kn_bablu_reaction_001', text: 'ಅಮ್ಮೋ! ಇದೇನಾಯ್ತು! ನನ್ನ ಕಾಲುಗಳು ನಡುಗ್ತಿವೆ!', character: 'bablu', emotion: 'scared', context: 'reaction', tags: ['scared'] },
    { id: 'kn_bablu_reaction_002', text: 'ವಾವ್! ಏನ್ ಟ್ವಿಸ್ಟ್ ಮಗಾ! ಜಿಲೇಬಿ ತರ ಟ್ವಿಸ್ಟ್!', character: 'bablu', emotion: 'surprised', context: 'reaction', tags: ['twist'] },
    { id: 'kn_bablu_celebration_001', text: 'ಗೆದ್ವಿ! ಸ್ವೀಟ್ಸ್ ತನ್ನಿ! ಲಡ್ಡು! ಮೈಸೂರ್ ಪಾಕ್!', character: 'bablu', emotion: 'happy', context: 'celebration', tags: ['sweets'] },
    { id: 'kn_bablu_introduction_001', text: 'ನನ್ನ ಹೆಸರು ಬಾಬ್ಲು! ನನ್ನ ಹಾಬಿ? ತಿನ್ನೋದು! ನನ್ನ ಶಕ್ತಿ? ತಿನ್ನೋದು!', character: 'bablu', emotion: 'happy', context: 'introduction', tags: ['self'] },
    { id: 'kn_bablu_farewell_001', text: 'ಬೈ ಬೈ! ಮುಂದಿನ ಸಲ ಹೆಚ್ಚು ಸಮೋಸಾ ತನ್ನಿ!', character: 'bablu', emotion: 'happy', context: 'farewell', tags: ['bye'] },
    { id: 'kn_bablu_comfort_001', text: 'ಅಳ್ಬೇಡ ಮಗಾ! ನನ್ನ ಕೊನೆಯ ಸಮೋಸಾ ನಿನಗೇ ಕೊಡ್ತೀನಿ!', character: 'bablu', emotion: 'sad', context: 'comfort', tags: ['sacrifice'] },
    { id: 'kn_bablu_discovery_001', text: 'ಇದೇನು? ತಿನ್ನೋ ವಸ್ತುನಾ? ವಾಸನೆ ನೋಡ್ತೀನಿ!', character: 'bablu', emotion: 'surprised', context: 'discovery', tags: ['food'] },
    { id: 'kn_bablu_challenge_001', text: 'ಚಾಲೆಂಜ್? ನಾನು ರೆಡಿ! ತಿನ್ನೋ ಚಾಲೆಂಜ್ ಆದ್ರೆ!', character: 'bablu', emotion: 'happy', context: 'challenge', tags: ['food'] },
    { id: 'kn_bablu_narration_001', text: 'ಆಮೇಲೆ ಏನಾಯ್ತು ಗೊತ್ತಾ? ನಿಲ್ಲು ಹೇಳ್ತೀನಿ! ಮೊದಲು ತಿಂತೀನಿ!', character: 'bablu', emotion: 'happy', context: 'narration', tags: ['funny'] },
    { id: 'kn_bablu_conflict_003', text: 'ನಾನಾ? ಫೈಟ್? ನೋ ವೇ ಮಗಾ! ನಾನು ಕುಕ್, ಫೈಟರ್ ಅಲ್ಲ!', character: 'bablu', emotion: 'scared', context: 'conflict', tags: ['coward'] },
    { id: 'kn_bablu_resolution_002', text: 'ನಾನೂ ಹೆಲ್ಪ್ ಮಾಡಿದೆ! ನಾನು... ಅಂ... ಮೋರಲ್ ಸಪೋರ್ಟ್ ಕೊಟ್ಟೆ!', character: 'bablu', emotion: 'happy', context: 'resolution', tags: ['funny'] },
    { id: 'kn_bablu_reaction_003', text: 'ಹ ಹ ಹ! ತುಂಬಾ ಫನ್ನಿ! ನಕ್ಕು ನಕ್ಕು ಹೊಟ್ಟೆ ನೋವು ಬಂತು!', character: 'bablu', emotion: 'happy', context: 'reaction', tags: ['laugh'] },

    // ─── GURUJI ────────────────────────────────────────
    { id: 'kn_guruji_greeting_001', text: 'ಬನ್ನಿ ಮಕ್ಕಳೇ! ಇವತ್ತು ಒಂದು ಬಹಳ ಹಳೆಯ ಕಥೆ ಹೇಳ್ತೀನಿ!', character: 'guruji', emotion: 'happy', context: 'greeting', tags: ['story'] },
    { id: 'kn_guruji_conflict_001', text: 'ತಾಳ್ಮೆ ಇಡಿ ಮಕ್ಕಳೇ! ಪ್ರತಿ ಸಮಸ್ಯೆಗೂ ಪರಿಹಾರ ಇರುತ್ತೆ!', character: 'guruji', emotion: 'neutral', context: 'conflict', tags: ['patience'] },
    { id: 'kn_guruji_resolution_001', text: 'ಭಲೇ! ಸರಿಯಾದ ದಾರಿ ಆಯ್ಕೆ ಮಾಡಿದ್ರಿ! ಹೆಮ್ಮೆ ಆಗ್ತಿದೆ!', character: 'guruji', emotion: 'happy', context: 'resolution', tags: ['proud'] },
    { id: 'kn_guruji_moral_001', text: 'ನೆನಪಿಡಿ ಮಕ್ಕಳೇ — ನಿಜವಾದ ಸಂಪತ್ತು ಜ್ಞಾನ ಮತ್ತು ಪ್ರೀತಿ!', character: 'guruji', emotion: 'neutral', context: 'moral', tags: ['wealth'] },
    { id: 'kn_guruji_moral_002', text: 'ಅಹಂಕಾರ ಪತನಕ್ಕೆ ಕಾರಣ — ವಿನಯಕ್ಕಿಂತ ದೊಡ್ಡ ಶಕ್ತಿ ಇಲ್ಲ!', character: 'guruji', emotion: 'thinking', context: 'moral', tags: ['pride'] },
    { id: 'kn_guruji_narration_001', text: 'ಬಹಳ ಹಿಂದೆ, ಈ ಕಾಡಿನಲ್ಲಿ ಒಂದು ಬುದ್ಧಿವಂತ ಪ್ರಾಣಿ ಇತ್ತು...', character: 'guruji', emotion: 'neutral', context: 'narration', tags: ['story_start'] },
    { id: 'kn_guruji_comfort_001', text: 'ಸೋಲೊಪ್ಪಬೇಡ ಮಗನೇ! ನಿಜವಾದ ಶಕ್ತಿ ಬಿದ್ದು ಮೇಲೆದ್ದೇಳೋದರಲ್ಲಿ ಇದೆ!', character: 'guruji', emotion: 'neutral', context: 'comfort', tags: ['encourage'] },
    { id: 'kn_guruji_introduction_001', text: 'ನಾನು ಗುರುಜೀ! ನನ್ನ ಬಳಿ ಕಥೆಗಳ ಅಮೂಲ್ಯ ನಿಧಿ ಇದೆ!', character: 'guruji', emotion: 'happy', context: 'introduction', tags: ['self'] },
    { id: 'kn_guruji_farewell_001', text: 'ಹೋಗಿ ಮಕ್ಕಳೇ, ಇವತ್ತಿನ ಪಾಠ ಹೃದಯದಲ್ಲಿ ಇಟ್ಕೊಳ್ಳಿ!', character: 'guruji', emotion: 'happy', context: 'farewell', tags: ['lesson'] },
    { id: 'kn_guruji_reaction_001', text: 'ಹ್ಮ್ಮ್... ತುಂಬಾ ಆಸಕ್ತಿಕರ! ನನಗೆ ಒಂದು ಕಥೆ ನೆನಪಾಗ್ತಿದೆ!', character: 'guruji', emotion: 'thinking', context: 'reaction', tags: ['story'] },
    { id: 'kn_guruji_riddle_question_001', text: 'ಈಗ ಒಂದು ಒಗಟು! ಗಮನವಿಟ್ಟು ಕೇಳಿ, ಯೋಚಿಸಿ!', character: 'guruji', emotion: 'happy', context: 'riddle_question', tags: ['riddle'] },
    { id: 'kn_guruji_riddle_answer_001', text: 'ಅದ್ಭುತ! ಸರಿಯಾದ ಉತ್ತರ! ನೀನು ನಿಜಕ್ಕೂ ಬುದ್ಧಿವಂತ!', character: 'guruji', emotion: 'happy', context: 'riddle_answer', tags: ['correct'] },
    { id: 'kn_guruji_discovery_001', text: 'ಇದು ತುಂಬಾ ಪ್ರಾಚೀನ! ನಮ್ಮ ಪೂರ್ವಿಕರ ಜ್ಞಾನ ಇದರಲ್ಲಿ ಅಡಗಿದೆ!', character: 'guruji', emotion: 'surprised', context: 'discovery', tags: ['ancient'] },
    { id: 'kn_guruji_celebration_001', text: 'ಸಂತೋಷ ಹಂಚಿಕೊಂಡರೆ ಎರಡ್ಮಡಿ ಆಗುತ್ತೆ! ಆಚರಿಸೋಣ!', character: 'guruji', emotion: 'happy', context: 'celebration', tags: ['share'] },
    { id: 'kn_guruji_conflict_002', text: 'ಬಲದಿಂದ ಅಲ್ಲ, ಬುದ್ಧಿಯಿಂದ ಹೋರಾಡಿ! ಮನಸ್ಸನ್ನು ಶಾಂತವಾಗಿ ಇಡಿ!', character: 'guruji', emotion: 'neutral', context: 'conflict', tags: ['calm'] },

    // ─── KAALIYA ───────────────────────────────────────
    { id: 'kn_kaaliya_conflict_001', text: 'ನನ್ನ ದಾರಿಯಲ್ಲಿ ನಿಲ್ಲೋಕೆ ನಿನಗೆ ಎಷ್ಟು ಧೈರ್ಯ!', character: 'kaaliya', emotion: 'angry', context: 'conflict', tags: ['threat'] },
    { id: 'kn_kaaliya_conflict_002', text: 'ಮೂರ್ಖರೇ! ನನ್ನ ನೀವು ಎಂದಿಗೂ ಸೋಲಿಸಲ್ಲ!', character: 'kaaliya', emotion: 'angry', context: 'conflict', tags: ['superior'] },
    { id: 'kn_kaaliya_conflict_003', text: 'ಹ ಹ ಹ! ನನ್ನ ಬಲೆ ಸಿದ್ಧ! ಈಗ ತಮಾಷೆ ನೋಡಿ!', character: 'kaaliya', emotion: 'happy', context: 'conflict', tags: ['trap'] },
    { id: 'kn_kaaliya_threat_001', text: 'ಕೇಳಿ! ನನ್ನ ವಿರುದ್ಧ ಹೋದವನಿಗೆ ಒಳ್ಳೆಯ ಗತಿ ಇರಲ್ಲ!', character: 'kaaliya', emotion: 'angry', context: 'threat', tags: ['warning'] },
    { id: 'kn_kaaliya_resolution_001', text: 'ಸರಿ... ಬಹುಶಃ ನಾನು ತಪ್ಪು... ಆದ್ರೆ ಇದು ಕೊನೆಯ ಬಾರಿ!', character: 'kaaliya', emotion: 'sad', context: 'resolution', tags: ['admit'] },
    { id: 'kn_kaaliya_moral_001', text: 'ಬಹುಶಃ... ಸ್ನೇಹ ಶಕ್ತಿಗಿಂತ ಮುಖ್ಯನೋ...', character: 'kaaliya', emotion: 'thinking', context: 'moral', tags: ['change'] },
    { id: 'kn_kaaliya_reaction_001', text: 'ಏನು?! ಇದು ಹೇಗೆ ಸಾಧ್ಯ! ಇಲ್ಲ!', character: 'kaaliya', emotion: 'surprised', context: 'reaction', tags: ['shock'] },
    { id: 'kn_kaaliya_introduction_001', text: 'ನಾನು ಕಾಳಿಯಾ! ಈ ಕಾಡಿನ ಅತ್ಯಂತ ಶಕ್ತಿಶಾಲಿ! ಎಲ್ಲರೂ ನನಗೆ ಹೆದರ್ತಾರೆ!', character: 'kaaliya', emotion: 'angry', context: 'introduction', tags: ['self'] },
    { id: 'kn_kaaliya_farewell_001', text: 'ನೆನಪಿಡು... ಕಾಳಿಯಾ ಯಾವಾಗಲೂ ವಾಪಸ್ ಬರ್ತಾನೆ!', character: 'kaaliya', emotion: 'angry', context: 'farewell', tags: ['ominous'] },
    { id: 'kn_kaaliya_greeting_001', text: 'ಹ್ಮ್... ಇವತ್ತು ಯಾವ ಬುದ್ಧಿಹೀನ ನನ್ನ ದಾರಿಗೆ ಬರ್ತಾನೋ!', character: 'kaaliya', emotion: 'angry', context: 'greeting', tags: ['menace'] },
    { id: 'kn_kaaliya_discovery_001', text: 'ಆಹಾ! ಇದು ತುಂಬಾ ಬೆಲೆ ಬಾಳುವುದು! ಈಗ ಇದು ನನ್ನದು!', character: 'kaaliya', emotion: 'happy', context: 'discovery', tags: ['greed'] },
    { id: 'kn_kaaliya_challenge_001', text: 'ನನಗೆ ಚಾಲೆಂಜ್? ಹ! ಯಾರ ಜೊತೆ ಕಿತಾಪತಿ ಮಾಡ್ತಿದ್ದೀರಾ ಗೊತ್ತಿಲ್ಲ!', character: 'kaaliya', emotion: 'angry', context: 'challenge', tags: ['arrogant'] },

    // ─── AMMA ──────────────────────────────────────────
    { id: 'kn_amma_greeting_001', text: 'ಬನ್ನಿ ಮಕ್ಕಳೇ, ಊಟ ರೆಡಿ! ಮೊದಲು ಕೈ ತೊಳೆಯಿರಿ!', character: 'amma', emotion: 'happy', context: 'greeting', tags: ['food'] },
    { id: 'kn_amma_conflict_001', text: 'ಮಕ್ಕಳೇ, ಜಗಳ ಮಾಡಬೇಡಿ! ಪ್ರೀತಿಯಿಂದ ಮಾತಾಡಿ!', character: 'amma', emotion: 'sad', context: 'conflict', tags: ['peace'] },
    { id: 'kn_amma_resolution_001', text: 'ದೇವರ ದಯೆ! ನನ್ನ ಮಕ್ಕಳು ಕ್ಷೇಮವಾಗಿ ಇದ್ದಾರೆ!', character: 'amma', emotion: 'happy', context: 'resolution', tags: ['relief'] },
    { id: 'kn_amma_moral_001', text: 'ನೆನಪಿಡು ಮಗನೇ, ಪ್ರೀತಿ ಎಲ್ಲಕ್ಕಿಂತ ದೊಡ್ಡ ಶಕ್ತಿ!', character: 'amma', emotion: 'happy', context: 'moral', tags: ['love'] },
    { id: 'kn_amma_comfort_001', text: 'ಅಳಬೇಡ ನನ್ನ ಕಂದಾ! ಅಮ್ಮ ಇದ್ದಾಳಲ್ಲ! ಎಲ್ಲ ಸರಿಯಾಗುತ್ತೆ!', character: 'amma', emotion: 'sad', context: 'comfort', tags: ['mother'] },
    { id: 'kn_amma_introduction_001', text: 'ನಾನು ಈ ಮಕ್ಕಳ ಅಮ್ಮ! ಅವರ ಖುಷಿಯೇ ನನ್ನ ಜಗತ್ತು!', character: 'amma', emotion: 'happy', context: 'introduction', tags: ['self'] },
    { id: 'kn_amma_farewell_001', text: 'ಬೇಗ ವಾಪಸ್ ಬನ್ನಿ! ದಾರಿಯಲ್ಲಿ ಏನಾದ್ರೂ ತಿನ್ನಿ!', character: 'amma', emotion: 'happy', context: 'farewell', tags: ['care'] },
    { id: 'kn_amma_celebration_001', text: 'ಭಲೇ! ಇವತ್ತು ಎಲ್ಲರಿಗೂ ಪಾಯಸ ಮಾಡ್ತೀನಿ!', character: 'amma', emotion: 'happy', context: 'celebration', tags: ['sweet'] },
    { id: 'kn_amma_reaction_001', text: 'ಅಯ್ಯೋ! ಇದೇನಾಯ್ತು ಇದು!', character: 'amma', emotion: 'surprised', context: 'reaction', tags: ['shock'] },
    { id: 'kn_amma_narration_001', text: 'ನಮ್ಮ ಅಜ್ಜಿ ಹೇಳ್ತಿದ್ರು — ಪ್ರತಿ ಮಗುವಿನಲ್ಲೂ ಒಬ್ಬ ಹೀರೋ ಅಡಗಿದ್ದಾನೆ!', character: 'amma', emotion: 'neutral', context: 'narration', tags: ['grandmother'] },

    // ─── RAJA ──────────────────────────────────────────
    { id: 'kn_raja_greeting_001', text: 'ಪ್ರಜೆಗಳಿಗೆ ನನ್ನ ನಮಸ್ಕಾರ! ಇವತ್ತು ದರ್ಬಾರಿನಲ್ಲಿ ಏನು ವಿಷಯ?', character: 'raja', emotion: 'neutral', context: 'greeting', tags: ['court'] },
    { id: 'kn_raja_conflict_001', text: 'ಇದು ಅನ್ಯಾಯ! ರಾಜ್ಯದಲ್ಲಿ ಹೀಗೆ ನಡೆಯಲ್ಲ!', character: 'raja', emotion: 'angry', context: 'conflict', tags: ['justice'] },
    { id: 'kn_raja_resolution_001', text: 'ನ್ಯಾಯ ಆಯ್ತು! ಈಗ ರಾಜ್ಯದಲ್ಲಿ ಶಾಂತಿ ನೆಲೆಸುತ್ತೆ!', character: 'raja', emotion: 'happy', context: 'resolution', tags: ['justice'] },
    { id: 'kn_raja_moral_001', text: 'ಒಳ್ಳೆಯ ರಾಜ ಪ್ರಜೆಗಳ ಸೇವೆ ಮಾಡ್ಬೇಕು!', character: 'raja', emotion: 'neutral', context: 'moral', tags: ['service'] },
    { id: 'kn_raja_introduction_001', text: 'ನಾನು ಈ ರಾಜ್ಯದ ರಾಜ! ನ್ಯಾಯ ಮತ್ತು ಧರ್ಮ ನನ್ನ ಕರ್ತವ್ಯ!', character: 'raja', emotion: 'neutral', context: 'introduction', tags: ['self'] },
    { id: 'kn_raja_celebration_001', text: 'ಇವತ್ತು ಇಡೀ ರಾಜ್ಯದಲ್ಲಿ ಉತ್ಸವ! ಎಲ್ಲರಿಗೂ ಸಿಹಿ ಹಂಚಿ!', character: 'raja', emotion: 'happy', context: 'celebration', tags: ['festival'] },
    { id: 'kn_raja_farewell_001', text: 'ಹೋಗಿ, ರಾಜ್ಯ ಸೇವೆ ಮಾಡಿ! ಅದೇ ದೊಡ್ಡ ಧರ್ಮ!', character: 'raja', emotion: 'neutral', context: 'farewell', tags: ['duty'] },
    { id: 'kn_raja_challenge_001', text: 'ಈ ಸವಾಲು ಗೆಲ್ಲುವವರಿಗೆ ಬಹುಮಾನ ಸಿಗುತ್ತೆ!', character: 'raja', emotion: 'neutral', context: 'challenge', tags: ['reward'] },
    { id: 'kn_raja_narration_001', text: 'ಬಹಳ ಹಿಂದೆ, ಈ ರಾಜ್ಯದಲ್ಲಿ ಒಬ್ಬ ಮಹಾನ್ ರಾಜ ಇದ್ದ...', character: 'raja', emotion: 'neutral', context: 'narration', tags: ['story_start'] },
    { id: 'kn_raja_reaction_001', text: 'ಇದು ಅದ್ಭುತ! ಭಲೇ!', character: 'raja', emotion: 'surprised', context: 'reaction', tags: ['impressed'] },
    { id: 'kn_raja_comfort_001', text: 'ಚಿಂತೆ ಮಾಡ್ಬೇಡಿ! ರಾಜ ಇರುವ ತನಕ ಪ್ರಜೆಗಳು ಸುರಕ್ಷಿತ!', character: 'raja', emotion: 'neutral', context: 'comfort', tags: ['protect'] },
    { id: 'kn_raja_discovery_001', text: 'ಇದು ರಾಜ್ಯದ ಪ್ರಾಚೀನ ನಿಧಿ! ಇದನ್ನ ಜಾಗ್ರತೆಯಾಗಿ ಕಾಪಾಡಿ!', character: 'raja', emotion: 'surprised', context: 'discovery', tags: ['treasure'] },
    { id: 'kn_raja_threat_001', text: 'ಎಚ್ಚರ! ರಾಜ್ಯದ ನಿಯಮ ಮೀರಿದವರಿಗೆ ಶಿಕ್ಷೆ ಖಂಡಿತ!', character: 'raja', emotion: 'angry', context: 'threat', tags: ['law'] },

    // ─── MOTI ──────────────────────────────────────────
    { id: 'kn_moti_greeting_001', text: 'ಭೌ ಭೌ! (ಬಾಲ ಆಡಿಸ್ತಾ)', character: 'moti', emotion: 'happy', context: 'greeting', tags: ['bark'] },
    { id: 'kn_moti_conflict_001', text: 'ಗರ್ರ್ರ್! (ರಕ್ಷಿಸಲು ಪ್ರಯತ್ನಿಸ್ತಾ)', character: 'moti', emotion: 'angry', context: 'conflict', tags: ['growl'] },
    { id: 'kn_moti_resolution_001', text: 'ಭೌ! ಭೌ ಭೌ! (ಖುಷಿಯಿಂದ ಜಿಗಿಯುತ್ತಾ)', character: 'moti', emotion: 'happy', context: 'resolution', tags: ['bark'] },
    { id: 'kn_moti_reaction_001', text: 'ಕೂನ್ ಕೂನ್? (ತಲೆ ಓರೆ ಮಾಡ್ತಾ)', character: 'moti', emotion: 'surprised', context: 'reaction', tags: ['confused'] },
    { id: 'kn_moti_comfort_001', text: 'ಕೂನ್... (ಮೆಲ್ಲನೆ ಹತ್ತಿರ ಬಂದು)', character: 'moti', emotion: 'sad', context: 'comfort', tags: ['nuzzle'] },
    { id: 'kn_moti_celebration_001', text: 'ಭೌ ಭೌ ಭೌ! (ಗುಂಡಗೆ ಓಡ್ತಾ)', character: 'moti', emotion: 'happy', context: 'celebration', tags: ['spin'] },
    { id: 'kn_moti_introduction_001', text: 'ಭೌ! (ನಾನು ಮೋತಿ — ಎಲ್ಲರ ಬೆಸ್ಟ್ ಫ್ರೆಂಡ್!)', character: 'moti', emotion: 'happy', context: 'introduction', tags: ['self'] },
    { id: 'kn_moti_farewell_001', text: 'ಕೂನ್... ಭೌ! (ಬಿಡೋಕೆ ಮನಸ್ಸಿಲ್ಲ, ಆಮೇಲೆ ಬೈ ಹೇಳ್ತಾ)', character: 'moti', emotion: 'sad', context: 'farewell', tags: ['bye'] },
    { id: 'kn_moti_discovery_001', text: 'ಭೌ! ಭೌ! (ಏನೋ ವಾಸನೆ ಮಾಡ್ತಾ, ಜೋರಾಗಿ ಬೊಗಳ್ತಾ)', character: 'moti', emotion: 'surprised', context: 'discovery', tags: ['sniff'] },
    { id: 'kn_moti_threat_001', text: 'ಗರ್ರ್ರ್ರ್ರ್! (ಹಲ್ಲು ತೋರಿಸ್ತಾ)', character: 'moti', emotion: 'angry', context: 'threat', tags: ['growl'] },
    { id: 'kn_moti_moral_001', text: 'ಭೌ! (ನಿಷ್ಠೆ ಎಲ್ಲಕ್ಕಿಂತ ದೊಡ್ಡ ಗುಣ!)', character: 'moti', emotion: 'happy', context: 'moral', tags: ['loyalty'] },
    { id: 'kn_moti_narration_001', text: '(ಮೋತಿ ಸುಮ್ಮನೆ ಕೇಳ್ತಿತ್ತು, ಎಲ್ಲಾ ಅರ್ಥ ಆಗಿರೋ ಹಾಗೆ)', character: 'moti', emotion: 'neutral', context: 'narration', tags: ['listen'] },
    { id: 'kn_moti_challenge_001', text: 'ಭೌ ಭೌ! (ರೆಡಿ! ಓಡ್ತಾ)', character: 'moti', emotion: 'determined', context: 'challenge', tags: ['ready'] },
  ],
};
