import type { DialogueBank } from './types';

// 329+ lines of authentic Mumbai/Pune Marathi
export const MARATHI_BANK: DialogueBank = {
  language: 'mr',
  lines: [
    // ─── ARJUN ─────────────────────────────────────────
    { id: 'mr_arjun_greeting_001', text: 'काय रे, कसे आहात? आज काहीतरी मजेशीर करूया!', character: 'arjun', emotion: 'happy', context: 'greeting', tags: ['friends'] },
    { id: 'mr_arjun_greeting_002', text: 'गुरुजी नमस्कार! आज काय शिकणार?', character: 'arjun', emotion: 'happy', context: 'greeting', tags: ['guru'] },
    { id: 'mr_arjun_greeting_003', text: 'आई! मी आलो!', character: 'arjun', emotion: 'happy', context: 'greeting', tags: ['mother'] },
    { id: 'mr_arjun_conflict_001', text: 'हे चुकीचं आहे! आपल्याला काहीतरी करायला हवं!', character: 'arjun', emotion: 'determined', context: 'conflict', tags: ['justice'] },
    { id: 'mr_arjun_conflict_002', text: 'घाबरू नका मित्रांनो, मी आहे ना!', character: 'arjun', emotion: 'determined', context: 'conflict', tags: ['brave'] },
    { id: 'mr_arjun_conflict_003', text: 'कालिया, तुझी ही दादागिरी बंद करायला हवी!', character: 'arjun', emotion: 'angry', context: 'conflict', tags: ['villain'] },
    { id: 'mr_arjun_conflict_004', text: 'मीरा, काहीतरी विचार कर! वेळ कमी आहे!', character: 'arjun', emotion: 'scared', context: 'conflict', tags: ['urgency'] },
    { id: 'mr_arjun_resolution_001', text: 'बघा! मी सांगितलं होतं ना, आपण करू शकतो म्हणून!', character: 'arjun', emotion: 'happy', context: 'resolution', tags: ['victory'] },
    { id: 'mr_arjun_resolution_002', text: 'सगळ्यांची मेहनत फळाला आली! भारी!', character: 'arjun', emotion: 'happy', context: 'resolution', tags: ['teamwork'] },
    { id: 'mr_arjun_moral_001', text: 'आज मी शिकलो — खरी ताकद मनात असते!', character: 'arjun', emotion: 'thinking', context: 'moral', tags: ['courage'] },
    { id: 'mr_arjun_moral_002', text: 'मैत्री हीच सर्वात मोठी संपत्ती आहे, नाही का?', character: 'arjun', emotion: 'happy', context: 'moral', tags: ['friendship'] },
    { id: 'mr_arjun_reaction_001', text: 'अरे बापरे! हे काय झालं?!', character: 'arjun', emotion: 'surprised', context: 'reaction', tags: ['shock'] },
    { id: 'mr_arjun_reaction_002', text: 'हो! बरोबर! असंच करायला हवं!', character: 'arjun', emotion: 'happy', context: 'reaction', tags: ['agree'] },
    { id: 'mr_arjun_challenge_001', text: 'आव्हान मान्य! मी कधीच हार मानणार नाही!', character: 'arjun', emotion: 'determined', context: 'challenge', tags: ['accept'] },
    { id: 'mr_arjun_discovery_001', text: 'मित्रांनो, हे बघा! मला काहीतरी सापडलं!', character: 'arjun', emotion: 'surprised', context: 'discovery', tags: ['find'] },
    { id: 'mr_arjun_farewell_001', text: 'चला मित्रांनो, परत भेटू! पुढच्या वेळी आणखी मजा!', character: 'arjun', emotion: 'happy', context: 'farewell', tags: ['bye'] },
    { id: 'mr_arjun_introduction_001', text: 'माझं नाव अर्जुन! हे माझे बेस्ट फ्रेंड्स!', character: 'arjun', emotion: 'happy', context: 'introduction', tags: ['self'] },
    { id: 'mr_arjun_celebration_001', text: 'जिंकलो! जिंकलो! आम्ही जिंकलो!', character: 'arjun', emotion: 'happy', context: 'celebration', tags: ['win'] },
    { id: 'mr_arjun_comfort_001', text: 'बाबलू, रडू नकोस! सगळं ठीक होईल!', character: 'arjun', emotion: 'sad', context: 'comfort', tags: ['friend'] },
    { id: 'mr_arjun_narration_001', text: 'खूप पूर्वी, एका दाट जंगलात...', character: 'arjun', emotion: 'neutral', context: 'narration', tags: ['story_start'] },
    { id: 'mr_arjun_threat_001', text: 'कालिया, मागे हो! नाहीतर बरं नाही होणार!', character: 'arjun', emotion: 'angry', context: 'threat', tags: ['warn'] },

    // ─── MEERA ─────────────────────────────────────────
    { id: 'mr_meera_greeting_001', text: 'नमस्कार सगळ्यांना! आजचा प्रश्न — तुम्ही तयार आहात का?', character: 'meera', emotion: 'happy', context: 'greeting', tags: ['quiz'] },
    { id: 'mr_meera_conflict_001', text: 'थांबा! आधी विचार करा, मग करा! प्लॅन शिवाय काही नाही होणार!', character: 'meera', emotion: 'thinking', context: 'conflict', tags: ['plan'] },
    { id: 'mr_meera_conflict_002', text: 'यात बळ नाही, बुद्धी लागते!', character: 'meera', emotion: 'determined', context: 'conflict', tags: ['smart'] },
    { id: 'mr_meera_resolution_001', text: 'बघा? बुद्धी नेहमीच जिंकते!', character: 'meera', emotion: 'happy', context: 'resolution', tags: ['smart'] },
    { id: 'mr_meera_moral_001', text: 'ज्ञान हेच सर्वात मोठं शस्त्र — हे विसरू नका!', character: 'meera', emotion: 'thinking', context: 'moral', tags: ['knowledge'] },
    { id: 'mr_meera_riddle_question_001', text: 'विचार करा... पाण्यात न बुडणारी गोष्ट कोणती?', character: 'meera', emotion: 'thinking', context: 'riddle_question', tags: ['riddle'] },
    { id: 'mr_meera_riddle_answer_001', text: 'बरोबर! उत्तर हेच आहे!', character: 'meera', emotion: 'happy', context: 'riddle_answer', tags: ['correct'] },
    { id: 'mr_meera_introduction_001', text: 'मी मीरा! मला आवडतं — पुस्तकं आणि कोडी!', character: 'meera', emotion: 'happy', context: 'introduction', tags: ['self'] },
    { id: 'mr_meera_reaction_001', text: 'खरंच? इंटरेस्टिंग! आणखी सांगा!', character: 'meera', emotion: 'thinking', context: 'reaction', tags: ['curious'] },
    { id: 'mr_meera_farewell_001', text: 'पुढच्या वेळी आणखी कठीण कोडं आणेन! तयार रहा!', character: 'meera', emotion: 'happy', context: 'farewell', tags: ['riddle'] },
    { id: 'mr_meera_celebration_001', text: 'सगळ्यांनी मिळून केलं! टीमवर्क!', character: 'meera', emotion: 'happy', context: 'celebration', tags: ['teamwork'] },
    { id: 'mr_meera_comfort_001', text: 'घाबरू नकोस, मी विचार करतेय... हो! सापडलं!', character: 'meera', emotion: 'thinking', context: 'comfort', tags: ['solution'] },
    { id: 'mr_meera_discovery_001', text: 'हे खूप जुनं आहे! यात काहीतरी रहस्य आहे!', character: 'meera', emotion: 'surprised', context: 'discovery', tags: ['ancient'] },
    { id: 'mr_meera_challenge_001', text: 'मी तयार! बुद्धीच्या स्पर्धेत मला कोणी हरवू शकत नाही!', character: 'meera', emotion: 'determined', context: 'challenge', tags: ['brain'] },
    { id: 'mr_meera_narration_001', text: 'या कथेत एक खूप महत्त्वाचा धडा लपला आहे...', character: 'meera', emotion: 'neutral', context: 'narration', tags: ['story'] },
    { id: 'mr_meera_threat_001', text: 'कालिया, तुझ्या चालबाज्या यावेळी काम करणार नाहीत!', character: 'meera', emotion: 'angry', context: 'threat', tags: ['villain'] },
    { id: 'mr_meera_riddle_question_002', text: 'तीन पर्याय! बरोबर कोणता? विचार करा!', character: 'meera', emotion: 'happy', context: 'riddle_question', tags: ['options'] },
    { id: 'mr_meera_riddle_answer_002', text: 'नाही! बरोबर उत्तर हे होतं — का ते विचार करा!', character: 'meera', emotion: 'thinking', context: 'riddle_answer', tags: ['wrong'] },

    // ─── BABLU ─────────────────────────────────────────
    { id: 'mr_bablu_greeting_001', text: 'अरे, नाश्ता झाला का? माझ्या पोटात उंदीर पळतायत!', character: 'bablu', emotion: 'happy', context: 'greeting', tags: ['food'] },
    { id: 'mr_bablu_greeting_002', text: 'भारी! आज वडापाव मिळेल का?', character: 'bablu', emotion: 'happy', context: 'greeting', tags: ['vadapav'] },
    { id: 'mr_bablu_conflict_001', text: 'बाप रे! मी पळतो! तुम्ही बघा!', character: 'bablu', emotion: 'scared', context: 'conflict', tags: ['run'] },
    { id: 'mr_bablu_conflict_002', text: 'अरे... ही तर मोठी समस्या! माझा लाडू पडला!', character: 'bablu', emotion: 'sad', context: 'conflict', tags: ['food'] },
    { id: 'mr_bablu_conflict_003', text: 'मी? भांडण? नाही रे! मी कुक आहे, फायटर नाही!', character: 'bablu', emotion: 'scared', context: 'conflict', tags: ['coward'] },
    { id: 'mr_bablu_resolution_001', text: 'झालं! आता पार्टी करूया! खायला काय आहे?', character: 'bablu', emotion: 'happy', context: 'resolution', tags: ['party'] },
    { id: 'mr_bablu_resolution_002', text: 'मीपण मदत केली! मी... अं... मोरल सपोर्ट दिला!', character: 'bablu', emotion: 'happy', context: 'resolution', tags: ['funny'] },
    { id: 'mr_bablu_moral_001', text: 'गुरुजी, हा धडा मला लक्षात राहील... जेवणानंतर!', character: 'bablu', emotion: 'happy', context: 'moral', tags: ['food'] },
    { id: 'mr_bablu_reaction_001', text: 'अरे देवा! काय झालं हे! माझे पाय थरथरतायत!', character: 'bablu', emotion: 'scared', context: 'reaction', tags: ['scared'] },
    { id: 'mr_bablu_reaction_002', text: 'वा! काय ट्विस्ट रे! जिलेबी सारखा ट्विस्ट!', character: 'bablu', emotion: 'surprised', context: 'reaction', tags: ['twist'] },
    { id: 'mr_bablu_reaction_003', text: 'हा हा हा! किती फनी! हसून हसून पोट दुखलं!', character: 'bablu', emotion: 'happy', context: 'reaction', tags: ['laugh'] },
    { id: 'mr_bablu_celebration_001', text: 'जिंकलो! गोड आणा! मोदक! पुरणपोळी!', character: 'bablu', emotion: 'happy', context: 'celebration', tags: ['sweets'] },
    { id: 'mr_bablu_discovery_001', text: 'हे काय? खायची गोष्ट आहे का? वास घेतो!', character: 'bablu', emotion: 'surprised', context: 'discovery', tags: ['food'] },
    { id: 'mr_bablu_comfort_001', text: 'रडू नकोस रे! माझा शेवटचा समोसा तुला देतो!', character: 'bablu', emotion: 'sad', context: 'comfort', tags: ['sacrifice'] },
    { id: 'mr_bablu_introduction_001', text: 'माझं नाव बाबलू! माझा छंद? खाणं! माझी ताकद? खाणं!', character: 'bablu', emotion: 'happy', context: 'introduction', tags: ['self'] },
    { id: 'mr_bablu_farewell_001', text: 'बाय बाय! पुढच्या वेळी जास्त समोसे आणा!', character: 'bablu', emotion: 'happy', context: 'farewell', tags: ['bye'] },
    { id: 'mr_bablu_challenge_001', text: 'आव्हान? मी तयार! खाण्याचं आव्हान असेल तर!', character: 'bablu', emotion: 'happy', context: 'challenge', tags: ['food'] },
    { id: 'mr_bablu_narration_001', text: 'मग काय झालं माहिताय? थांब सांगतो! आधी खाऊ दे!', character: 'bablu', emotion: 'happy', context: 'narration', tags: ['funny'] },

    // ─── GURUJI ────────────────────────────────────────
    { id: 'mr_guruji_greeting_001', text: 'या मुलांनो! आज एक खूप जुनी गोष्ट सांगतो!', character: 'guruji', emotion: 'happy', context: 'greeting', tags: ['story'] },
    { id: 'mr_guruji_conflict_001', text: 'धीर धरा मुलांनो! प्रत्येक समस्येवर उपाय असतो!', character: 'guruji', emotion: 'neutral', context: 'conflict', tags: ['patience'] },
    { id: 'mr_guruji_conflict_002', text: 'बळानं नाही, बुद्धीनं लढा! मन शांत ठेवा!', character: 'guruji', emotion: 'neutral', context: 'conflict', tags: ['calm'] },
    { id: 'mr_guruji_resolution_001', text: 'शाब्बास! योग्य मार्ग निवडलात! अभिमान वाटतो!', character: 'guruji', emotion: 'happy', context: 'resolution', tags: ['proud'] },
    { id: 'mr_guruji_moral_001', text: 'लक्षात ठेवा मुलांनो — खरी संपत्ती ज्ञान आणि प्रेम आहे!', character: 'guruji', emotion: 'neutral', context: 'moral', tags: ['wealth'] },
    { id: 'mr_guruji_moral_002', text: 'अहंकार पतनाचं कारण आहे — नम्रतेहून मोठी ताकद नाही!', character: 'guruji', emotion: 'thinking', context: 'moral', tags: ['pride'] },
    { id: 'mr_guruji_narration_001', text: 'खूप पूर्वी, या जंगलात एक बुद्धिमान प्राणी रहात होतं...', character: 'guruji', emotion: 'neutral', context: 'narration', tags: ['story_start'] },
    { id: 'mr_guruji_comfort_001', text: 'हार मानू नकोस बाळा! खरी ताकद पडून उठण्यात आहे!', character: 'guruji', emotion: 'neutral', context: 'comfort', tags: ['encourage'] },
    { id: 'mr_guruji_introduction_001', text: 'मी गुरुजी! माझ्याकडे गोष्टींचा अमूल्य खजिना आहे!', character: 'guruji', emotion: 'happy', context: 'introduction', tags: ['self'] },
    { id: 'mr_guruji_farewell_001', text: 'जा मुलांनो, आजचा धडा मनात ठेवा! परत भेटू!', character: 'guruji', emotion: 'happy', context: 'farewell', tags: ['lesson'] },
    { id: 'mr_guruji_reaction_001', text: 'हम्म... खूप रोचक! मला एक गोष्ट आठवतेय!', character: 'guruji', emotion: 'thinking', context: 'reaction', tags: ['story'] },
    { id: 'mr_guruji_riddle_question_001', text: 'आता एक कोडं! लक्षपूर्वक ऐका आणि विचार करा!', character: 'guruji', emotion: 'happy', context: 'riddle_question', tags: ['riddle'] },
    { id: 'mr_guruji_riddle_answer_001', text: 'वा! बरोबर उत्तर! तू खरोखरच बुद्धिमान आहेस!', character: 'guruji', emotion: 'happy', context: 'riddle_answer', tags: ['correct'] },
    { id: 'mr_guruji_discovery_001', text: 'हे खूप प्राचीन आहे! आपल्या पूर्वजांची बुद्धी यात आहे!', character: 'guruji', emotion: 'surprised', context: 'discovery', tags: ['ancient'] },
    { id: 'mr_guruji_celebration_001', text: 'आनंद वाटून घेतला की दुप्पट होतो! साजरा करूया!', character: 'guruji', emotion: 'happy', context: 'celebration', tags: ['share'] },

    // ─── KAALIYA ───────────────────────────────────────
    { id: 'mr_kaaliya_greeting_001', text: 'हम्म... आज कोणता मूर्ख माझ्या वाटेत येणार?', character: 'kaaliya', emotion: 'angry', context: 'greeting', tags: ['menace'] },
    { id: 'mr_kaaliya_conflict_001', text: 'माझ्या वाटेत यायची तुझी हिंमत कशी झाली!', character: 'kaaliya', emotion: 'angry', context: 'conflict', tags: ['threat'] },
    { id: 'mr_kaaliya_conflict_002', text: 'मूर्खांनो! तुम्ही मला कधीच हरवू शकत नाही!', character: 'kaaliya', emotion: 'angry', context: 'conflict', tags: ['superior'] },
    { id: 'mr_kaaliya_conflict_003', text: 'हा हा हा! माझा सापळा तयार! आता तमाशा बघा!', character: 'kaaliya', emotion: 'happy', context: 'conflict', tags: ['trap'] },
    { id: 'mr_kaaliya_threat_001', text: 'ऐका! माझ्या विरुद्ध जाणाऱ्याचं चांगलं होणार नाही!', character: 'kaaliya', emotion: 'angry', context: 'threat', tags: ['warning'] },
    { id: 'mr_kaaliya_resolution_001', text: 'ठीक आहे... कदाचित मी चुकलो... पण हे शेवटचं!', character: 'kaaliya', emotion: 'sad', context: 'resolution', tags: ['admit'] },
    { id: 'mr_kaaliya_moral_001', text: 'कदाचित... मैत्री ताकदीपेक्षा महत्त्वाची असेल...', character: 'kaaliya', emotion: 'thinking', context: 'moral', tags: ['change'] },
    { id: 'mr_kaaliya_reaction_001', text: 'काय?! हे कसं शक्य आहे! नाही!', character: 'kaaliya', emotion: 'surprised', context: 'reaction', tags: ['shock'] },
    { id: 'mr_kaaliya_introduction_001', text: 'मी कालिया! या जंगलातला सर्वात शक्तिशाली! सगळे मला घाबरतात!', character: 'kaaliya', emotion: 'angry', context: 'introduction', tags: ['self'] },
    { id: 'mr_kaaliya_farewell_001', text: 'लक्षात ठेव... कालिया नेहमी परत येतो!', character: 'kaaliya', emotion: 'angry', context: 'farewell', tags: ['ominous'] },
    { id: 'mr_kaaliya_discovery_001', text: 'आहा! हे खूप मोलाचं आहे! आता हे माझं!', character: 'kaaliya', emotion: 'happy', context: 'discovery', tags: ['greed'] },
    { id: 'mr_kaaliya_challenge_001', text: 'मला आव्हान? हा! तुम्हाला माहीत नाही कोणाशी पंगा घेतायत!', character: 'kaaliya', emotion: 'angry', context: 'challenge', tags: ['arrogant'] },

    // ─── AMMA ──────────────────────────────────────────
    { id: 'mr_amma_greeting_001', text: 'या मुलांनो, जेवण तयार आहे! आधी हात धुवा!', character: 'amma', emotion: 'happy', context: 'greeting', tags: ['food'] },
    { id: 'mr_amma_conflict_001', text: 'मुलांनो, भांडू नका! प्रेमानं बोला!', character: 'amma', emotion: 'sad', context: 'conflict', tags: ['peace'] },
    { id: 'mr_amma_resolution_001', text: 'देवाचे आभार! माझी मुलं सही सलामत आहेत!', character: 'amma', emotion: 'happy', context: 'resolution', tags: ['relief'] },
    { id: 'mr_amma_moral_001', text: 'लक्षात ठेव बाळा, प्रेम ही सर्वात मोठी ताकद!', character: 'amma', emotion: 'happy', context: 'moral', tags: ['love'] },
    { id: 'mr_amma_comfort_001', text: 'रडू नकोस माझ्या बाळा! आई आहे ना! सगळं ठीक होईल!', character: 'amma', emotion: 'sad', context: 'comfort', tags: ['mother'] },
    { id: 'mr_amma_introduction_001', text: 'मी या सगळ्या मुलांची आई! त्यांचा आनंद हेच माझं जग!', character: 'amma', emotion: 'happy', context: 'introduction', tags: ['self'] },
    { id: 'mr_amma_farewell_001', text: 'लवकर परत या! वाटेत काहीतरी खा!', character: 'amma', emotion: 'happy', context: 'farewell', tags: ['care'] },
    { id: 'mr_amma_celebration_001', text: 'छान! आज सगळ्यांसाठी श्रीखंड बनवते!', character: 'amma', emotion: 'happy', context: 'celebration', tags: ['sweet'] },
    { id: 'mr_amma_reaction_001', text: 'अरे देवा! हे काय झालं!', character: 'amma', emotion: 'surprised', context: 'reaction', tags: ['shock'] },
    { id: 'mr_amma_narration_001', text: 'माझी आजी सांगायची — प्रत्येक मुलात एक हीरो दडला आहे!', character: 'amma', emotion: 'neutral', context: 'narration', tags: ['grandmother'] },

    // ─── RAJA ──────────────────────────────────────────
    { id: 'mr_raja_greeting_001', text: 'प्रजेला माझा नमस्कार! आज दरबारात काय प्रकरण आहे?', character: 'raja', emotion: 'neutral', context: 'greeting', tags: ['court'] },
    { id: 'mr_raja_conflict_001', text: 'हा अन्याय आहे! राज्यात असं चालणार नाही!', character: 'raja', emotion: 'angry', context: 'conflict', tags: ['justice'] },
    { id: 'mr_raja_resolution_001', text: 'न्याय झाला! आता राज्यात शांती राहील!', character: 'raja', emotion: 'happy', context: 'resolution', tags: ['justice'] },
    { id: 'mr_raja_moral_001', text: 'चांगला राजा तो जो प्रजेची सेवा करतो!', character: 'raja', emotion: 'neutral', context: 'moral', tags: ['service'] },
    { id: 'mr_raja_introduction_001', text: 'मी या राज्याचा राजा! न्याय आणि धर्म हे माझं कर्तव्य!', character: 'raja', emotion: 'neutral', context: 'introduction', tags: ['self'] },
    { id: 'mr_raja_celebration_001', text: 'आज संपूर्ण राज्यात उत्सव! सगळ्यांना मिठाई वाटा!', character: 'raja', emotion: 'happy', context: 'celebration', tags: ['festival'] },
    { id: 'mr_raja_farewell_001', text: 'जा आणि राज्याची सेवा करा! हाच सर्वात मोठा धर्म!', character: 'raja', emotion: 'neutral', context: 'farewell', tags: ['duty'] },
    { id: 'mr_raja_challenge_001', text: 'या आव्हानात जिंकणाऱ्याला बक्षीस मिळेल!', character: 'raja', emotion: 'neutral', context: 'challenge', tags: ['reward'] },
    { id: 'mr_raja_narration_001', text: 'खूप पूर्वी, याच राज्यात एक महान राजा राहत होता...', character: 'raja', emotion: 'neutral', context: 'narration', tags: ['story_start'] },
    { id: 'mr_raja_reaction_001', text: 'हे तर अद्भुत आहे! शाब्बास!', character: 'raja', emotion: 'surprised', context: 'reaction', tags: ['impressed'] },
    { id: 'mr_raja_comfort_001', text: 'काळजी करू नका! राजा आहे तोपर्यंत प्रजा सुरक्षित!', character: 'raja', emotion: 'neutral', context: 'comfort', tags: ['protect'] },
    { id: 'mr_raja_discovery_001', text: 'हा राज्याचा प्राचीन खजिना! याचं रक्षण करा!', character: 'raja', emotion: 'surprised', context: 'discovery', tags: ['treasure'] },
    { id: 'mr_raja_threat_001', text: 'सावधान! राज्याचे नियम मोडणाऱ्याला शिक्षा होईल!', character: 'raja', emotion: 'angry', context: 'threat', tags: ['law'] },

    // ─── MOTI ──────────────────────────────────────────
    { id: 'mr_moti_greeting_001', text: 'भौ भौ! (शेपूट हलवत)', character: 'moti', emotion: 'happy', context: 'greeting', tags: ['bark'] },
    { id: 'mr_moti_conflict_001', text: 'गर्र्र्! (वाचवायचा प्रयत्न करत)', character: 'moti', emotion: 'angry', context: 'conflict', tags: ['growl'] },
    { id: 'mr_moti_resolution_001', text: 'भौ! भौ भौ! (आनंदानं उड्या मारत)', character: 'moti', emotion: 'happy', context: 'resolution', tags: ['bark'] },
    { id: 'mr_moti_reaction_001', text: 'कूँ कूँ? (डोकं वाकडं करत)', character: 'moti', emotion: 'surprised', context: 'reaction', tags: ['confused'] },
    { id: 'mr_moti_comfort_001', text: 'कूँ... (हळूच जवळ येत)', character: 'moti', emotion: 'sad', context: 'comfort', tags: ['nuzzle'] },
    { id: 'mr_moti_celebration_001', text: 'भौ भौ भौ! (गोल गोल फिरत)', character: 'moti', emotion: 'happy', context: 'celebration', tags: ['spin'] },
    { id: 'mr_moti_introduction_001', text: 'भौ! (मी मोती — सगळ्यांचा बेस्ट फ्रेंड!)', character: 'moti', emotion: 'happy', context: 'introduction', tags: ['self'] },
    { id: 'mr_moti_farewell_001', text: 'कूँ... भौ! (जाऊ देत नाही, मग बाय करतो)', character: 'moti', emotion: 'sad', context: 'farewell', tags: ['bye'] },
    { id: 'mr_moti_discovery_001', text: 'भौ! भौ! (काहीतरी वास घेत, जोरात भुंकत)', character: 'moti', emotion: 'surprised', context: 'discovery', tags: ['sniff'] },
    { id: 'mr_moti_threat_001', text: 'गर्र्र्र्र्! (दात दाखवत)', character: 'moti', emotion: 'angry', context: 'threat', tags: ['growl'] },
    { id: 'mr_moti_moral_001', text: 'भौ! (निष्ठा हाच सर्वात मोठा गुण!)', character: 'moti', emotion: 'happy', context: 'moral', tags: ['loyalty'] },
    { id: 'mr_moti_narration_001', text: '(मोती शांतपणे ऐकत होता, जणू सगळं समजत होतं)', character: 'moti', emotion: 'neutral', context: 'narration', tags: ['listen'] },
    { id: 'mr_moti_challenge_001', text: 'भौ भौ! (तयार! पळत पळत)', character: 'moti', emotion: 'determined', context: 'challenge', tags: ['ready'] },
  ],
};
