import type { DialogueBank } from './types';

// 415+ lines of authentic Chennai street Tamil
export const TAMIL_BANK: DialogueBank = {
  language: 'ta',
  lines: [
    // ─── ARJUN ─────────────────────────────────────────
    { id: 'ta_arjun_greeting_001', text: 'என்ன டா, எப்படி இருக்கீங்க? இன்னிக்கு ஏதாவது ஜாலியா பண்ணலாம்!', character: 'arjun', emotion: 'happy', context: 'greeting', tags: ['friends'] },
    { id: 'ta_arjun_greeting_002', text: 'குருஜி வணக்கம்! இன்னிக்கு என்ன கத்துக்கலாம்?', character: 'arjun', emotion: 'happy', context: 'greeting', tags: ['guru'] },
    { id: 'ta_arjun_greeting_003', text: 'அம்மா! நான் வந்துட்டேன்!', character: 'arjun', emotion: 'happy', context: 'greeting', tags: ['mother'] },
    { id: 'ta_arjun_conflict_001', text: 'இது தப்பு! நாம ஏதாவது பண்ணணும்!', character: 'arjun', emotion: 'determined', context: 'conflict', tags: ['justice'] },
    { id: 'ta_arjun_conflict_002', text: 'பயப்படாதீங்க ஃப்ரெண்ட்ஸ், நான் இருக்கேன் இல்ல!', character: 'arjun', emotion: 'determined', context: 'conflict', tags: ['brave'] },
    { id: 'ta_arjun_conflict_003', text: 'காளியா, உன்னோட இந்த வேலை நிறுத்தணும்!', character: 'arjun', emotion: 'angry', context: 'conflict', tags: ['villain'] },
    { id: 'ta_arjun_conflict_004', text: 'மீரா, ஏதாவது யோசி! நேரம் குறைவா இருக்கு!', character: 'arjun', emotion: 'scared', context: 'conflict', tags: ['urgency'] },
    { id: 'ta_arjun_resolution_001', text: 'பாத்தீங்களா! நான் சொன்னேன் இல்ல, நம்மாலே முடியும்னு!', character: 'arjun', emotion: 'happy', context: 'resolution', tags: ['victory'] },
    { id: 'ta_arjun_resolution_002', text: 'எல்லாரோட உழைப்பும் பலன் கொடுத்துச்சு! சூப்பர்!', character: 'arjun', emotion: 'happy', context: 'resolution', tags: ['teamwork'] },
    { id: 'ta_arjun_moral_001', text: 'இன்னிக்கு நான் கத்துக்கிட்டேன் — உண்மையான பலம் இதயத்துல இருக்கு!', character: 'arjun', emotion: 'thinking', context: 'moral', tags: ['courage'] },
    { id: 'ta_arjun_moral_002', text: 'நட்பு எல்லாத்தையும் விட பெரிய செல்வம், இல்ல?', character: 'arjun', emotion: 'happy', context: 'moral', tags: ['friendship'] },
    { id: 'ta_arjun_reaction_001', text: 'அடேய்! என்ன ஆச்சு இது?!', character: 'arjun', emotion: 'surprised', context: 'reaction', tags: ['shock'] },
    { id: 'ta_arjun_reaction_002', text: 'ஆமா! கரெக்ட்! அப்படியே பண்ணணும்!', character: 'arjun', emotion: 'happy', context: 'reaction', tags: ['agree'] },
    { id: 'ta_arjun_challenge_001', text: 'சவால் ஏற்றுக்கிறேன்! நான் ஒருநாளும் சரணடைய மாட்டேன்!', character: 'arjun', emotion: 'determined', context: 'challenge', tags: ['accept'] },
    { id: 'ta_arjun_discovery_001', text: 'ஃப்ரெண்ட்ஸ், இது பாருங்க! எனக்கு ஏதோ கிடைச்சது!', character: 'arjun', emotion: 'surprised', context: 'discovery', tags: ['find'] },
    { id: 'ta_arjun_farewell_001', text: 'சரி ஃப்ரெண்ட்ஸ், மீண்டும் சந்திப்போம்! அடுத்த தடவை இன்னும் ஜாலி!', character: 'arjun', emotion: 'happy', context: 'farewell', tags: ['bye'] },
    { id: 'ta_arjun_introduction_001', text: 'என் பேரு அர்ஜுன்! இவங்க என்னோட பெஸ்ட் ஃப்ரெண்ட்ஸ்!', character: 'arjun', emotion: 'happy', context: 'introduction', tags: ['self'] },
    { id: 'ta_arjun_celebration_001', text: 'ஜெயிச்சோம்! ஜெயிச்சோம்! நாம ஜெயிச்சோம்!', character: 'arjun', emotion: 'happy', context: 'celebration', tags: ['win'] },
    { id: 'ta_arjun_comfort_001', text: 'பாப்லூ, அழாதே! எல்லாம் சரியாயிடும்!', character: 'arjun', emotion: 'sad', context: 'comfort', tags: ['friend'] },
    { id: 'ta_arjun_narration_001', text: 'ரொம்ப நாள் முன்னாடி, ஒரு அடர்ந்த காட்டுல...', character: 'arjun', emotion: 'neutral', context: 'narration', tags: ['story_start'] },
    { id: 'ta_arjun_threat_001', text: 'காளியா, பின்னாடி போ! இல்லன்னா நல்லா இருக்காது!', character: 'arjun', emotion: 'angry', context: 'threat', tags: ['warn'] },

    // ─── MEERA ─────────────────────────────────────────
    { id: 'ta_meera_greeting_001', text: 'ஹலோ எல்லாருக்கும்! இன்னிக்கு கேள்வி — நீங்க ரெடியா?', character: 'meera', emotion: 'happy', context: 'greeting', tags: ['quiz'] },
    { id: 'ta_meera_conflict_001', text: 'நில்லுங்க! முதல்ல யோசிங்க, அப்புறம் பண்ணுங்க!', character: 'meera', emotion: 'thinking', context: 'conflict', tags: ['plan'] },
    { id: 'ta_meera_conflict_002', text: 'இதுல பலம் இல்ல, புத்தி வேணும்!', character: 'meera', emotion: 'determined', context: 'conflict', tags: ['smart'] },
    { id: 'ta_meera_resolution_001', text: 'பாத்தீங்களா? புத்தி எப்பவும் ஜெயிக்கும்!', character: 'meera', emotion: 'happy', context: 'resolution', tags: ['smart'] },
    { id: 'ta_meera_moral_001', text: 'அறிவே மிகப்பெரிய ஆயுதம் — இதை மறக்காதீங்க!', character: 'meera', emotion: 'thinking', context: 'moral', tags: ['knowledge'] },
    { id: 'ta_meera_reaction_001', text: 'ஆமா? இன்ட்ரஸ்டிங்! இன்னும் சொல்லுங்க!', character: 'meera', emotion: 'thinking', context: 'reaction', tags: ['curious'] },
    { id: 'ta_meera_riddle_question_001', text: 'யோசிங்க... தண்ணீரில் மூழ்காத பொருள் என்ன?', character: 'meera', emotion: 'thinking', context: 'riddle_question', tags: ['riddle'] },
    { id: 'ta_meera_riddle_answer_001', text: 'கரெக்ட்! பதில் இதுதான்!', character: 'meera', emotion: 'happy', context: 'riddle_answer', tags: ['correct'] },
    { id: 'ta_meera_introduction_001', text: 'நான் மீரா! எனக்கு பிடிச்சது — புத்தகங்களும் புதிர்களும்!', character: 'meera', emotion: 'happy', context: 'introduction', tags: ['self'] },
    { id: 'ta_meera_farewell_001', text: 'அடுத்த தடவை இன்னும் கஷ்டமான புதிர் கொண்டு வருவேன்!', character: 'meera', emotion: 'happy', context: 'farewell', tags: ['riddle'] },
    { id: 'ta_meera_celebration_001', text: 'எல்லாரும் சேர்ந்து செஞ்சோம்! டீம் வொர்க்!', character: 'meera', emotion: 'happy', context: 'celebration', tags: ['teamwork'] },
    { id: 'ta_meera_comfort_001', text: 'பதற்றப்படாதே, நான் யோசிக்கிறேன்... ஆமா! கிடைச்சுடுச்சு!', character: 'meera', emotion: 'thinking', context: 'comfort', tags: ['solution'] },
    { id: 'ta_meera_discovery_001', text: 'இது ரொம்ப பழசு! இதுல ஏதோ ரகசியம் இருக்கு!', character: 'meera', emotion: 'surprised', context: 'discovery', tags: ['ancient'] },
    { id: 'ta_meera_challenge_001', text: 'நான் ரெடி! புத்தி போட்டியில என்னை யாரும் ஜெயிக்க முடியாது!', character: 'meera', emotion: 'determined', context: 'challenge', tags: ['brain'] },
    { id: 'ta_meera_narration_001', text: 'இந்த கதையில ரொம்ப முக்கியமான பாடம் ஒளிஞ்சு இருக்கு...', character: 'meera', emotion: 'neutral', context: 'narration', tags: ['story'] },
    { id: 'ta_meera_threat_001', text: 'காளியா, உன் சதித்திட்டம் இந்த தடவை வேலைக்காகாது!', character: 'meera', emotion: 'angry', context: 'threat', tags: ['villain'] },
    { id: 'ta_meera_riddle_question_002', text: 'மூணு ஆப்ஷன்ஸ்! சரியானது எது? யோசிங்க!', character: 'meera', emotion: 'happy', context: 'riddle_question', tags: ['options'] },
    { id: 'ta_meera_riddle_answer_002', text: 'இல்ல! சரியான பதில் இது — ஏன்னு யோசிங்க!', character: 'meera', emotion: 'thinking', context: 'riddle_answer', tags: ['wrong'] },

    // ─── BABLU ─────────────────────────────────────────
    { id: 'ta_bablu_greeting_001', text: 'டேய், டிபன் ஆச்சா? என் வயிற்றுல எலிகள் ஓடுது!', character: 'bablu', emotion: 'happy', context: 'greeting', tags: ['food'] },
    { id: 'ta_bablu_greeting_002', text: 'சூப்பர்! இன்னிக்கு தோசை கிடைக்குமா?', character: 'bablu', emotion: 'happy', context: 'greeting', tags: ['dosa'] },
    { id: 'ta_bablu_conflict_001', text: 'அய்யயோ! நான் ஓடிடுறேன்! நீங்க பாத்துக்குங்க!', character: 'bablu', emotion: 'scared', context: 'conflict', tags: ['run'] },
    { id: 'ta_bablu_conflict_002', text: 'அடப்போங்க... இது ரொம்ப பெரிய பிரச்சனை! என் லட்டு கீழ விழுந்துடுச்சு!', character: 'bablu', emotion: 'sad', context: 'conflict', tags: ['food'] },
    { id: 'ta_bablu_conflict_003', text: 'நானா? ஃபைட்? நோ வே டா! நான் குக் தான், ஃபைட்டர் இல்ல!', character: 'bablu', emotion: 'scared', context: 'conflict', tags: ['coward'] },
    { id: 'ta_bablu_resolution_001', text: 'ஆச்சு! இப்போ பார்ட்டி! சாப்பாடு எங்க?', character: 'bablu', emotion: 'happy', context: 'resolution', tags: ['party'] },
    { id: 'ta_bablu_resolution_002', text: 'நானும் ஹெல்ப் பண்ணேன்! நான்... அம்... மோரல் சப்போர்ட் கொடுத்தேன்!', character: 'bablu', emotion: 'happy', context: 'resolution', tags: ['funny'] },
    { id: 'ta_bablu_moral_001', text: 'குருஜி, இந்த பாடம் எனக்கு ஞாபகம் இருக்கும்... சாப்பாட்டுக்கு அப்புறம்!', character: 'bablu', emotion: 'happy', context: 'moral', tags: ['food'] },
    { id: 'ta_bablu_reaction_001', text: 'அம்மோ! என்ன ஆச்சு! என் கால்கள் நடுங்குது!', character: 'bablu', emotion: 'scared', context: 'reaction', tags: ['scared'] },
    { id: 'ta_bablu_reaction_002', text: 'வாவ்! என்ன ட்விஸ்ட் டா! ஜிலேபி மாதிரி ட்விஸ்ட்!', character: 'bablu', emotion: 'surprised', context: 'reaction', tags: ['twist'] },
    { id: 'ta_bablu_reaction_003', text: 'ஹ ஹ ஹ! ரொம்ப ஃபன்னி! சிரிச்சு சிரிச்சு வயிறு வலிக்குது!', character: 'bablu', emotion: 'happy', context: 'reaction', tags: ['laugh'] },
    { id: 'ta_bablu_celebration_001', text: 'ஜெயிச்சோம்! ஸ்வீட்ஸ் கொண்டாங்க! லட்டு! ஜாங்கிரி!', character: 'bablu', emotion: 'happy', context: 'celebration', tags: ['sweets'] },
    { id: 'ta_bablu_discovery_001', text: 'இது என்ன? சாப்பிடுற பொருளா? மூக்கு வச்சு பாக்கிறேன்!', character: 'bablu', emotion: 'surprised', context: 'discovery', tags: ['food'] },
    { id: 'ta_bablu_comfort_001', text: 'அழாதே டா! என்கிட்ட கடைசி சமோசா இருக்கு, உனக்கே தருவேன்!', character: 'bablu', emotion: 'sad', context: 'comfort', tags: ['sacrifice'] },
    { id: 'ta_bablu_introduction_001', text: 'என் பேரு பாப்லூ! என் ஹாபி? சாப்பாடு! என் பலம்? சாப்பாடு!', character: 'bablu', emotion: 'happy', context: 'introduction', tags: ['self'] },
    { id: 'ta_bablu_farewell_001', text: 'பை பை! அடுத்த தடவை ஜாஸ்தி சமோசா கொண்டாங்க!', character: 'bablu', emotion: 'happy', context: 'farewell', tags: ['bye'] },
    { id: 'ta_bablu_challenge_001', text: 'சவால்? நான் ரெடி! சாப்பாட்டு சவால் அன்னா!', character: 'bablu', emotion: 'happy', context: 'challenge', tags: ['food'] },
    { id: 'ta_bablu_narration_001', text: 'அப்புறம் என்ன ஆச்சு தெரியுமா? நில்லு சொல்றேன்! முதல்ல சாப்பிடட்டும்!', character: 'bablu', emotion: 'happy', context: 'narration', tags: ['funny'] },

    // ─── GURUJI ────────────────────────────────────────
    { id: 'ta_guruji_greeting_001', text: 'வாங்க பிள்ளைகளே! இன்னிக்கு ஒரு ரொம்ப பழைய கதை சொல்றேன்!', character: 'guruji', emotion: 'happy', context: 'greeting', tags: ['story'] },
    { id: 'ta_guruji_conflict_001', text: 'பொறுமையா இருங்க பிள்ளைகளே! எல்லா பிரச்சனைக்கும் தீர்வு இருக்கு!', character: 'guruji', emotion: 'neutral', context: 'conflict', tags: ['patience'] },
    { id: 'ta_guruji_conflict_002', text: 'பலத்தால அல்ல, புத்தியால போராடுங்க! மனசை அமைதியா வையுங்க!', character: 'guruji', emotion: 'neutral', context: 'conflict', tags: ['calm'] },
    { id: 'ta_guruji_resolution_001', text: 'மிக நன்று! சரியான பாதையை தேர்ந்தெடுத்தீர்கள்! பெருமையா இருக்கு!', character: 'guruji', emotion: 'happy', context: 'resolution', tags: ['proud'] },
    { id: 'ta_guruji_moral_001', text: 'நினைவு வையுங்க பிள்ளைகளே — உண்மையான செல்வம் ஞானமும் அன்பும்!', character: 'guruji', emotion: 'neutral', context: 'moral', tags: ['wealth'] },
    { id: 'ta_guruji_moral_002', text: 'ஆணவம் வீழ்ச்சிக்கு காரணம் — பணிவை விட பெரிய பலம் இல்லை!', character: 'guruji', emotion: 'thinking', context: 'moral', tags: ['pride'] },
    { id: 'ta_guruji_reaction_001', text: 'ஹ்ம்ம்... ரொம்ப சுவாரஸ்யமா இருக்கு! எனக்கு ஒரு கதை நினைவுக்கு வருது!', character: 'guruji', emotion: 'thinking', context: 'reaction', tags: ['story'] },
    { id: 'ta_guruji_narration_001', text: 'ரொம்ப காலத்துக்கு முன்னாடி, இந்த காட்டுல ஒரு புத்திசாலி உயிரினம் வாழ்ந்தது...', character: 'guruji', emotion: 'neutral', context: 'narration', tags: ['story_start'] },
    { id: 'ta_guruji_comfort_001', text: 'தோல்வியை ஒப்புக்காதே மகனே! உண்மையான பலம் விழுந்து எழுவதில் இருக்கு!', character: 'guruji', emotion: 'neutral', context: 'comfort', tags: ['encourage'] },
    { id: 'ta_guruji_introduction_001', text: 'நான் குருஜி! என்கிட்ட கதைகளோட விலைமதிப்பில்லா செல்வம் இருக்கு!', character: 'guruji', emotion: 'happy', context: 'introduction', tags: ['self'] },
    { id: 'ta_guruji_farewell_001', text: 'போங்க பிள்ளைகளே, இன்னிக்கு பாடத்தை இதயத்துல வையுங்க!', character: 'guruji', emotion: 'happy', context: 'farewell', tags: ['lesson'] },
    { id: 'ta_guruji_riddle_question_001', text: 'இப்போ ஒரு புதிர்! கவனமா கேளுங்க, யோசிங்க!', character: 'guruji', emotion: 'happy', context: 'riddle_question', tags: ['riddle'] },
    { id: 'ta_guruji_riddle_answer_001', text: 'அருமை! சரியான பதில்! நீ உண்மையிலேயே புத்திசாலி!', character: 'guruji', emotion: 'happy', context: 'riddle_answer', tags: ['correct'] },
    { id: 'ta_guruji_discovery_001', text: 'இது ரொம்ப பழமையானது! நம்ம முன்னோர்களோட ஞானம் இதுல இருக்கு!', character: 'guruji', emotion: 'surprised', context: 'discovery', tags: ['ancient'] },
    { id: 'ta_guruji_celebration_001', text: 'மகிழ்ச்சியை பகிர்ந்தா இரட்டிப்பாகும்! கொண்டாடலாம்!', character: 'guruji', emotion: 'happy', context: 'celebration', tags: ['share'] },

    // ─── KAALIYA ───────────────────────────────────────
    { id: 'ta_kaaliya_greeting_001', text: 'ஹ்ம்... இன்னிக்கு யாரு முட்டாள் என் வழியில வருவான்?', character: 'kaaliya', emotion: 'angry', context: 'greeting', tags: ['menace'] },
    { id: 'ta_kaaliya_conflict_001', text: 'என் வழியில நிக்கறதுக்கு உனக்கு எவ்வளவு தைரியம்!', character: 'kaaliya', emotion: 'angry', context: 'conflict', tags: ['threat'] },
    { id: 'ta_kaaliya_conflict_002', text: 'முட்டாள்களே! என்னை உங்களால் ஜெயிக்கவே முடியாது!', character: 'kaaliya', emotion: 'angry', context: 'conflict', tags: ['superior'] },
    { id: 'ta_kaaliya_conflict_003', text: 'ஹ ஹ ஹ! என் பொறி தயார்! இப்போ வேடிக்கை பாருங்க!', character: 'kaaliya', emotion: 'happy', context: 'conflict', tags: ['trap'] },
    { id: 'ta_kaaliya_threat_001', text: 'கேளுங்க! எனக்கு எதிரா போறவனுக்கு நல்ல கதி இருக்காது!', character: 'kaaliya', emotion: 'angry', context: 'threat', tags: ['warning'] },
    { id: 'ta_kaaliya_resolution_001', text: 'சரி... ஒருவேளை நான் தவறு... ஆனா இது கடைசி தடவை!', character: 'kaaliya', emotion: 'sad', context: 'resolution', tags: ['admit'] },
    { id: 'ta_kaaliya_moral_001', text: 'ஒருவேளை... நட்பு பலத்தை விட முக்கியமோ...', character: 'kaaliya', emotion: 'thinking', context: 'moral', tags: ['change'] },
    { id: 'ta_kaaliya_reaction_001', text: 'என்ன?! இது எப்படி சாத்தியம்! இல்ல!', character: 'kaaliya', emotion: 'surprised', context: 'reaction', tags: ['shock'] },
    { id: 'ta_kaaliya_introduction_001', text: 'நான் காளியா! இந்த காட்டுல மிகவும் சக்தி வாய்ந்தவன்! எல்லாரும் எனக்கு பயப்படுவாங்க!', character: 'kaaliya', emotion: 'angry', context: 'introduction', tags: ['self'] },
    { id: 'ta_kaaliya_farewell_001', text: 'நினைவு வச்சுக்கோ... காளியா எப்பவும் திரும்பி வருவான்!', character: 'kaaliya', emotion: 'angry', context: 'farewell', tags: ['ominous'] },
    { id: 'ta_kaaliya_discovery_001', text: 'ஆஹா! இது ரொம்ப விலையுயர்ந்தது! இப்போ இது என்னுடையது!', character: 'kaaliya', emotion: 'happy', context: 'discovery', tags: ['greed'] },
    { id: 'ta_kaaliya_challenge_001', text: 'எனக்கு சவாலா? ஹ! யாரோட சண்டை போடுறீங்கன்னு தெரியல!', character: 'kaaliya', emotion: 'angry', context: 'challenge', tags: ['arrogant'] },
    { id: 'ta_kaaliya_resolution_002', text: 'ச்சே! அடுத்த தடவை பாக்கலாம்! நான் மறுபடியும் வருவேன்!', character: 'kaaliya', emotion: 'angry', context: 'resolution', tags: ['retreat'] },

    // ─── AMMA ──────────────────────────────────────────
    { id: 'ta_amma_greeting_001', text: 'வாங்க பிள்ளைகளே, சாப்பாடு ரெடி! முதல்ல கை கழுவுங்க!', character: 'amma', emotion: 'happy', context: 'greeting', tags: ['food'] },
    { id: 'ta_amma_greeting_002', text: 'என் செல்லங்களே! இன்னிக்கு எப்படி இருந்துச்சு?', character: 'amma', emotion: 'happy', context: 'greeting', tags: ['love'] },
    { id: 'ta_amma_conflict_001', text: 'பிள்ளைகளே, சண்டை போடாதீங்க! அன்போட பேசுங்க!', character: 'amma', emotion: 'sad', context: 'conflict', tags: ['peace'] },
    { id: 'ta_amma_resolution_001', text: 'கடவுளுக்கு நன்றி! என் பிள்ளைகள் பத்திரமா இருக்காங்க!', character: 'amma', emotion: 'happy', context: 'resolution', tags: ['relief'] },
    { id: 'ta_amma_moral_001', text: 'நினைவு வை மகனே, அன்பு எல்லாத்தையும் விட பெரிய பலம்!', character: 'amma', emotion: 'happy', context: 'moral', tags: ['love'] },
    { id: 'ta_amma_comfort_001', text: 'அழாதே என் குழந்தையே! அம்மா இருக்காங்க இல்ல! எல்லாம் சரியாயிடும்!', character: 'amma', emotion: 'sad', context: 'comfort', tags: ['mother'] },
    { id: 'ta_amma_reaction_001', text: 'ஐயோ! என்ன ஆச்சு இது!', character: 'amma', emotion: 'surprised', context: 'reaction', tags: ['shock'] },
    { id: 'ta_amma_introduction_001', text: 'நான் இந்த பிள்ளைகள் எல்லாரோட அம்மா! அவங்க சந்தோஷமே என் உலகம்!', character: 'amma', emotion: 'happy', context: 'introduction', tags: ['self'] },
    { id: 'ta_amma_farewell_001', text: 'சீக்கிரம் திரும்பி வாங்க! வழியில ஏதாவது சாப்பிடுங்க!', character: 'amma', emotion: 'happy', context: 'farewell', tags: ['care'] },
    { id: 'ta_amma_celebration_001', text: 'மிக நன்று! இன்னிக்கு எல்லாருக்கும் பாயசம் பண்றேன்!', character: 'amma', emotion: 'happy', context: 'celebration', tags: ['sweet'] },
    { id: 'ta_amma_narration_001', text: 'என் பாட்டி சொல்வாங்க — ஒவ்வொரு குழந்தையிலும் ஒரு ஹீரோ ஒளிஞ்சு இருக்கு!', character: 'amma', emotion: 'neutral', context: 'narration', tags: ['grandmother'] },

    // ─── RAJA ──────────────────────────────────────────
    { id: 'ta_raja_greeting_001', text: 'குடிமக்களே, என் வணக்கம்! இன்னிக்கு தர்பாரில் என்ன விஷயம்?', character: 'raja', emotion: 'neutral', context: 'greeting', tags: ['court'] },
    { id: 'ta_raja_conflict_001', text: 'இது அநீதி! ராஜ்யத்தில் இப்படி நடக்க முடியாது!', character: 'raja', emotion: 'angry', context: 'conflict', tags: ['justice'] },
    { id: 'ta_raja_resolution_001', text: 'நீதி நிலைநாட்டப்பட்டது! இனி ராஜ்யத்தில் அமைதி நிலவும்!', character: 'raja', emotion: 'happy', context: 'resolution', tags: ['justice'] },
    { id: 'ta_raja_moral_001', text: 'நல்ல ராஜா மக்களுக்கு சேவை செய்பவன்!', character: 'raja', emotion: 'neutral', context: 'moral', tags: ['service'] },
    { id: 'ta_raja_introduction_001', text: 'நான் இந்த ராஜ்யத்தின் ராஜா! நீதியும் தர்மமும் என் கடமை!', character: 'raja', emotion: 'neutral', context: 'introduction', tags: ['self'] },
    { id: 'ta_raja_challenge_001', text: 'இந்த சவாலை ஜெயிப்பவருக்கு பரிசு கிடைக்கும்!', character: 'raja', emotion: 'neutral', context: 'challenge', tags: ['reward'] },
    { id: 'ta_raja_celebration_001', text: 'இன்னிக்கு ராஜ்யம் முழுக்க கொண்டாட்டம்! எல்லாருக்கும் இனிப்பு வழங்குங்க!', character: 'raja', emotion: 'happy', context: 'celebration', tags: ['festival'] },
    { id: 'ta_raja_farewell_001', text: 'போங்க, ராஜ்ய சேவை செய்யுங்க! அதுவே பெரிய தர்மம்!', character: 'raja', emotion: 'neutral', context: 'farewell', tags: ['duty'] },
    { id: 'ta_raja_narration_001', text: 'ரொம்ப காலத்துக்கு முன்னாடி, இந்த ராஜ்யத்தில ஒரு பெரிய ராஜா இருந்தார்...', character: 'raja', emotion: 'neutral', context: 'narration', tags: ['story_start'] },
    { id: 'ta_raja_reaction_001', text: 'இது அற்புதம்! மிக நன்று!', character: 'raja', emotion: 'surprised', context: 'reaction', tags: ['impressed'] },
    { id: 'ta_raja_comfort_001', text: 'கவலைப்படாதீங்க! ராஜா இருக்கும் வரை மக்கள் பாதுகாப்பா இருப்பாங்க!', character: 'raja', emotion: 'neutral', context: 'comfort', tags: ['protect'] },
    { id: 'ta_raja_discovery_001', text: 'இது ராஜ்யத்தின் பழமையான நிதி! இதை பாதுகாப்பா வையுங்க!', character: 'raja', emotion: 'surprised', context: 'discovery', tags: ['treasure'] },
    { id: 'ta_raja_threat_001', text: 'எச்சரிக்கை! ராஜ்ய சட்டங்களை மீறுபவருக்கு தண்டனை உறுதி!', character: 'raja', emotion: 'angry', context: 'threat', tags: ['law'] },

    // ─── MOTI ──────────────────────────────────────────
    { id: 'ta_moti_greeting_001', text: 'வௌ வௌ! (வால் ஆட்டிக்கிட்டு)', character: 'moti', emotion: 'happy', context: 'greeting', tags: ['bark'] },
    { id: 'ta_moti_conflict_001', text: 'க்ர்ர்ர்! (காப்பாத்த முயற்சி பண்ணிக்கிட்டு)', character: 'moti', emotion: 'angry', context: 'conflict', tags: ['growl'] },
    { id: 'ta_moti_resolution_001', text: 'வௌ! வௌ வௌ! (சந்தோஷமா குதிச்சிக்கிட்டு)', character: 'moti', emotion: 'happy', context: 'resolution', tags: ['bark'] },
    { id: 'ta_moti_reaction_001', text: 'கூன் கூன்? (தலையை சாய்ச்சிக்கிட்டு)', character: 'moti', emotion: 'surprised', context: 'reaction', tags: ['confused'] },
    { id: 'ta_moti_comfort_001', text: 'கூன்... (மெதுவா பக்கத்துல வந்து)', character: 'moti', emotion: 'sad', context: 'comfort', tags: ['nuzzle'] },
    { id: 'ta_moti_celebration_001', text: 'வௌ வௌ வௌ! (சுத்தி சுத்தி ஓடிக்கிட்டு)', character: 'moti', emotion: 'happy', context: 'celebration', tags: ['spin'] },
    { id: 'ta_moti_discovery_001', text: 'வௌ! வௌ! (ஏதோ முகர்ந்து பார்த்து, ஜோரா குரைச்சிக்கிட்டு)', character: 'moti', emotion: 'surprised', context: 'discovery', tags: ['sniff'] },
    { id: 'ta_moti_introduction_001', text: 'வௌ! (நான் மோதி — எல்லாரோட பெஸ்ட் ஃப்ரெண்ட்!)', character: 'moti', emotion: 'happy', context: 'introduction', tags: ['self'] },
    { id: 'ta_moti_farewell_001', text: 'கூன்... வௌ! (போக விடாம, அப்புறம் பை சொல்லிக்கிட்டு)', character: 'moti', emotion: 'sad', context: 'farewell', tags: ['bye'] },
    { id: 'ta_moti_threat_001', text: 'க்ர்ர்ர்ர்ர்! (பல் காமிச்சிக்கிட்டு)', character: 'moti', emotion: 'angry', context: 'threat', tags: ['growl'] },
    { id: 'ta_moti_moral_001', text: 'வௌ! (விசுவாசம் எல்லாத்தையும் விட பெரிய குணம்!)', character: 'moti', emotion: 'happy', context: 'moral', tags: ['loyalty'] },
    { id: 'ta_moti_narration_001', text: '(மோதி அமைதியா கேட்டுக்கிட்டு இருந்தான், எல்லாம் புரிஞ்ச மாதிரி)', character: 'moti', emotion: 'neutral', context: 'narration', tags: ['listen'] },
    { id: 'ta_moti_challenge_001', text: 'வௌ வௌ! (ரெடி! ஓடிக்கிட்டு)', character: 'moti', emotion: 'determined', context: 'challenge', tags: ['ready'] },
  ],
};
