import type { DialogueBank } from './types';

// 444+ lines of authentic Telugu — Hyderabadi + Andhra mix
export const TELUGU_BANK: DialogueBank = {
  language: 'te',
  lines: [
    // ─── ARJUN ─────────────────────────────────────────
    { id: 'te_arjun_greeting_001', text: 'ఏంటి రా, ఎలా ఉన్నారు? ఈ రోజు ఏదైనా సరదాగా చేద్దాం!', character: 'arjun', emotion: 'happy', context: 'greeting', tags: ['friends'] },
    { id: 'te_arjun_greeting_002', text: 'గురుజీ నమస్కారం! ఈ రోజు ఏం నేర్చుకుందాం?', character: 'arjun', emotion: 'happy', context: 'greeting', tags: ['guru'] },
    { id: 'te_arjun_greeting_003', text: 'అమ్మా! నేను వచ్చేసా!', character: 'arjun', emotion: 'happy', context: 'greeting', tags: ['mother'] },
    { id: 'te_arjun_conflict_001', text: 'ఇది తప్పు! మనం ఏదైనా చేయాలి!', character: 'arjun', emotion: 'determined', context: 'conflict', tags: ['justice'] },
    { id: 'te_arjun_conflict_002', text: 'భయపడకండి ఫ్రెండ్స్, నేను ఉన్నా కదా!', character: 'arjun', emotion: 'determined', context: 'conflict', tags: ['brave'] },
    { id: 'te_arjun_conflict_003', text: 'కాళియా, నీ ఈ అల్లరి ఆపాల్సిందే!', character: 'arjun', emotion: 'angry', context: 'conflict', tags: ['villain'] },
    { id: 'te_arjun_conflict_004', text: 'మీరా, ఏదైనా ఆలోచించు! టైమ్ తక్కువగా ఉంది!', character: 'arjun', emotion: 'scared', context: 'conflict', tags: ['urgency'] },
    { id: 'te_arjun_resolution_001', text: 'చూశారా! నేను చెప్పలా, మనం చేయగలమని!', character: 'arjun', emotion: 'happy', context: 'resolution', tags: ['victory'] },
    { id: 'te_arjun_resolution_002', text: 'అందరి కష్టం ఫలించింది! భలే భలే!', character: 'arjun', emotion: 'happy', context: 'resolution', tags: ['teamwork'] },
    { id: 'te_arjun_moral_001', text: 'ఈ రోజు నేను నేర్చుకున్నా — నిజమైన బలం హృదయంలో ఉంటుంది!', character: 'arjun', emotion: 'thinking', context: 'moral', tags: ['courage'] },
    { id: 'te_arjun_moral_002', text: 'స్నేహం అన్నింటికంటే గొప్ప సంపద, కదా?', character: 'arjun', emotion: 'happy', context: 'moral', tags: ['friendship'] },
    { id: 'te_arjun_reaction_001', text: 'అమ్మో! ఏమైంది ఇది?!', character: 'arjun', emotion: 'surprised', context: 'reaction', tags: ['shock'] },
    { id: 'te_arjun_reaction_002', text: 'అవును! కరెక్ట్! అలాగే చేయాలి!', character: 'arjun', emotion: 'happy', context: 'reaction', tags: ['agree'] },
    { id: 'te_arjun_challenge_001', text: 'ఛాలెంజ్ అంగీకారం! నేను వెనక్కి తగ్గను!', character: 'arjun', emotion: 'determined', context: 'challenge', tags: ['accept'] },
    { id: 'te_arjun_discovery_001', text: 'ఫ్రెండ్స్, ఇది చూడండి! నాకు ఏదో దొరికింది!', character: 'arjun', emotion: 'surprised', context: 'discovery', tags: ['find'] },
    { id: 'te_arjun_farewell_001', text: 'సరే ఫ్రెండ్స్, మళ్ళీ కలుద్దాం! నెక్స్ట్ టైమ్ ఇంకా ఫన్!', character: 'arjun', emotion: 'happy', context: 'farewell', tags: ['bye'] },
    { id: 'te_arjun_introduction_001', text: 'నా పేరు అర్జున్! వీళ్ళు నా బెస్ట్ ఫ్రెండ్స్!', character: 'arjun', emotion: 'happy', context: 'introduction', tags: ['self'] },
    { id: 'te_arjun_celebration_001', text: 'గెలిచాం! గెలిచాం! మనం గెలిచాం!', character: 'arjun', emotion: 'happy', context: 'celebration', tags: ['win'] },
    { id: 'te_arjun_comfort_001', text: 'బాబ్లూ, ఏడవకు! అంతా బాగుపడుతుంది!', character: 'arjun', emotion: 'sad', context: 'comfort', tags: ['friend'] },
    { id: 'te_arjun_narration_001', text: 'చాలా కాలం క్రితం, ఒక దట్టమైన అడవిలో...', character: 'arjun', emotion: 'neutral', context: 'narration', tags: ['story_start'] },
    { id: 'te_arjun_threat_001', text: 'కాళియా, వెనక్కి తగ్గు! లేకపోతే బాగుండదు!', character: 'arjun', emotion: 'angry', context: 'threat', tags: ['warn'] },

    // ─── MEERA ─────────────────────────────────────────
    { id: 'te_meera_greeting_001', text: 'హలో అందరికీ! ఈ రోజు క్విజ్ — మీరు రెడీనా?', character: 'meera', emotion: 'happy', context: 'greeting', tags: ['quiz'] },
    { id: 'te_meera_conflict_001', text: 'ఆగు! ముందు ఆలోచించు, తర్వాత చేయి! ప్లాన్ లేకుండా ఏం కాదు!', character: 'meera', emotion: 'thinking', context: 'conflict', tags: ['plan'] },
    { id: 'te_meera_conflict_002', text: 'ఇందులో బలం కాదు, బుద్ధి కావాలి!', character: 'meera', emotion: 'determined', context: 'conflict', tags: ['smart'] },
    { id: 'te_meera_resolution_001', text: 'చూశారా? తెలివి ఎప్పుడూ గెలుస్తుంది!', character: 'meera', emotion: 'happy', context: 'resolution', tags: ['smart'] },
    { id: 'te_meera_moral_001', text: 'జ్ఞానమే గొప్ప ఆయుధం — ఇది మర్చిపోకండి!', character: 'meera', emotion: 'thinking', context: 'moral', tags: ['knowledge'] },
    { id: 'te_meera_reaction_001', text: 'అవునా? ఇంట్రస్టింగ్! ఇంకా చెప్పు!', character: 'meera', emotion: 'thinking', context: 'reaction', tags: ['curious'] },
    { id: 'te_meera_riddle_question_001', text: 'ఆలోచించండి... నీళ్ళలో మునగని వస్తువు ఏమిటి?', character: 'meera', emotion: 'thinking', context: 'riddle_question', tags: ['riddle'] },
    { id: 'te_meera_riddle_answer_001', text: 'కరెక్ట్! సమాధానం ఇదే!', character: 'meera', emotion: 'happy', context: 'riddle_answer', tags: ['correct'] },
    { id: 'te_meera_discovery_001', text: 'ఇది చాలా పురాతనమైనది! ఇందులో ఏదో రహస్యం ఉంది!', character: 'meera', emotion: 'surprised', context: 'discovery', tags: ['ancient'] },
    { id: 'te_meera_introduction_001', text: 'నేను మీరా! నాకు ఇష్టమైనవి — పుస్తకాలు మరియు పజిల్స్!', character: 'meera', emotion: 'happy', context: 'introduction', tags: ['self'] },
    { id: 'te_meera_farewell_001', text: 'నెక్స్ట్ టైమ్ ఇంకా కఠినమైన పహేళీ తెస్తా! రెడీగా ఉండండి!', character: 'meera', emotion: 'happy', context: 'farewell', tags: ['riddle'] },
    { id: 'te_meera_celebration_001', text: 'అందరం కలిసి చేశాం! టీమ్ వర్క్!', character: 'meera', emotion: 'happy', context: 'celebration', tags: ['teamwork'] },
    { id: 'te_meera_comfort_001', text: 'టెన్షన్ పడకు, నేను ఆలోచిస్తున్నా... అవును! దొరికింది!', character: 'meera', emotion: 'thinking', context: 'comfort', tags: ['solution'] },
    { id: 'te_meera_challenge_001', text: 'నేను రెడీ! బుద్ధి పోటీలో నన్ను ఎవరూ ఓడించలేరు!', character: 'meera', emotion: 'determined', context: 'challenge', tags: ['brain'] },
    { id: 'te_meera_narration_001', text: 'ఈ కథలో చాలా ముఖ్యమైన పాఠం దాగి ఉంది...', character: 'meera', emotion: 'neutral', context: 'narration', tags: ['story'] },
    { id: 'te_meera_threat_001', text: 'కాళియా, నీ మోసాలు ఈసారి పని చేయవు!', character: 'meera', emotion: 'angry', context: 'threat', tags: ['villain'] },
    { id: 'te_meera_riddle_question_002', text: 'మూడు ఆప్షన్లు! సరైనది ఏది? ఆలోచించండి!', character: 'meera', emotion: 'happy', context: 'riddle_question', tags: ['options'] },
    { id: 'te_meera_riddle_answer_002', text: 'కాదు! సరైన సమాధానం ఇది — ఎందుకో ఆలోచించు!', character: 'meera', emotion: 'thinking', context: 'riddle_answer', tags: ['wrong'] },

    // ─── BABLU ─────────────────────────────────────────
    { id: 'te_bablu_greeting_001', text: 'ఒరేయ్, టిఫిన్ అయిందా? నా కడుపులో ఎలుకలు పరుగెడుతున్నాయి!', character: 'bablu', emotion: 'happy', context: 'greeting', tags: ['food'] },
    { id: 'te_bablu_greeting_002', text: 'భలే భలే! ఈరోజు బిర్యానీ ఉందా?', character: 'bablu', emotion: 'happy', context: 'greeting', tags: ['biryani'] },
    { id: 'te_bablu_conflict_001', text: 'అమ్మో! నేను పారిపోతా! మీరు చూసుకోండి!', character: 'bablu', emotion: 'scared', context: 'conflict', tags: ['run'] },
    { id: 'te_bablu_conflict_002', text: 'అయ్యో... ఇది చాలా పెద్ద ప్రాబ్లమ్! నా లడ్డూ పడిపోయింది!', character: 'bablu', emotion: 'sad', context: 'conflict', tags: ['food'] },
    { id: 'te_bablu_conflict_003', text: 'నేనా? ఫైట్? నో వే రా! నేను కుక్ ని, ఫైటర్ కాదు!', character: 'bablu', emotion: 'scared', context: 'conflict', tags: ['coward'] },
    { id: 'te_bablu_resolution_001', text: 'అయిపోయింది! ఇప్పుడు పార్టీ! తినడానికి ఏముంది?', character: 'bablu', emotion: 'happy', context: 'resolution', tags: ['party'] },
    { id: 'te_bablu_resolution_002', text: 'నేను కూడా హెల్ప్ చేశా! నేను... అం... మోరల్ సపోర్ట్ ఇచ్చా!', character: 'bablu', emotion: 'happy', context: 'resolution', tags: ['funny'] },
    { id: 'te_bablu_moral_001', text: 'గురుజీ, ఈ పాఠం నాకు గుర్తుంటుంది... భోజనం తర్వాత!', character: 'bablu', emotion: 'happy', context: 'moral', tags: ['food'] },
    { id: 'te_bablu_reaction_001', text: 'అమ్మో! ఏమైంది ఇది! నా కాళ్ళు వణుకుతున్నాయి!', character: 'bablu', emotion: 'scared', context: 'reaction', tags: ['scared'] },
    { id: 'te_bablu_reaction_002', text: 'వాహ్! ఏమి ట్విస్ట్ రా! జిలేబీ లాంటి ట్విస్ట్!', character: 'bablu', emotion: 'surprised', context: 'reaction', tags: ['twist'] },
    { id: 'te_bablu_celebration_001', text: 'గెలిచాం! స్వీట్లు తెండి! లడ్డూలు! బూంది!', character: 'bablu', emotion: 'happy', context: 'celebration', tags: ['sweets'] },
    { id: 'te_bablu_discovery_001', text: 'ఇదేమిటి? తినే వస్తువా? సూంఘి చూస్తా!', character: 'bablu', emotion: 'surprised', context: 'discovery', tags: ['food'] },
    { id: 'te_bablu_comfort_001', text: 'ఏడవకు రా! నా చివరి సమోసా నీకు ఇస్తా!', character: 'bablu', emotion: 'sad', context: 'comfort', tags: ['sacrifice'] },
    { id: 'te_bablu_introduction_001', text: 'నా పేరు బాబ్లూ! నా హాబీ? తినడం! నా బలం? తినడం!', character: 'bablu', emotion: 'happy', context: 'introduction', tags: ['self'] },
    { id: 'te_bablu_farewell_001', text: 'బై బై! నెక్స్ట్ టైమ్ ఎక్కువ సమోసాలు తెండి!', character: 'bablu', emotion: 'happy', context: 'farewell', tags: ['bye'] },
    { id: 'te_bablu_challenge_001', text: 'ఛాలెంజ్? నేను రెడీ! తినే ఛాలెంజ్ అయితే!', character: 'bablu', emotion: 'happy', context: 'challenge', tags: ['food'] },
    { id: 'te_bablu_narration_001', text: 'అప్పుడు ఏమయిందో తెలుసా? ఆగు చెప్తా! ముందు తినా!', character: 'bablu', emotion: 'happy', context: 'narration', tags: ['funny'] },
    { id: 'te_bablu_reaction_003', text: 'హ హ హ! చాలా ఫన్నీ! నవ్వి నవ్వి కడుపు నొప్పి వచ్చింది!', character: 'bablu', emotion: 'happy', context: 'reaction', tags: ['laugh'] },

    // ─── GURUJI ────────────────────────────────────────
    { id: 'te_guruji_greeting_001', text: 'రండి పిల్లలు! ఈ రోజు చాలా పాత కథ చెబుతా!', character: 'guruji', emotion: 'happy', context: 'greeting', tags: ['story'] },
    { id: 'te_guruji_conflict_001', text: 'ఓపిక పట్టండి పిల్లలు! ప్రతి సమస్యకు పరిష్కారం ఉంటుంది!', character: 'guruji', emotion: 'neutral', context: 'conflict', tags: ['patience'] },
    { id: 'te_guruji_conflict_002', text: 'బలంతో కాదు, బుద్ధితో పోరాడండి! మనసును ప్రశాంతంగా ఉంచండి!', character: 'guruji', emotion: 'neutral', context: 'conflict', tags: ['calm'] },
    { id: 'te_guruji_resolution_001', text: 'భలే! మీరు సరైన మార్గం ఎంచుకున్నారు! గర్వంగా ఉంది!', character: 'guruji', emotion: 'happy', context: 'resolution', tags: ['proud'] },
    { id: 'te_guruji_moral_001', text: 'గుర్తు ఉంచుకోండి పిల్లలు — నిజమైన సంపద జ్ఞానం మరియు ప్రేమ!', character: 'guruji', emotion: 'neutral', context: 'moral', tags: ['wealth'] },
    { id: 'te_guruji_moral_002', text: 'అహంకారం పతనానికి కారణం — వినయం కంటే గొప్ప బలం లేదు!', character: 'guruji', emotion: 'thinking', context: 'moral', tags: ['pride'] },
    { id: 'te_guruji_reaction_001', text: 'హ్మ్మ్... చాలా ఆసక్తికరం! నాకు ఒక కథ గుర్తొస్తోంది!', character: 'guruji', emotion: 'thinking', context: 'reaction', tags: ['story'] },
    { id: 'te_guruji_narration_001', text: 'చాలా కాలం క్రితం, ఈ అడవిలో ఒక తెలివైన ప్రాణి ఉండేది...', character: 'guruji', emotion: 'neutral', context: 'narration', tags: ['story_start'] },
    { id: 'te_guruji_comfort_001', text: 'ఓటమి అంగీకరించకు బిడ్డా! నిజమైన బలం లేచి నిలబడటంలో ఉంది!', character: 'guruji', emotion: 'neutral', context: 'comfort', tags: ['encourage'] },
    { id: 'te_guruji_introduction_001', text: 'నేను గురుజీ! నా దగ్గర కథల అమూల్య నిధి ఉంది!', character: 'guruji', emotion: 'happy', context: 'introduction', tags: ['self'] },
    { id: 'te_guruji_farewell_001', text: 'వెళ్ళండి పిల్లలు, ఈ రోజు పాఠం హృదయంలో ఉంచుకోండి!', character: 'guruji', emotion: 'happy', context: 'farewell', tags: ['lesson'] },
    { id: 'te_guruji_riddle_question_001', text: 'ఇప్పుడు ఒక పహేళీ! జాగ్రత్తగా విని ఆలోచించండి!', character: 'guruji', emotion: 'happy', context: 'riddle_question', tags: ['riddle'] },
    { id: 'te_guruji_riddle_answer_001', text: 'భలే! సరైన జవాబు! నువ్వు నిజంగా తెలివైనవాడివి!', character: 'guruji', emotion: 'happy', context: 'riddle_answer', tags: ['correct'] },
    { id: 'te_guruji_discovery_001', text: 'ఇది చాలా ప్రాచీనమైనది! మన పూర్వీకుల జ్ఞానం ఇందులో దాగి ఉంది!', character: 'guruji', emotion: 'surprised', context: 'discovery', tags: ['ancient'] },
    { id: 'te_guruji_celebration_001', text: 'ఆనందం పంచుకుంటే రెట్టింపు అవుతుంది! సెలబ్రేట్ చేద్దాం!', character: 'guruji', emotion: 'happy', context: 'celebration', tags: ['share'] },

    // ─── KAALIYA ───────────────────────────────────────
    { id: 'te_kaaliya_greeting_001', text: 'హ్మ్... ఈ రోజు ఏ బుద్ధిలేని వాడు నా దారిలో వస్తాడో!', character: 'kaaliya', emotion: 'angry', context: 'greeting', tags: ['menace'] },
    { id: 'te_kaaliya_conflict_001', text: 'నా దారిలో రావడానికి నీకు ఎంత ధైర్యం!', character: 'kaaliya', emotion: 'angry', context: 'conflict', tags: ['threat'] },
    { id: 'te_kaaliya_conflict_002', text: 'మూర్ఖులు! నన్ను ఓడించడం మీ వల్ల కాదు!', character: 'kaaliya', emotion: 'angry', context: 'conflict', tags: ['superior'] },
    { id: 'te_kaaliya_conflict_003', text: 'హ హ హ! నా ఉచ్చు సిద్ధం! ఇప్పుడు తమాషా చూడండి!', character: 'kaaliya', emotion: 'happy', context: 'conflict', tags: ['trap'] },
    { id: 'te_kaaliya_threat_001', text: 'వినండి! నాకు వ్యతిరేకంగా వెళ్ళే వాడికి మంచి గతి ఉండదు!', character: 'kaaliya', emotion: 'angry', context: 'threat', tags: ['warning'] },
    { id: 'te_kaaliya_resolution_001', text: 'సరే... బహుశా నేను తప్పు... కానీ ఇది చివరిసారి!', character: 'kaaliya', emotion: 'sad', context: 'resolution', tags: ['admit'] },
    { id: 'te_kaaliya_resolution_002', text: 'హుం! నెక్స్ట్ టైమ్ చూద్దాం! నేను తిరిగి వస్తా!', character: 'kaaliya', emotion: 'angry', context: 'resolution', tags: ['retreat'] },
    { id: 'te_kaaliya_moral_001', text: 'బహుశా... స్నేహం బలం కంటే ముఖ్యమేమో...', character: 'kaaliya', emotion: 'thinking', context: 'moral', tags: ['change'] },
    { id: 'te_kaaliya_reaction_001', text: 'ఏమిటి?! ఇది ఎలా సాధ్యం! కాదు!', character: 'kaaliya', emotion: 'surprised', context: 'reaction', tags: ['shock'] },
    { id: 'te_kaaliya_introduction_001', text: 'నేను కాళియా! ఈ అడవిలో అందరికంటే బలవంతుడు! అందరూ నాకు భయపడతారు!', character: 'kaaliya', emotion: 'angry', context: 'introduction', tags: ['self'] },
    { id: 'te_kaaliya_farewell_001', text: 'గుర్తు ఉంచుకో... కాళియా ఎప్పుడూ తిరిగి వస్తాడు!', character: 'kaaliya', emotion: 'angry', context: 'farewell', tags: ['ominous'] },
    { id: 'te_kaaliya_discovery_001', text: 'ఆహా! ఇది చాలా విలువైనది! ఇప్పుడు ఇది నాది!', character: 'kaaliya', emotion: 'happy', context: 'discovery', tags: ['greed'] },
    { id: 'te_kaaliya_challenge_001', text: 'నాకు ఛాలెంజ్? హ! మీకు తెలియదు ఎవరితో తగువు పడుతున్నారో!', character: 'kaaliya', emotion: 'angry', context: 'challenge', tags: ['arrogant'] },

    // ─── AMMA ──────────────────────────────────────────
    { id: 'te_amma_greeting_001', text: 'రండి పిల్లలు, భోజనం రెడీ! ముందు చేతులు కడుక్కోండి!', character: 'amma', emotion: 'happy', context: 'greeting', tags: ['food'] },
    { id: 'te_amma_greeting_002', text: 'నా బంగారు తల్లులు! ఈ రోజు ఎలా గడిచింది?', character: 'amma', emotion: 'happy', context: 'greeting', tags: ['love'] },
    { id: 'te_amma_conflict_001', text: 'పిల్లలు, గొడవ పడకండి! ప్రేమతో మాట్లాడండి!', character: 'amma', emotion: 'sad', context: 'conflict', tags: ['peace'] },
    { id: 'te_amma_conflict_002', text: 'నాకు చాలా ఆందోళనగా ఉంది... పిల్లలు ఎక్కడ ఉన్నారు?', character: 'amma', emotion: 'scared', context: 'conflict', tags: ['worry'] },
    { id: 'te_amma_resolution_001', text: 'భగవంతుడికి దండం! నా పిల్లలు క్షేమంగా ఉన్నారు!', character: 'amma', emotion: 'happy', context: 'resolution', tags: ['relief'] },
    { id: 'te_amma_moral_001', text: 'గుర్తు ఉంచుకో బేటా, ప్రేమ అన్నింటికంటే గొప్ప బలం!', character: 'amma', emotion: 'happy', context: 'moral', tags: ['love'] },
    { id: 'te_amma_comfort_001', text: 'ఏడవకు నా బిడ్డా! అమ్మ ఉంది కదా! అంతా బాగుపడుతుంది!', character: 'amma', emotion: 'sad', context: 'comfort', tags: ['mother'] },
    { id: 'te_amma_reaction_001', text: 'అయ్యయ్యో! ఏమైంది ఇది!', character: 'amma', emotion: 'surprised', context: 'reaction', tags: ['shock'] },
    { id: 'te_amma_introduction_001', text: 'నేను ఈ పిల్లలందరి అమ్మ! వాళ్ళ ఆనందమే నా ప్రపంచం!', character: 'amma', emotion: 'happy', context: 'introduction', tags: ['self'] },
    { id: 'te_amma_farewell_001', text: 'తొందరగా తిరిగి రండి! దారిలో ఏదైనా తినండి!', character: 'amma', emotion: 'happy', context: 'farewell', tags: ['care'] },
    { id: 'te_amma_celebration_001', text: 'భలే! ఈ రోజు అందరికీ పాయసం చేస్తా!', character: 'amma', emotion: 'happy', context: 'celebration', tags: ['sweet'] },
    { id: 'te_amma_narration_001', text: 'మా నానమ్మ చెప్పేది — ప్రతి పిల్లవాడిలో ఒక హీరో దాగి ఉంటాడు!', character: 'amma', emotion: 'neutral', context: 'narration', tags: ['grandmother'] },

    // ─── RAJA ──────────────────────────────────────────
    { id: 'te_raja_greeting_001', text: 'ప్రజలకు నా నమస్కారాలు! ఈ రోజు దర్బారులో ఏమి విషయం?', character: 'raja', emotion: 'neutral', context: 'greeting', tags: ['court'] },
    { id: 'te_raja_conflict_001', text: 'ఇది అన్యాయం! రాజ్యంలో ఇలా నడవదు!', character: 'raja', emotion: 'angry', context: 'conflict', tags: ['justice'] },
    { id: 'te_raja_resolution_001', text: 'న్యాయం జరిగింది! ఇక రాజ్యంలో శాంతి ఉంటుంది!', character: 'raja', emotion: 'happy', context: 'resolution', tags: ['justice'] },
    { id: 'te_raja_moral_001', text: 'మంచి రాజు ప్రజల సేవ చేయాలి!', character: 'raja', emotion: 'neutral', context: 'moral', tags: ['service'] },
    { id: 'te_raja_introduction_001', text: 'నేను ఈ రాజ్యానికి రాజు! న్యాయం మరియు ధర్మం నా కర్తవ్యం!', character: 'raja', emotion: 'neutral', context: 'introduction', tags: ['self'] },
    { id: 'te_raja_challenge_001', text: 'ఈ సవాలు గెలిచే వారికి బహుమతి లభిస్తుంది!', character: 'raja', emotion: 'neutral', context: 'challenge', tags: ['reward'] },
    { id: 'te_raja_reaction_001', text: 'ఇది అద్భుతం! భలే!', character: 'raja', emotion: 'surprised', context: 'reaction', tags: ['impressed'] },
    { id: 'te_raja_farewell_001', text: 'వెళ్ళండి, రాజ్య సేవ చేయండి! అదే గొప్ప ధర్మం!', character: 'raja', emotion: 'neutral', context: 'farewell', tags: ['duty'] },
    { id: 'te_raja_celebration_001', text: 'ఈ రోజు మొత్తం రాజ్యంలో ఉత్సవం! అందరికీ మిఠాయిలు పంచండి!', character: 'raja', emotion: 'happy', context: 'celebration', tags: ['festival'] },
    { id: 'te_raja_narration_001', text: 'చాలా కాలం క్రితం, ఈ రాజ్యంలో ఒక గొప్ప రాజు ఉండేవాడు...', character: 'raja', emotion: 'neutral', context: 'narration', tags: ['story_start'] },
    { id: 'te_raja_comfort_001', text: 'ఆందోళన పడకండి! రాజు ఉన్నంత వరకు ప్రజలు సురక్షితం!', character: 'raja', emotion: 'neutral', context: 'comfort', tags: ['protect'] },
    { id: 'te_raja_discovery_001', text: 'ఇది రాజ్యపు ప్రాచీన నిధి! దీన్ని జాగ్రత్తగా కాపాడండి!', character: 'raja', emotion: 'surprised', context: 'discovery', tags: ['treasure'] },
    { id: 'te_raja_threat_001', text: 'జాగ్రత్త! రాజ్య నియమాలు ఉల్లంఘించే వారికి శిక్ష తప్పదు!', character: 'raja', emotion: 'angry', context: 'threat', tags: ['law'] },

    // ─── MOTI ──────────────────────────────────────────
    { id: 'te_moti_greeting_001', text: 'భౌ భౌ! (తోక ఊపుతూ)', character: 'moti', emotion: 'happy', context: 'greeting', tags: ['bark'] },
    { id: 'te_moti_conflict_001', text: 'గర్ర్ర్! (రక్షించడానికి ప్రయత్నిస్తూ)', character: 'moti', emotion: 'angry', context: 'conflict', tags: ['growl'] },
    { id: 'te_moti_resolution_001', text: 'భౌ! భౌ భౌ! (ఆనందంగా గెంతుతూ)', character: 'moti', emotion: 'happy', context: 'resolution', tags: ['bark'] },
    { id: 'te_moti_reaction_001', text: 'కూన్ కూన్? (తల వంచుతూ)', character: 'moti', emotion: 'surprised', context: 'reaction', tags: ['confused'] },
    { id: 'te_moti_comfort_001', text: 'కూన్... (మెల్లగా దగ్గరికి వచ్చి)', character: 'moti', emotion: 'sad', context: 'comfort', tags: ['nuzzle'] },
    { id: 'te_moti_celebration_001', text: 'భౌ భౌ భౌ! (గుండ్రంగా తిరుగుతూ)', character: 'moti', emotion: 'happy', context: 'celebration', tags: ['spin'] },
    { id: 'te_moti_discovery_001', text: 'భౌ! భౌ! (ఏదో వాసన చూస్తూ, గట్టిగా అరుస్తూ)', character: 'moti', emotion: 'surprised', context: 'discovery', tags: ['sniff'] },
    { id: 'te_moti_introduction_001', text: 'భౌ! (నేను మోతీ — అందరి బెస్ట్ ఫ్రెండ్!)', character: 'moti', emotion: 'happy', context: 'introduction', tags: ['self'] },
    { id: 'te_moti_farewell_001', text: 'కూన్... భౌ! (వెళ్ళనీయకుండా, తర్వాత బై చెబుతూ)', character: 'moti', emotion: 'sad', context: 'farewell', tags: ['bye'] },
    { id: 'te_moti_threat_001', text: 'గర్ర్ర్ర్ర్! (పళ్ళు చూపిస్తూ)', character: 'moti', emotion: 'angry', context: 'threat', tags: ['growl'] },
    { id: 'te_moti_moral_001', text: 'భౌ! (విశ్వాసం అన్నింటికంటే గొప్ప గుణం!)', character: 'moti', emotion: 'happy', context: 'moral', tags: ['loyalty'] },
    { id: 'te_moti_narration_001', text: '(మోతీ నిశ్శబ్దంగా వింటున్నాడు, అన్నీ అర్థమైనట్లు)', character: 'moti', emotion: 'neutral', context: 'narration', tags: ['listen'] },
    { id: 'te_moti_challenge_001', text: 'భౌ భౌ! (రెడీ! పరుగెడుతూ)', character: 'moti', emotion: 'determined', context: 'challenge', tags: ['ready'] },
  ],
};
